using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;


public static class ShipNames
{
    private static List<string> allNames;

    public static string GetRandom()
    {
        return allNames.RandomElement();
    }

    public static void Init()
    {
        allNames = new List<string>()
        {
            "Above Board",
            "Adroit",
            "Algorab",
            "Alexandrine",
            "Alright Already",
            "Amalfi",
            "Amphioxus",
            "Ancient Mariner",
            "Apollo Zero",
            "Arabia Felix",
            "Argo Navis",
            "Arktos",
            "Astarte",
            "Atalanta",
        "Aurora Australis",
    "Austral Moon",
    "Banasdan Argosy",
    "Barbican Star",
    "Baroness Duperre",
    "Bianxing",
    "Bittersweet",
    "Black Cat's Luck",
    "Black Lotus",
    "Bluebottle",
    "Bold Venture",
    "Bottom Line",
    "Brass Hind",
    "Cachalot",
    "Caledon Dancer",
    "Cardinal Grosbeak",
    "Carrymore",
    "Chanticleer",
    "Childe Harold",
    "Cinquefoil",
    "Coreward Lion",
    "Compass Rose",
    "Confidence",
    "Contractor",
    "Cor Caroli",
    "Corvid",
    "Count Meyin",
    "Crane Fly",
    "Croix de Sansterre",
    "Danphe",
    "Daikoku",
    "Daystar",
    "Dead Reckoning",
    "Devil's Fifth",
    "Delgado Vincennes",
    "Diamond Sun",
    "Dolphin of Mora",
    "Dorothy Gail",
    "Durable",
    "Dziban",
    "Ecorcheur",
    "Eglantine",
    "Elsinore",
    "Eltanin",
    "En Passant",
    "Enchantress of Space",
    "Enki Clipper",
    "Entre Nous",
    "Esterlin",
    "Euphonia",
    "Evergreen",
    "Fair Elizabeth",
    "Falcon Marquis",
    "Filthy Lucre",
    "Final Option",
    "Flying Colours",
    "Fortune",
    "Four Finger Discount",
    "Fraser Red",
    "Friday",
    "From Far Away",
    "Galeota",
    "Genêt d’Espagne",
    "Giauzar",
    "Globular Cluster",
    "Golden Egg",
    "Golden Sun",
    "Gordian Knot",
    "Grace Under Fire",
    "Great Unknown",
    "Green Harbour",
    "Guilded Lily",
    "Gulf Jumper",
    "Gyousei",
    "Hand Over Fist",
    "Hanging Fire",
    "Hangxing",
    "Hanseatic",
    "Hesperides",
    "High Cotton",
    "Hikarimono",
    "Hippogriff",
    "Hinotama",
    "Hopewell",
    "Horn of Plenty",
    "Hoshikuzu",
    "In The Black",
    "Inch of Candle",
    "Infinite Horizon",
    "Iron Spike",
    "Ittousei",
    "Jackanape",
    "Jasmine",
    "Jeanne d'Arc",
    "Ji Banlun",
    "Kajourieki",
    "Kamsin",
    "Katydid",
    "Kelso Convoy",
    "Kian",
    "King Of The Hill",
    "La Bohème",
    "Lady of Aramis",
    "Lapwing",
    "Larkspur",
    "Let's Go",
    "Lionheart",
    "Little Dipper",
    "Longview",
    "LSP Pax Rulin",
    "Mabataki",
    "Magdalena",
    "Magpie",
    "Make Me",
    "Making Hay",
    "Maria Kosmas",
    "Markab",
    "Marvel of Glisten",
    "Merry Dun",
    "Miaplacidus",
    "Mimosa",
    "Mushozoku",
    "Nadir Shah",
    "Nain Rouge",
    "Nashira",
    "New Dawn",
    "New Utopia",
    "No Patron",
    "Noonday Sun",
    "Nuisance",
    "Ocean of Black",
    "On Margin",
    "One Red Cent",
    "Open Sky",
    "Outremer",
    "Pardon My Vilani",
    "Pass The Buck",
    "Passable",
    "Per Chevron Sable",
    "Perroquet",
    "Pioneer Moon",
    "Piper",
    "Pleione",
    "Prairie Fire",
    "Pride of Deneb",
    "Quatre Freres",
    "Queen Mab",
    "Quetzal",
    "Quickstep",
    "Rabelais’ Dodge",
    "Rack and Manger",
    "Rainbow Ceres",
    "Raise the Wind",
    "Rambler",
    "Rara Avis",
    "Red Sun",
    "Red Tincture",
    "Redstone",
    "Reseda",
    "Rest - harrow",
    "Rift Sounder",
    "Rig Marie",
    "Rock Bottom",
    "Samoyed",
    "Sapphire",
    "Savoyard",
    "Second of Arc",
    "Seginus",
    "Seiya",
    "Shake A Leg",
    "Shaula",
    "Sheratan",
    "Silver Cloud",
    "Skylark",
    "So Sue Me",
    "Solitaire",
    "Someday",
    "Spacebourne Pride",
    "Sparrowhawk",
    "Spinward Pride",
    "Sprig of Broom",
    "Stella Polare",
    "Stem To Stern",
    "Sternmetal Eight",
    "Superior",
    "Tarazed",
    "Tejat Prior",
    "Thousand Credit Ante",
    "Three Squares",
    "Tigridie",
    "Time To Space",
    "Tintagel",
    "Tokeiza",
    "Towers Cluster",
    "Tradegood",
    "Trailing Venture",
    "Trin Stardust",
    "Tukera Princess",
    "Ulysses",
    "Upset Price",
    "Urania",
    "Ursa",
    "Various",
    "Venturous",
    "Vesta of Extolay",
    "Vikingur",
    "Virago",
    "Wade’s Boat",
    "Wages of Sin",
    "Waldemar’s Way",
    "Way Away",
    "Weigh Anchor",
    "Weissnichtwo",
    "Westward Ho",
    "Windfall",
    "Winter Wren",
    "World Island",
    "Xebec",
    "Xingshi",
    "Yellowhammer",
    "Yue Laou",
    "Young Queen",
    "Yseult",
    "Zenith",
    "Zeuxis",
    "Zincali",
    "Zwarte Zee",
    "Active",
    "Aegis",
    "Aeneas",
    "Agenor",
    "Ajax",
    "Amalfi",
    "Amazon",
    "Ambuscade",
    "Anhur",
    "Archon",
    "Astabis",
    "Audacious",
    "Bellatrix",
    "Bellerophon",
    "Black Prince",
    "Bogatyr",
    "Brahmastra",
    "Brenhin",
    "Bulwark",
    "Caesar",
    "Centurion",
    "Challenger",
    "Charlemagne",
    "Cheyenne",
    "Conqueror",
    "Conquest",
    "Diomedes",
    "Epeus",
    "Eris",
    "Fear Me",
    "For Glory",
    "Formidable",
    "Forte",
    "Forward",
    "Hazard",
    "Heimdall",
    "Hermes",
    "Hinchinbrooke",
    "Hippolyta",
    "Hussar",
    "Illustrious",
    "Imperator",
    "Juusei",
    "Kederli",
    "Kestrel",
    "Khedive",
    "Kintaro",
    "Lesath",
    "Loaded For Bear",
    "Mahrem",
    "Majestic",
    "Manas",
    "Menelaus",
    "Patroclus",
    "Pentesilea",
    "Qiangquan",
    "Rabican",
    "Rasalas",
    "Razzia",
    "Renown",
    "Resistance",
    "Revenge",
    "Rodomont",
    "Rubicon",
    "Saiph",
    "Sarpedon",
    "Sargas",
    "Sentinel",
    "Steadfast",
    "Sultan",
    "Svalin",
    "Swift",
    "Tenacious",
    "Thunderer",
    "Valiant",
    "Valorous",
    "Vendetta",
    "Victorious",
    "Voivode",
    "War Lord",
    "Warhawk",
    "Xanthos",
    "Yeth Hound",
    "Zulfagar",
    "Almansur",
    "Alcmaeon",
    "Anaxagoras",
    "Ansing Explorer",
    "Aristarchus",
    "Barnard",
    "Bonestell",
    "Bougainwille",
    "Bowditch",
    "Cabeza de Vaca",
    "Cape Bojador",
    "Cassini",
    "Cayley",
    "Columba",
    "Cousteau",
    "Cuvier",
    "De L’Isle",
    "Dicuil",
    "Eratosthenes",
    "Fabricius",
    "Flammarion",
    "Flamsteed",
    "Fresnel",
    "Gassendi",
    "Gemma Frisius",
    "Gnosis",
    "Gunter Chain",
    "Haeckel",
    "Heaviside",
    "Henry Draper",
    "Hogenburg",
    "Ibn Batuta",
    "Jan Jansson",
    "Kim Chong-Ho",
    "La Condamine",
    "Mungo Park",
    "Ortelius",
    "Piri Reis",
    "Ptolemy",
    "Sagacity",
    "Saxton",
    "Sextant",
    "Theodolite",
    "Tanxianzhe",
    "Van den Keere",
    "Void Ranger",
    "Von Humboldt",
    "Willem Blaeu",
    "Wye Level",
    "Zhu Xi",
    "Yachts",
    "Aia Sophia",
    "Alladin’s Cave",
    "Amalthea",
    "Andvaranaut",
    "Conversation Piece",
    "Crystal Spheres",
    "Crown Jewel",
    "Ebisu",
    "Golden Promise",
    "Helve and Hatchet",
    "Idle Lake",
    "Inamorata",
    "Jubilee",
    "Kohinoor",
    "Labarum",
        };
    }
}
