using System.Collections.Generic;


public static class EngLocalization
{
    public static Dictionary<string, string> _locals = new Dictionary<string, string>()
    {
        {"StartInfo", "You are in the remote sector of the galaxy on the very edge of inhabited space.\n" +
                  "As a result of special operations, you had to steal the command ship and the energy\n" +
                  " element on it. Now you have to find the rest of the elements to open the galaxy gates," +
                  "\n and deliver the data to your command"},
        {"Yes", "Yes"},
        {"No", "No"},
        {"Ok", "Ok"},
        {"Reflected", "Effect reflected"},
        {"CriticalDamage", "Critical damages. If damages more than {0} ship destroyed"},
        {"Event", "Event"},
        {"RechargeSheildSpell", "Recharge shield on {0}%"},
        {"ArmorField", "Armor:{0}/{1}"},
        {"UnstableCore0", "Some of your ships can get damage cause your core is unstable.\n\n Find repair services to stabilize your core.\n\n If core stability level become less than -10 your fleet will be destroyed."},
        {"MapExit", "Do you want to exit to main menu?\nProgress will be saved and you can resume later."},
        {"CantByLevel", "Can't use this item cause ship level is too low"},
        {"ReqireLevelFeild", "Require pilot level:{0}"},
        {"CanCauseNoLevel", "Can't upgrade weapon cause pilot don't have enough level.\nPilot level:{0}. Target Level{1}"},
        {"RoundWaveStrike", "Damage all ships near by [{2}/{3}].\n[Cost:{0}/{1}]"},
        {"And", "and"},
        {"Shop", "Shop"},
        {"BaseCenter", "Headquarters"},
        {"BaseEnter", "Military base"},
        {"SectorDungeon", "Military base"},
        {"SupportModul", "Support module. Affect on weapons."},
        {"ActionModul", "Action module"},
        {"CataclysmProcess", "{0} cells destroyed"},
        {"RemainCataclysm", "Days remain:{0}"},
        {"VeryEasy", "Very easy"},
        {"Easy", "Easy"},
        {"Normal", "Normal"},
        {"Hard", "Hard"},
        {"Imposilbe", "Impossible"},
        {"Radius", "Radius"},
        {"Sector", "Sector"},
        {"Reload", "Reload"},
        {"WeaponShieldPerHit", "Shield stealer"},
        {"ShootPerTime", "Bullet count"},

        {"cantUpgrade", "Can't upgrade"},
        {"UpgParams", "Dou you want upgrade {0}?\n Cost {1} credits."},
        {"CoreSector", "Target sector"},
        {"NotCoreSector", "Simple sector"},
        {"StatisticDifficulty", "Difficulty:{0}%."},
        {"StatisticConfig", "Army:{0}."},
        {"StatisticMapSize", "Map size:{0}."},
        {"StatisticFinalArmyPower", "Final power:{0}."},
        {"StatisticRecievedOpendPoints", "Received points:{0}."},
        {"StatisticDate", "{0}"},
        {"Fight", "Fight"},
        {"StatisticNoResult", "No results"},
        {"StatisticNoLastResult", "Wait for game..."},
        {"StatisticLastResult", "Last result:"},
        {"Sacrifice", "Sacrifice ship {0} the {1} of {2}"},

        {"MaxArmyCount", "Fleet count:{0}/{1}"},
        {"EndGameDays", "Days:{0}"},
        {"BattleWinsStat", "Wins:{0}"},
        {"OpenWeaponsEndGame","New weapons for start open {0} and {1}"},
        {"OpenConfigEndGame", "New fleet type available to play: {0}"},
        {"FrontShieldActivate", "Mega-shield activated"},
        {"Crit", "Crit {0}!"},
        {"WinEnd", "All fine now you are free and everything will be fine. Maybe..."},
        {"LoseEnd", "Your fleet destroyed."},
        {"RepairDroneSpell", "Launch repair drone. When ship comes near drone starts healing it. Heal {1}% of hull points."},

        {"Shield Locker", "Shield Locker"},
        {"Auto shield", "Auto shield"},
        {"Shield regeneration", "Shield regeneration"},
        {"Repair drone", "Repair drone"},
        {"Rocked catcher", "Rocked catcher"},
        {"Deflector", "Deflector"},
        {"Side strike", "Side strike"},
        {"Engine locker", "Engine locker"},
        {"EMI mine", "EMI mine"},
        {"Power mine", "Power mine"},
        {"Fire mine", "Fire mine"},
        {"Front shield", "Mega-shield"},
        {"Body armor", "Hull armor"},
        {"Teleportation", "Teleportation"},
        {"Laser power", "Laser power"},
        {"Rockets power", "Rockets power"},
        {"Bomb power", "Bomb power"},
        {"EMI power", "EMI power"},
        {"Impulse power", "Impulse power"},
        {"Speed", "Ship Speed"},
        {"Turn Speed", "Turn Speed"},
        {"Bullet speed", "Bullet speed"},
        {"Spray fire", "Spray fire"},
        {"Longer dist", "Longer dist"},
        {"Pusher", "Pusher"},
        {"Burner", "Burner"},
        {"Stopper", "Stopper"},
        {"Locker", "Locker"},
        {"Critical", "Critical"},
        {"AOE", "AOE"},
        {"Wider", "Wider"},
        {"Close strike", "Close strike"},
        {"Chain strike", "Multi target"},
        {"Penetrating shot", "Penetrating shot"},
        {"Powerful recoil", "Powerful recoil"},
        {"Shield stealer", "Shield stealer"},
        {"More bullets", "More bullets"},
        {"Power shot", "Power shot"},
        {"Fire wave", "Fire wave"},
        {"Protector", "Protector"},
        {"Beam upgrade", "Beam upgrade"},
        {"Heavy weapons", "Heavy weapons"},
        {"Maximum shield", "Maximum shield"},
        {"scout", "Scouts"},
        {"repair", "Repair services"},
        {"chargesCount", "Charges Count"},
        {"chargesSpeed", "Charges Speed"},
        {"engineParameter", "Engine"},

        {"Preparing", "Preparing"},
        {"Return", "Return"},
        {"Evade enemy", "Evade enemy"},
        {"RepairAction", "Repair"},
        {"Wait", "Wait"},
        {"Hiding", "Hiding"},
        {"FlangAttack", "Flank Attack"},

        {"MainShipBlinkDesc", "Teleports your main ship to selected target"},
        {"MainShipBlinkName", "Jumper"},
        {"hookShot", "Magnet strike"},
        {"wantUpgrade", "You want to upgrade {0}? Credits:{1}"},
        {"wantUpgradeLong", "You want to upgrade {0}? Credits:{1}. Microchips:{2}"},


        {"engineLock", "Engine locker"},
        {"lineShot", "Line shot"},
        {"throwAround", "Power explosion"},
        {"vacuum", "Vacuum"},
        {"mineField", "Mine Field"},
        {"distShot", "Power shot"},
        {"artilleryPeriod", "Artillery"},
        {"repairDrones", "Repair drones"},
        {"rechargeShield", "Recharge shield"},
        {"roundWave", "Round damage"},
        {"machineGun", "Machine gun"},

        {"WANT_UPGRADE_WEAPON","Do you want to upgrade {0}?" },
        {"WeaponMaxLevel", "Weapon have max level"},
        {"Processing", "Processing..."},
        {"Win", "Win!"},
        {"Lose", "Lose"},
        {"RunAwayComplete","Run away complete" },
        {"Type", "Type"},

        {"Regen", "Regeneration"},
        {"DamageBody", "Damage hull"},
        {"DamageShield", "Damage shield"},
        {"HealBody", "Repair hull"},
        {"HealShield", "Recharge shield"},
        {"ChargesCount", "Charges count {0}"},
        {"ChargesDelay", "Charges delay {0}"},
        {"Scouted", "Scouted"},
        {"Gate", "Gate"},
        {"Home", "Home"},
        {"Complete", "Complete {0}"},
        {"Target", "Target {0}"},
        {"Delay", "Delay"},

        {"trick_turn", "Fast turn to attack enemy"},
        {"trick_twist", "Ship moves to side to avoid attack and do strike from flank"},
        {"trick_loop", "Loop to avoid attack and confuse enemy"},
        {"trick_frontStrike", "Ram strike"}, 

        {"trick_name_turn", "Drift"},
        {"trick_name_twist", "Twist"},
        {"trick_name_loop", "Loop"},
        {"trick_name_frontStrike", "Ram"},

        {"healBodySupport",  "Repair drone"},
        {"healShieldSupport",  "Energy drone"},
        {"shildDamage",  "Shield locker"},
        {"shieldLocker",  "Lock shield of target enemy."},
        {"autoShieldRepair", "Repair shield when it's down."},
        {"shieldRegen", "Faster shield restoring."},
        {"autoRepair", "Add HP when ship have low hp."},
        {"antiPhysical", "Destroy physical bullets in close radius."},
        {"antiEnergy","Destroy energy bullets in close radius" },
        {"closeStrike","When enemy close, launch special bullet to hit them." },
        {"engineLocker","Destroy engine of target enemy." },
        {"systemMines", "Put system mines, crashing enemies engines"},
        {"damageMines","Put damage mines to hit enemies" },
        {"frontShield","For a short period all bullets can't do damage." },
        {"armor", "Decrease damage on ships hull"},
        {"fireMines", "Put damage mines, witch can fire enemies."},
        {"blink", "Ship can teleport to better locations."},
        {"laserUpgrade", "Increase power of all laser weapons for +1/+1 per level."},
        {"rocketUpgrade","Increase power of all rocket weapons for +1/+1 per level." },
        {"EMIUpgrade", "Increase power of all EMI weapons for +1/+1 per level."},
        {"impulseUpgrade","Increase power of all impulse weapons for +1/+1 per level." },
        {"bombUpgrade","Increase power of all bomb weapons for +1/+1 per level." },

        {"WeaponSpeed", "Increase speed of all bullets."},
        {"ArmyAdditionalPower", "Every turn enemies fleets will be upgraded."},

        {"Back", "Back"},
        {"Battle", "Battle"},

        {"questKills", "{0} kills"},
        {"Fleet", "Fleet"},
        {"Loading", "Loading"},
        {"RusLang", "Russian"},
        {"EngLang", "English"},
        {"EspLang", "Spanish"},
        {"ReloadToLoc", "Restart game to update localization"},
        {"SettingsWindow", "Settings Window"},
        {"RechargeButton","Recharge Shield.\nCost[{0}/{1}]" },
        {"BuffButton", "Increase parameters of ship.\n[Cost:{0}/{1}]"},
        {"PowerWeaponButton", "Increase next shoot damage of ship.\n[Cost:{0}/{1}]"},
        {"CellScouted", "Coordinates Scouted [{0},{1}]"},
        {"PriorityTarget", "Priority Target"},
        {"BaitPriorityTarget","Bait Target"},
        {"engineCrash","Engine crashed for {0:0} sec" },
        {"shieldCrash","Shield turn off for {0:0} sec" },
        {"fireCrash", "Fire starts! {0:0} sec"},
        {"winAgainst", "Wins against {0}"},
        {"damageByQuest", "Damage by {0}"},
        {"killLight","Light ships kills" },
        {"killMed","Medium ships kills" },
        {"killHeavy", "Heavy ships kills"},
        {"mainShipKills", "Kills by commander"},
        {"upgradeWeapons", "Weapons levels upgrades"},
        {"sellModuls", "Sell modules"},
        {"PriorityTargetDesc", "All your ship will try to attack selected ship."},
        {"BaitPriorityTargetDesc","All enemies ships will try to attack selected ship" },
        {"SpellModulChargers", "Charges require: {0} with delay {1} sec."},
        {"ArtillerySpell","Starts fire at selected zone. Total bullets {0}. Damage of each bullet:{2}/{1}." },
        {"EnerguLockSpell","Destroy engines at all enemies ships in radius {1} for {0} sec." },
        {"LineSHotSpell","Triple shot by selected direction. Base damage: {0}/{1}. And starts fire for {2} sec. Total fire damage:{3}" },
        {"MinesSpell","Set {0} mines for {1} sec to selected location. Each mine damage {2}/{3}" },
        {"ShieldOffSpell","Disable shields of ships in radius for {0} sec. And damages shield for {1}." },
        {"TrowAroundSpell", "Create a shockwave witch throw around all ships in radius with power {0}. And shield damage {1}."},
        {"DescHookShotSpell", "Push all target to your commander ship and damage engines for a {0} sec"},
        {"KillUIPilotMini","Kills:{0}" },
        {"KillUIPilot", "Kills:{0}/{1}"},
        {"Remain","Remain" },
        {"EngineDest", "Engine destroyed"},
        {"ShieldDest","Shield destroyed" },
        {"FireDest", "Fire on board"},
        {"DoWantRetire","Do you want run away?" },
        {"NoSafeGame","No save game" },
        {"MaxLevel", "Max"},
        {"DamageTimeEffectRepair", "Remove all negative effects"},
        {"AddMicrochips", "Add microchips {0}"},
        {"Microchips", "Microchips"},

        {"WeaponAOE", "Affects for all ships in radius. {0}. Decrease damage by {1}%."},
        {"WeaponSector",  "Increase aim sector by {0}% per level"},
        {"WeaponPowerShot", "Increase reload time by {0}%. Increase damage by {1}%."},
        {"WeaponPowerShotSupport", "Increase reload time by {0}%. Increase restore power by {1}%."},
        {"WeaponShootPerTime", "Add 1 bullet per shoot. Decrease weapons power by {0}% "},
        {"WeaponLessDist", "Decrease aim radius by {0}%. Increase damage by {1}%."},
        {"WeaponLessDistSupport", "Decrease aim radius by {0}%. Increase restore power by {1}%."},
        {"WeaponPushSupport", "All external powers stops affect on ship"},
        {"ShipTurnSpeed", "Increase ship turn speed by {0}%"},
        {"ShipSpeed", "Increase ship max speed by {0}%"},
        {"ShieldDouble", "Increase shield power by {0}% . Decrease ship body points by {1}%"},
        {"ShipDecreaseSpeed", "Increase weapons power by {0}%.  Decrease ship max speed by {1}%"},
        {"WeaponIncreaseDamage", "Increase damage by {0}% for all {1} weapons."},
        {"WeaponNoBulletDeath", "Bullet don't destroy when hit target. Increase reload time by {0}%."},
        {"WeaponShieldPerHitDesc", "Decrease weapons power by {0}%. Restore {1} of shield per hit."},
        {"IgnoreShieldLevel1", "Ignore shield. Decrease damage by {0}%."},
        {"Ignore shield", "Ignore shield."},
        {"WeaponSelfDamage", "Add a +{0}/+{0} Damage. But damages own ship when strikes on {1}/{1}"},
        {"WeaponSelfDamageSupport", "Add a +{0}/+{0} to restore points. But damages own ship when strikes on {1}/{1}"},
        {"WeaponPush","Push target when hit"},
        {"WeaponCrit","Add a {0}% chance to get a {1} additional hull damage."},
        {"WeaponCritSupport","С {0}% chance to repair {1} hull points."},
        {"DamageTimeEffect","with a {0}% chance for {1:0} sec, when hit."},
        {"DamageTimeEffectEngine","Turn off engine {0}"},
        {"DamageTimeEffectShield","Off all shield {0}"},
        {"DamageTimeEffectFire","Start fire {0}"},
        {"ResistDamages","Reflects all negative effects"},

        {"wantSell","Do you want sell item for {0}?"},
        {"wantBuyItem","Do you want buy item for {0}?"},

        {"valuable goods","valuable goods"},
        {"invaluable goods","invaluable goods"},



        {"DamageInfoUI", "Damage: {0}/{1}" },
        {"KillsInfoUI", "Kills: {0}"},
        {"ReputationChanges", "{2} reputation change {0} => {1}."},
        {"ReputationData", "{0} reputation: {1}"},

        {"HirePilot","You hired a new pilot. Type:{0}  Config:{1}"},

        {"Destroyed", "Destroyed" },
        {"Completed", "Completed"},
        {"StartNewGameFieldSize", "Sector size"},
        {"StartNewGameCoresCount","Keys count" },
        {"StartNewGameSectorsCount", "Sectors count"},

        {"All to me", "To fleet"},
        {"Equal", "Equal"},
        {"All to ship", "To battleships"},
        {"To Map", "To Map"},



        {"EngineLockNameA1", "Radius"},
        {"EngineLockNameB2", "Low time"},
        {"EngineLockDescA1", "Increase radius of affection on {0}"},
        {"EngineLockDescB2", "Decrease batteries reload time on {0} sec"},

        {"ArtilleryNameA1", "Bullets"},
        {"ArtilleryNameB2", "Fast shoots"},
        {"ArtilleryDescA1", "Increase count of bullets on {0}"},
        {"ArtilleryDescB2", "Decrease period between bullets on {0} sec"},

        {"DistShotNameA1", "Engine lock"},
        {"DistShotNameB2", "AOE"},
        {"DistShotDescA1", "Damage engine when hit. Engine stops for {0} sec"},
        {"DistShotDescB2", "Increase area of damage on {0}"},

        {"LineShotNameA1", "Penetraiting"},
        {"LineShotNameB2", "Termit"},
        {"LineShotDescA1", "No bullet death when hit"},
        {"LineShotDescB2", "Increase fire power on {0}"},

        {"MachineGunNameA1", "Multishot"},
        {"MachineGunNameB2", "More bullets"},
        {"MachineGunDescA1", "Shoots to all nearby targets. Bullets count: {0} for each target"},
        {"MachineGunDescB2", "More bullets in line. Bullets count: {0}"},

        {"MinesSpellNameA1", "Fire"},
        {"MinesSpellNameB2", "Engine damage"},
        {"MinesSpellDescA1", "Add fire damage for {0} sec"},
        {"MinesSpellDescB2", "Destroy engines for {0} sec"},

        {"RechargeSheildNameA1", "AOE"},
        {"RechargeSheildNameB2", "Resists"},
        {"RechargeSheildDescA1", "Effects to all nearby ships at {0} radius"},
        {"RechargeSheildDescB2", "Add for {0} sec resist to ship"},

        {"RepairDroneNameA1", "Shield"},
        {"RepairDroneNameB2", "Buff"},
        {"RepairDroneDescA1", "Repair shield for {0} %"},
        {"RepairDroneDescB2", "Add for {0} speed buff"},

        {"ShieldOffNameA1", "Battery"},
        {"ShieldOffNameB2", "Fire"},
        {"ShieldOffDescA1", "Decrease batteries count"},
        {"ShieldOffDescB2", "Add fire damage for {0} sec"},

        {"TrowAroundNameA1", "Engines"},
        {"TrowAroundNameB2", "Drop load"},
        {"TrowAroundDescA1", "Destroy engines when hit for {0} sec"},
        {"TrowAroundDescB2", "Unload all weapons of target"},

        {"VacuumNameA1", "Radius"},
        {"VacuumNameB2", "Battery"},
        {"VacuumDescA1", "Increase radius of effect on {0}"},
        {"VacuumDescB2", "Decrease batteries reload time for {0} sec"},

        {"HookShotNameA1", "Radius"},
        {"HookShotNameB2", "Battery"},
        {"HookShotDescA1", "Increase radius of effect on {0}"},
        {"HookShotDescB2", "Decrease batteries reload time for {0} sec"},



        {"RaidersProCons", "Pros: Good speed, many slots for modules.\nCons: Few weapon slots. No shield regeneration."},
        {"FederationProCons", "Pros: Many weapon slots. Shield regeneration.\nCons: Low speed."},
        {"MercenaryProCons", "Pros: Balanced.\nCons: Balanced."},
        {"OcronsProCons", "Pros: Perfect hull health. Many slots for modules.\nCons: No shied. No shield regeneration."},
        {"KriosProCons", "Pros: Good shield. Perfect shield regeneration.\nCons: Low hull health."},

        {"WeaponsStart","On start your ships will have one of {0} or {1} complect."},

        {"Paramscout", "Scout can provide you information about enemies army.\nAnd sometimes can try steal something."},
        {"Paramrepair", "Between battles you will need to repair your fleet.\nThis one will help you."},
        {"ParamchargesCount", "Increase main ship charges count."},
        {"ParamchargesSpeed","Increase main ship charges regeneration speed."},
        {"ParamEngine","Upgrade engine. More speed and faster recharge of blink."},

        {"asteroidsEvent", "Asteroid vortex"},
        {"shieldsOffEvent", "EMP surge"},

        {"ShipsRepaired", "Ships Repaired"},
        {"Raiders", "Raiders"},
        {"Federation", "Federation"},
        {"Mercenary", "Mercenary"},
        {"Ocrons", "Ocrons"},
        {"Krios", "Krios"},
        {"Droids", "Droids"},
        {"Light", "Light"},
        {"Medium", "Medium"},
        {"Heavy", "Heavy"},
        {"Base", "Base"},
        {"ESideAttackStraight", "Attack as usual"},
        {"ESideAttackFlangs", "Attack from flags"},
        {"ESideAttackBaseDefence", "Attack only near commander ship"},
        {"BaseDefenceYes", "Defend the base"},
        {"BaseDefenceNo", "No"},
        {"EGlobalTacticsFight", "Fight"},
        {"EGlobalTacticsGoSafe", "Stay in safe"},
        {"ECommanderPriority1Base","Attack commander ship" },
        {"ECommanderPriority1Fast","Choose to attack fastest ship"  },
        {"ECommanderPriority1Slow","Choose to attack slowest ship"  },
        {"ECommanderPriority1MinShield","Choose to attack ship with minimum shield" },
        {"ECommanderPriority1MinHealth","Choose to attack ship with minimum hull"  },
        {"ECommanderPriority1MaxShield","Choose to attack ship with max shield"  },
        {"ECommanderPriority1MaxHealth","Choose to attack ship with max hull"  },
        {"ECommanderPriority1Any", "Any ships to attack"},
        {"ECommanderPriority1Light","Light ships will be a priority" },
        {"ECommanderPriority1Mid","Medium ships will be a priority" },
        {"ECommanderPriority1Heavy", "Heavy ships will be a priority"},
        {"QuestReward", "Choose one reward"},
        {"Reputation", "Reputation"},
        {"Inventory", "Inventory"},
        {"ReputationElement", "Enemies:{0}"},
        {"Trickturn", "Quick turn"},
        {"Trickloop", "Loop"},
        {"Tricktwist", "Twist"},
        {"Settings", "Settings"},
        {"Private", "Private"},
        {"Lieutenant", "Lieutenant"},
        {"Achievements", "Achievements"},
        {"Captain", "Captain"},
        {"Major", "Major"},
        {"OpenNew", "Unlock"},
        {"FinalSector", "Galaxy gates"},
        {"Attack", "Attack"},
        {"AttackHalfLoop", "Trick attack"},
        {"Evade", "Evade"},
        {"Level", "Level"},
        {"Start game", "Start game"},
        {"Randomize", "Randomize"},
        {"Resume", "Resume"},
        {"NotEnoughtBattries", "Battries are not ready!"},
        {"reloadBoost", "Trick reload time:{0}"},
        {"PointsToOpen", "Points to unlock start options:"},
        {"SpellMaxLevel", "Max level reached: {0}"},
        {"WantChangeLang", "Restart game to update localization."},
        {"NoMouseMove", "Camera have no move by mouse."},


        {"descWinner", "Win at 1 battle"},
        {"descCaptain", "Win at 10 battle"},
        {"descMayor", "Win at 100 battle"},
        {"descTeam five", "Hire all faction at one army"},
        {"descFighter", "Destroy 100 enemy ships"},
        {"descDestroyer", "Destroy 1000 enemy ships"},
        {"descAnnihilator", "Destroy 10000 enemy ships"},
        {"descMerWin", "Win as mercenaries"},
        {"descFedWin", "Win as federation"},
        {"descKriWin", "Win as krios"},
        {"descOcrWin", "Win as ocrons"},
        {"descRdrWin", "Win as kingdom"},

        {"nameWinner", "Winner"},
        {"nameCaptain", "Captain"},
        {"nameMayor", "Mayor"},
        {"nameTeam five", "Team five"},
        {"nameFighter", "Fighter"},
        {"nameDestroyer", "Destroyer"},
        {"nameAnnihilator", "Annihilator"},
        {"nameMerWin", "Ringleader"},
        {"nameFedWin", "Chancellor"},
        {"nameKriWin", "Experimentalist"},
        {"nameOcrWin", "Fanatic"},
        {"nameRdrWin", "King"},

        {"MercGlobal", "Mercenary hideout"},
        {"NotEnoughtMoney", "Not enough credits"},
        {"NotEnoughtMoneyLong", "Not enought credits {0}."},
        {"NotEnoughtUpgrades", "Not enought microchips {0}."},
        {"leave", "Leave"},
        {"HireMerc", "Hire {1} the {0}. Level:{2}. Cost:{3} credits."},
        {"Take", "Take"},
        {"BrokenItem", "Your item broken {0}"},
        {"StabilizaInfo", "Stability level:{0}"},
        {"MainElements", "Energy blocks"},
        {"Credits", "Credits"},

        {"Health", "Health"},
        {"Shield", "Shield"},
        {"TurnSpeed", "Turn"},
        {"Unknown", "Unknown"},
        {"NewGame", "New Game"},
        {"Continue", "Continue"},
        {"Exit", "Exit"},
        {"ScoutsFind", "Scouts find something!"},
        {"Start point", "Start point"},

        {"ReinforcmentsCallNo", "No reinforcements"},
        {"ReinforcmentsCallConfig", "Call reinforcements:{0}"},
        {"ReinforcmentsCalled", "Reinforcements unavailable"},
        {"Retreat", "Retreat"},
        {"Upgrade", "Upgrade"},

        {"Laser", "Laser"},
        {"Rocket", "Rocket"},
        {"Impulse", "Impulse"},
        {"Swarm", "Swarm"},
        {"EMI", "EMI"},
        {"Beam", "Beam"},
        {"MovingArmy", "Special forces of {1}\nStatus:{2}. Power:{3}"},
        {"MovingArmyBorn", "Special forces of {0} appear. Coordinates:{1}"},
        {"AdditionalPower", "Enemies upgrades"},

        {"AddCredits", "Add credits:{0}"},
        {"Comparable", "Comparable"},
        {"Risky", "Risky"},
        {"Easily", "Easily"},
        {"confirmDismiss", "You really want to dismiss ship {0}?"},
        {"MovingArmyName", "SpecOps {0}"},
        {"RelocateTo", "Relocate to:{0}"},

        {"Demo", "This is demo version. We are not ready to show more. Maximum visited sectors:{0}. Maximum turns:{1}"},

        {"RecievePoints", "You will get points to unlock after winning. Amount depends on difficulty. Also you can get some points winning battles."},
        {"AA_FXAA", "Anti aliasing"},
        {"Sound", "Sound"},
        {"Turret", "Turret"},
        {"battlefield", "Battlefield"},
        {"Amry","Amry"},
        {"Trader","Trader"},
        {"RepairCompete","Repair Compete"},
        {"RepairStation","Repair Station"},
        {"BrokenNavigation", "Broken navigation"},
        {"modifBaseStart", "This is modification base. You can try to modificate something."},
        {"modifCellName", "Modification station"},

        {"scout_shipType", "No ship type info"},
        {"scout_weapons", "No weapons info"},
        {"scout_level", "No level info"},
        {"scout_moduls", "No modules info"},
        {"scout_spells", "No big guns info"},
        {"targteFar", "Target is too far"},

        {"Battle reward", "Battle reward:"},
        {"Fleet money", "Fleet money:"},

        {"armyCount", "Army count is {0}"},
        {"armyCountBetween", "Army count between {0} and {1}"},
        {"armyWeaponsContains","Weapons types contains {0}"},
        {"armyHaveMotherShip","Have commander ship"},
        {"armyJustFleet","Just fleet"},
        {"armyWeaponsCount","Weapons count:{0}. Moduls count:{1}"},
        {"armyUsingWeapons","Using weapons:{0}"},

        {"DescVacuumSpell", "Creates a vacuum over the target area that sucks in enemy units. Power:{0}. Shield damage:{1}"},
        {"ChainModulDesc", "Shoot to all targets in radius. Decrease damage on {0}%"},
        {"FireNearModulDesc", "Can fire nearby enemies for {0} sec when shoot."},
        {"SprayModulDesc", "Shoot with {0} bullets instead on one. Increase reload time by {1}%."},
        {"WeaponSpeedModulDesc", "Increase bullet speed by {0}% per level"},
        {"DescWeaponDistModul", "Increase aim radius by {0}% per level"},
        {"WeaponEngine", "Lock enemy engine for some period"},

        {"MachineGunSpellDesc", "Series  of {0} fast bullets. Damage: {1}/{2}"},
        {"DistShotSpell", "Single bullet. Only hull damage {0}."},
        {"DistShotSpellSpecial", "Single bullet.  Only hull damage {0}. If target have no shield destroy engine for {1} sec."},

        {"rep_adv_friend", "You are friends. Maybe they can help you."},
        {"rep_adv_neutral", "Fleets will fight, but you can trade with them."},
        {"rep_adv_negative", "You still can trade with them, but prices will be bad"},
        {"rep_adv_enemy", "No trade. Only fight! Special force will try to find and kill you."},
        {"rep_friend", "Friends"},
        {"rep_neutral", "Neutral"},
        {"rep_negative", "Negative"},
        {"rep_enemy", "Enemy"},
        {"DemoStart", "This is not final version on game, something can change later."},
        {"DemoStart2", "You will have only 25 turns. And some mechanics will be blocked."},

        {"dialog_Ok", "Ok"},
        {"dialog_MovingArmyStart", "You have been occupied by special force. You have no chanse to run."},

        {"dialog_MovingArmyFight", "Fight"},
        {"dialog_MovingArmyWin", "Special forces destroyed."},
        {"dialog_MovingArmyGerReward", "Get all valuable items."},

        {"dialog_shopEnemy", "You see shop. Nobody wants to trade with you." },
        {"dialog_shopTrade", "You see shop. Maybe you want buy something?" },
        {"dialog_repairEnemy", "This is repair station. They won't help you." },
        {"dialog_repairStart", "This is repair station. We can repair our fleet here." },
        {"dialog_fixCrit", "Fix all critical damages. Cost{0}" },
        {"dialog_repairCritFixed", "Critical damages fixed" },
        {"dialog_repairAll", "Yes repair all.{0} credits" },
        {"dialog_repairNotEnough", "I don't have enough credits" },


        //DILOGS ASTEROIDS
        {"dialog_asteroid_nothingComplete", "Nothing happens. You successfully complete way" },
        {"dialog_asteroid_nothingCompleteRepair","Nothing happens, but some ships need to be repaired. You successfully complete way" },
        {"dialog_asteroid_start", "Big asteroid field. You need somehow get to other side." },
        {"dialog_asteroid_fireAll","Fire from all weapons" },
        {"dialog_asteroid_slow","Slow go through field." },
        {"dialog_asteroid_brokenShip","You see {0} broken ship." },
        {"dialog_asteroid_brokenShipRepair", "Try to repair it [Repair:{0}]."},
        {"dialog_asteroid_brokenShipdecompile","Try to decompile it for money." },
        {"dialog_repairResultFull", "This ship can't be fully repaired but now you can use some parts. {0}"},
        {"dialog_repairResultCant", "This ship can't be fully repaired but you have no place for items."},
        {"dialog_asteroid_weaponsFire","Explosive weapons easily destroy enough asteroid. Now you have a way." },
        {"dialog_asteroid_weaponsFail", "Your weapons are have not much power to create a way throug. And some of your ships get damage"},
        {"dialog_asteroid_haveWay", "Finally you have a way! But some of your ships get damage"},
              
        //DILOGS BATTLEFIELD
        {"dialog_battlefield_start","You see some {0} ships stands against each other." },
        {"dialog_battlefield_provocate", "Hide and provocate them"},
        {"dialog_battlefield_reconcile","Try to reconcile all sides" },
        {"dialog_battlefield_thanks","Thanks!" },
        {"dialog_battlefield_diplomacyWin", "Your diplomacy skills are perfect. They will not fight and send you a gift for helping. Reputation add {Library.REPUTATION_RELEASE_PEACEFULL_ADD}."},
        {"dialog_battlefield_run","Run!" },
        {"dialog_battlefield_shoot","Shoot near!" },
        {"dialog_battlefield_diplomacyFail","Your diplomacy skills is awful. But now they want to kill you instead of each other." },
        {"dialog_battlefield_shit", "Shit."},
        {"dialog_battlefield_theyAttack","This is not your day. They attacking you!" },
        {"dialog_battlefield_ufff", "Ufff... Great."},
        {"dialog_battlefield_stopAttack","They stop trying attack anybody and run away. Maybe this is not bad. At least you save some lives" },
        {"dialog_battlefield_youRun", "You run away"},
        {"dialog_battlefield_artillery","Catch moment and fire with artillery" },
        {"dialog_battlefield_wait","Wait" },
        {"dialog_battlefield_theyBattle","They starts battle." },
        {"dialog_battlefield_killEachOther", "Battle ends. They kill each other. And you find some credits {0}."},
        {"dialog_battlefield_isee", "I see"},
        {"dialog_battlefield_battleHaveWinner", "Battle ends. Win side take trophies and go away. You can do nothing"},
        {"dialog_battlefield_good","Good" },
        {"dialog_battlefield_goodSHot", "Good shoot. You destroy all of them. After battle you find some items"},
        {"dialog_battlefield_fight","Fight" },
        {"dialog_battlefield_killYou","Now they want to destroy you." },

        //DIALOG_BROKEN_NAVIGATION
        {"dialog_navigation_start","You have a distress signal" },
        {"dialog_navigation_closer","Come closer" },
        {"dialog_navigation_trap", "It's a trap!"},
        {"dialog_navigation_fight", "Fight"},
        {"dialog_navigation_askHelp","You see a {0} ship with broken navigation system. He asking for help" },
        {"dialog_navigation_shelter","Send scout to deliver him to closest shelter. [Scouts: {0}]" },
        {"dialog_navigation_repair","Try repair navigation system. [Repair {0}]" },
        {"dialog_navigation_gift", "Your gift: {0}"},
        {"dialog_navigation_noFree", "Not free space for gift"},
        {"dialog_navigation_scouted", "{0} cells on global map scouted."},
        {"dialog_navigation_shelterOk","You successfully find way to shelter. {0}." },
        {"dialog_navigation_repairOk","You successfully repair ship. Reputation add." },
        {"dialog_navigation_tryHire", "Try hire"},
        {"dialog_navigation_takeMoney","Take money" },
        {"dialog_navigation_hired","Ship hired {0}." },
                            
        //DIALOG_CHANGE_ITEM
        {"dialog_changeitem_start","This ship wants to trade with you. {0}" },
        {"dialog_changeitem_tradeData","\nThey want to change your {0} to {1}" },
        {"dialog_changeitem_ok","Ok. Lets change." },
        {"dialog_changeitem_no","No, thanks." },
        {"dialog_changeitem_nothing","You have nothing to trade" },

        {"dialog_armySectorEvent","Sector event:{0}\n" },
        {"dialog_armyFrendly", "This fleet looks friendly.\n {0}"},
        {"dialog_armyBuyOut","Try to buy out. [Cost :{0}]" },
        {"dialog_armyStronger", "You see enemies. They look stronger than you. Shall we fight? \n {0}"},
        {"dialog_armyShallFight","You see enemies. Shall we fight? \n {0}" },
        {"dialog_armyNeutral", "This fleet won't attack you first. \n {0}" },
        {"dialog_armyAskHelp",  "Ask for help. [Reputation:{0}]"},
        {"dialog_armyRun","Runaway" },
        {"dialog_armyRunComplete","Running away complete." },
        {"dialog_armyRunFail", "Fail! Now you must fight."},
        {"dialog_armyBuyoutComplete","Buyout complete. You lose {0} credits." },
        {"dialog_Attack","Attack" },
        {"dialog_sectorClear","Nobody here. maybe you should return here later" },

        {"dialog_coreAttack","Attack." },
        {"dialog_coreTargetProtect","Target is under protection." },
        {"dialog_coreBuy","Buy for {0} credits." },
        {"dialog_coreUseDiplomacy","Use diplomacy." },
        {"dialog_coreSendScouts","Send scouts to steal." },
        {"dialog_coreFleetHave","Some other fleet already have your target. \n {0}" },
        {"dialog_coreFleetHaveFriend","Friendly fleet already find your target. You can try to use diplomacy. Or simply buy it.\n {0}" },
        {"dialog_coreWasPurchase","Element was purchased. {0}/{1}" },
        {"dialog_coreElementYour","Element is yours. {0}/{1}" },
        {"dialog_coreFight","Very bad. Fight." },
        {"dialog_coreFailSteal","Fail. While you were trying to steal an item, reinforcements came to them, and now you can't runaway." },
        {"dialog_corePartYours", "This part is yours now."},
        {"dialog_coreDiplomacyFail", "They don't want to give you this part"},

        {"dialog_hirePay", "Pay"},
        {"dialog_hireAttack", "You won't pay. Instead of it, you will just want to kill them all."},
        {"dialog_hireEnter","Space base inside big asteroid. Have impressive protection. \nEnter not free. Pay {0} to enter" },
        {"dialog_hireSomebody","You can try to hire somebody here." },
        {"dialog_hireMax","You have maximum size of fleet." },
        {"dialog_hireComplete","Hire complete" },

        {"Prisoner","Prisoner"},
        {"dialog_prisonerStart","Criminal try to escapes from the {0} police. But your fleet can catch him"},
        {"dialog_prisonerBuy","Buy stolen item. [Cost:{0}]"},
        {"dialog_prisonerCatch","Catch and return to police."},
        {"dialog_prisonerHire","Hire him"},
        {"dialog_prisonerHide","Hide him from police. [Reputation:{0}]"},
        {"dialog_prisonerHired","Criminal hired. Reputation removed {0}"},
        {"dialog_prisonerYourItem","Your item: {0}"},
        {"dialog_prisonerNoSpace","Not free space for item"},
        {"dialog_prisonerComplete","Complete. {0}"},
        {"dialog_prisonerHideOk","You successfully hide criminals ship. Credits add {0}"},
        {"dialog_prisonerFailFight","Fail! Now you will fight with police."},
        {"dialog_prisonerCatchOk","You successfully catch him. Reputation added"},
        {"dialog_prisonerBuyFail","You don't have enough money. Criminal just fly away"},

        {"ScienceLaboratory","Science laboratory"},
        {"dialog_scLabStart","You are close to {0} science laboratory. But this one is under siege."},
        {"dialog_scLabAttackNow","Attack immediately"},
        {"dialog_scLabContact","Contact with fleet commander"},
        {"dialog_scLabSedScouts","Send scouts to laboratory"},
        {"dialog_scLabFrighten","Try to frighten them."},
        {"dialog_scLabBetterContact","No, better I contact with them."},
        {"dialog_scLabNotRegular","This isn't regular army. We can try to frighten them."},
        {"dialog_scLabGoStation","Go to station."},
        {"dialog_scLabTheyRun","They running away!."},
        {"dialog_scLabFight","Fight"},
        {"dialog_scLabTotalFail","Fail! They just launch rockets to laboratory and now wants to kill you."},
        {"dialog_scLabGiveCredits","Maybe if just give you some credits and you will leave [Credits:{0}]"},
        {"dialog_scLabSimpleThiefs","They look like simple thiefs."},
        {"dialog_scLabTheLeave","They leaving."},
        {"dialog_scLabBadJoke","Bad joke! [Not enough credits]"},
        {"dialog_scLabAllKilled","All scientists were killed."},
        {"dialog_scLabImproveMain","Improve main ship."},
        {"dialog_scLabImproveBattle","Improve battle ships."},
        {"dialog_scLabScientsChoose","Scientists are alive. And they can improve your army"},
        {"dialog_scLabShipUpgraded","{0} upgrade at ship {1} Upgraded."},
        {"dialog_scLabAllMax","All your ships have max level."},
        {"dialog_scParamUpgraded","{0} Upgraded"},
        {"dialog_scLabNotingUpgrade","Nothing to improve."},

        {"dialog_secretStart","A lot of space garbage and other useless thing here. Do you want to investigate?"},
        {"dialog_secretSendScouts","Send scouts"},
        {"dialog_secretHideWait","Hide and wait"},
        {"dialog_secretSendFake","Send fake signal"},
        {"dialog_secretAttack","Attack!"},
        {"dialog_secretConnectWith","Connect with commander."},
        {"dialog_secretScoutResult","Scouts find a huge fleet, waiting for something. [Scouts:{0}]"},
        {"dialog_secretTryPrevent","Try to prevent conflict"},
        {"dialog_secretRun","Run"},
        {"dialog_secretSeeHugeArmy","Suddenly you see a huge army. And they are ready! [Scouts:{0}]"},
        {"dialog_secretHaveCredits","And now you have [credits{0} and {1}]"},
        {"dialog_secretYouRun","You run away. {0} [Scouts:{1}]"},
        {"dialog_secretFight","Fight"},
        {"dialog_secretRunFail","Running away failed! [Scouts:{0}]"},
        {"dialog_secretApplyDeal","Apply deal"},
        {"dialog_secretLeave","Leave"},
        {"dialog_secretTheyMessage","They send you a message with trade options."},
        {"dialog_secretTheyGoKill","Now they going to kill. Diplomacy is not your good side."},
        {"dialog_secretPartGo","Part of fleet going to check signal."},
        {"dialog_secretDoProvocation","Do provocation."},
        {"dialog_secretWait","Wait."},
        {"dialog_secretSecondCome","{0}s army coming."},
        {"dialog_secretSearchPlace","Search place."},
        {"dialog_secretTheyEnd","They complete trade, and ready to jump."},
        {"dialog_secretTake","Take. [Credits:{0}]"},
        {"dialog_secretForgotCredits","Looks like they forgot some credits."},
        {"dialog_secretTakeAll","Take all and run."},
        {"dialog_secretAppearSecond","While trading, appears another fleet."},
        {"dialog_secretFindGoods","After massive battle you find some goods. [Credits:{0}]"},
        {"dialog_secretProvoceFail","Your provocation failed. Now fight."},

        {"dialog_finalStartReady","This is your main goal. You have {0}/{1} parts to open gates.\n You are ready to go in."},
        {"dialog_finalStartNotReady","This is your main goal. You have {0}/{1} parts to open gates.\nNow you should acquire all others.\n Only one way to do it send one of your ships to block energy on gates. \n But you don't have enought ship \n Your are dead."},
        {"dialog_finalProcess","This is your main goal. You have {0}/{1} parts to open gates.\n Now you should acquire all others.\n Only one way to do it send one of your ships to block energy on gates. "},
        {"dialog_finalStartFight","But somebody don't want let you go and attacks you"},
        {"dialog_finalEnd","Now way is free and you can go whatever you want."},

        {"dialog_afterBattleStart","After battle one of enemy ship are alive."},
        {"dialog_afterBattleBuyout","Ask for bayout, maybe they send some credits to you"},
        {"dialog_afterBattleTeachPilots","Sciences from ship can teach some of your pilots"},
        {"dialog_afterBattleUpgradeSpell","Sciences from ship can try ti upgrade your main ship"},
        {"dialog_afterBattleOpenCells","Unlock navigation system to scout all sector"},
        {"dialog_afterBattleHireAction","Hire them"},
        {"dialog_afterBattleSearchFor","Search for money or items"},
        {"dialog_afterBattleKillAction","Kill them and take all goods"},
        {"dialog_afterBattleRepairAction","Repair him and leave him"},
        {"dialog_afterBattleTeachOk","{0} upgraded"},
        {"dialog_afterBattleUpgradeSpellOk","Big gun upgraded {0}"},
        {"dialog_afterBattleUpgradeSpellFail","Nothing to upgrade"},
        {"dialog_afterBattleCellOpen","All sectors cell scouted"},
        {"dialog_afterBattleBuyoutConfirm","Buyout confirm credits:{0}"},
        {"dialog_afterBattleBuyoutFail","Buyout fail"},
        {"dialog_afterBattleSearchOk","Credits add: {0}."},
        {"dialog_afterBattleSearchFail","Nothing."},
        {"dialog_afterBattleKillOk","Money doesn't smell. {0}"},
        {"dialog_afterBattleKillFail","He running away."},
        {"dialog_afterBattleHireOk","You hired a new pilot. Type:{0}  Config:{1}"},
        {"dialog_afterBattleRepairOk","Repair complete reputation add"},
        {"dialog_afterBattleRepairFail","Repair fail."},
        {"dialog_afterBattleMicrochip","Decompile ship and try to find microchip for upgrades"},
        {"dialog_afterBattleMircochipOk","Ok"},
        {"dialog_afterBattleMircochipFail","Fail"},

        {"dialog_dungeonExitFinalWin","This military base completly destoyed"},
        {"dialog_dungeonExitGo","Grab all items and go"},
        {"dialog_dungeonExitFinalBattle","This is main militaly base at this sector"},
        {"dialog_dungeogArmyEnterStart","This is military sector. Do you really want to go there?\nReinforcements will come immediately.\nHere you can find some special items."},
        {"dialog_dungeogArmyFriendGoIn","Ask your friend to go in."},

        {"dialog_Trader","Trader"},
        {"dialog_tradeStartSell","He want to sell {0} for {1} credits."},
        {"dialog_tradeStartBuy","He want to buy your item {0} for {1} credits."},
        {"dialog_tradeStartOk","Ok. Lets trade."},
        {"dialog_tradeStartNo","No, thanks."},
        {"dialog_tradeStartWantTrade","This ship wants to trade with you. {0}"},

        {"dialog_Space garbage", "Space garbage"},
        {"dialog_scGarbage", "In front of you a huge count of garbage."},
        {"dialog_scNoWant", "I don't want to dig in the trash."},
        {"dialog_scSearch", "Search on border. [Scouts:{0}]."},
        {"dialog_scDive", "Dive deep. [Scouts:{0}]"},
        {"dialog_nothing", "Nothing"},
        {"dialog_scAmbush", "Ambush!"},
        {"dialog_scWeapon", "This is new weapon {0}"},
        {"dialog_scScouted", "{0} points on global map scouted."},
        {"dialog_scMap", "This is galaxy map! {0}"},

        {"dialog_teacherImproved","Ship {0} Improved. Pilot level:{1}"},
        {"dialog_teacherFail","Fail."},
        {"dialog_teacherStartPilots","This is science ship. They can teach some of your pilots [credits:{0}]."},
        {"dialog_teacherNo","No, thanks."},
        {"dialog_Science ship","Science ship"},
        {"dialog_teacherStartSience", "This is science ship. They can improve your fleet [credits:{0}]. Do you want to upgrade {1}?"},

        {"Anomaly", "Anomaly"},
        {"dialog_anomalySendScouts", "Send scouts and try to get some info."},
        {"dialog_anomalyBeliveMysielf", "I believe at myself. Come close to it."},
        {"dialog_anomalyGoAway","No. Go away." },
        {"dialog_anomalyStart","You find a strange anomaly. Looks like it will go away soon. Do you want to investigate it?"},
        {"dialog_anomalyFreeze","Use freezing gun"},
        {"dialog_anomalyExplosive","Use explosive"},
        {"dialog_anomalyImpulse","Use impulse"},
        {"dialog_anomalyFire","Use fire"},
        {"dialog_anomalyChange","Something change."},
        {"dialog_anomalyRight","Looks like you doing right."},
        {"dialog_anomalyWrong","Wrong."},
        {"dialog_anomalyNoInfo","No info from scouts .Choose next move. Tries remain:{0}."},
        {"dialog_anomalyInfo","{0}{1}/{2} parts unlocked. Choose next move. Tries remain:{3}."},
        {"dialog_anomalyDeactivated","You successfully deactivate anomaly. {0} of your ships improved."},
        {"dialog_anomalyNotDay","Not my day."},
        {"dialog_anomalyDestroyed","Anomaly gone away."},


      /*P2*/  {"battleSpells", "Commander ship special options.\nAny shot will take some batteries for a period.\nYou must catch the moment to use them successfully."},
      /*P1*/  {"battleStart", "Battle starts.\nAll your ships will choose target and attack by self." },
      /*P1*/  {"battleEnemy", "Enemies fleet" },
      // /*P2*/  {"TutorMyMainShip", "Your main ship. To move it just click right mouse button on map."},
      /*P1*/  {"battleYour", "Your fleet. You can't control it directly.\nOnly choose tactics." },
      /*P2*/ {"battleMainShip", "You can control commander ship. Use mouse to select and move it. And use skill to teleport it to another location" },
        {"mapInsideInventory", "This is your fleet page. Here you can change equipment of your ships, or do some upgrades."},
        {"mapMain","This is global map.\nYou can move only to near places. To move click to point you want to go." },
        {"mapInventory", "Click here to choose equipment of your fleet." },
        {"mapFleetFast", "Your fleet. You can't control it directly.\nOnly choose tactics."},
        {"mapUpgrade", "One of your ships can be upgraded." },
        {"preBattle", "Preparation for the battle.\nChoose equipment suitable against the current opponent, based on information from scouts"},
        {"shopMain", "This is shop \nHere you can buy or sell something. Different good at different sectors can costs different money. Try to sell and buy at right sectors"},
        {"endBattle", "Choose a way to split bonus credits.\n If you want to level up battle ships choose \"to pilots\".\nIf you want to buy weapons or upgrade something choose \"to main\" "},

        {"TutorCloseForever", "Do not show this tip again"},

        {"Tutorial", "Tutorial"},

        {"TutorMoveGlobal", "To move camera use mouse or WSAD"},
        {"TutorHomeButton", "To find your fleet press home button"},
        {"TutorDifferentTypesCells", "Different types of cells contains different events.\nYou can move only to closest cells.\nChoose target wisely"},
        {"TutorDialog", "At dialogs you can choose different ways."},

        {"dialog_tutorEnds", "Tutorial ends. You are ready."},
        {"dialog_CantAttack", "You can't attack now. Go to shop and buy weapons."},
        {"TutorMove", "You can control ONLY commander ship\nClick right mouse button to move commander ship."},
        {"TutorRecharge", "Help your ships with recharge shield.\nIf one of your ships are damaged - help him."},
        {"TutorMachineGun", "Use machine gun to destroy enemies.\nIf you have good chances to damage enemy use it."},
        {"TutorEngineLock", "Use engine locker to disable enemies.\nUse it to help battle ships hit enemies."},
        {"TutorChangeTactics", "Change battle ship tactics.\nIf your ship if better against special types of enemy you can change priority targets of it."},

        {"ConfirmCloseTutor", "You closing tutorial.\nIf you want repeat, you can find it at menu."},

        {"StartTutorMoveGlobal", "To move camera use mouse or WSAD. Click right mouse button to place you want to move"},
        {"TutorShootMainShip", "Use machine gun to destroy enemy turret."},
        {"CantDropNow", "You can't sell items now."},
        {"startGameNoTutor", "Pass TUTORIAL first."},
        {"toGame", "Play"},
        {"toTutor", "Return"},
        {"Cancel", "Cancel"},
        {"Galaxy gate", "Galaxy gate"},
        {"wantStartTutor", "This is short tutorial. Pass it to understand basic of game."},
        {"TutorPreBattle", "Equip your fleet."},
        {"TutorStartShop", "Buy weapons for your battle ship."},
        {"resolutionTooLow", "Screen resolution is too low. Maybe you will have some problems. Minimum is 1280 and 720"},
        {"Move camera", "Move camera"},
        {"Commander Guns", "Commander Guns"},

        {"ParameterTypeScouts", "Amount of information you get before battle. Using at some dialogs"},
        {"ParameterTypeRepair", "Each turn repair battle ships hull points on {0} percent."},
        {"ParameterTypeChanrgeCount", "Count of batteries you can use at battle {0}"},
        {"ParameterTypeChanrgeSpeed", "Decrease reload batteries period on {0}%"},
        {"ParameterTypeEngine", "Radius of teleportation {0}. Reload period {1}"},

        {"cocpit", "Cockpit"},
        {"engine", "Engine"},
        {"wings", "Wings"},
        {"EParameterItemRaritynormal", "Normal"},
        {"EParameterItemRarityimproved", "Improved"},
        {"EParameterItemRarityperfect", "Special"},


        {"EParameterShipspeed", "Speed"},
        {"EParameterShipturn", "Turn Speed"},
        {"EParameterShipbodyPoints", "Hull points"},
        {"EParameterShipshieldPoints", "Shield points"},
        {"EParameterShiparmor", "Armor"},
        {"EParameterShipmodulsSlots", "Modules slots"},



    };

}

