using System.Collections.Generic;


public static class EspLocalization
{
    public static Dictionary<string, string> _locals = new Dictionary<string, string>()
    {
           {"StartInfo","Usted está en el sector remoto de la galaxia en el mismo borde del espacio habitado.Como resultado de operaciones especiales, que tuvo que robar la nave de mando y la energía elemento en ella. Ahora usted tiene que encontrar el resto de los elementos para abrir el galaxy gates, y entregar los datos a su comando"},
{"Yes","Sí"},
{"No","No"},
{"Ok","Ok"},
{"Reflected","Efecto se refleja"},
{"CriticalDamage","Crítica de daños y perjuicios. Si los daños más de {0} nave sea destruida"},
{"Event","Evento"},
{"RechargeSheildSpell","La recarga de escudo en la {0}%"},
{"ArmorField","Armadura:{0}/{1}"},
{"UnstableCore0","Algunos de sus barcos pueden sufrir daños causa de su núcleo es inestable. Encontrar servicios de reparación para estabilizar su núcleo. Si la estabilidad del núcleo vez menos de -10 su flota será destruido."},
{"MapExit","¿Quieres salir al menú principal?Progreso se guarda y se puede reanudar más tarde."},
{"CantByLevel","No puede usar este elemento causa nave nivel es demasiado bajo"},
{"ReqireLevelFeild","Requieren a nivel piloto:{0}"},
{"CanCauseNoLevel","No puede actualizar arma causa piloto no tiene suficiente nivel.Nivel piloto:{0}. Objetivo De Nivel{1}"},
{"RoundWaveStrike","El daño de todos los buques de cerca por [{2}/{3}].[Coste:{0}/{1}]"},
{"And","y"},
{"Shop","Tienda"},
{"BaseCenter","La sede de la"},
{"BaseEnter","Base militar"},
{"SectorDungeon","Base militar"},
{"SupportModul","Módulo de apoyo. Afectan en armas."},
{"ActionModul","La acción del módulo de"},
{"CataclysmProcess","{0} células destruidas"},
{"RemainCataclysm","Días, siendo:{0}"},
{"VeryEasy","Muy fácil"},
{"Easy","Fácil"},
{"Normal","Normal"},
{"Hard","Duro"},
{"Imposilbe","Imposible"},
{"Radius","Radio"},
{"Sector","Sector"},
{"Reload","Recarga"},
{"WeaponShieldPerHit","Escudo stealer"},
{"ShootPerTime","Bala contar"},
{"cantUpgrade","No se puede actualizar"},
{"UpgParams","Dou desea actualizar {0}? Cuesta {1} créditos."},
{"CoreSector","Objetivo del sector"},
{"NotCoreSector","Simple sector"},
{"StatisticDifficulty","Dificultad:{0}%."},
{"StatisticConfig","Ejército:{0}."},
{"StatisticMapSize","Tamaño del mapa:{0}."},
{"StatisticFinalArmyPower","Poder Final:{0}."},
{"StatisticRecievedOpendPoints","Puntos recibidos:{0}."},
{"StatisticDate","{0}"},
{"Fight","Lucha"},
{"StatisticNoResult","No hay resultados"},
{"StatisticNoLastResult","Espere a que el juego..."},
{"StatisticLastResult","Último resultado:"},
{"Sacrifice","El sacrificio de la nave {0} en {1} de {2}"},
{"MaxArmyCount","La flota del conde:{0}/{1}"},
{"EndGameDays","Días:{0}"},
{"BattleWinsStat","Gana:{0}"},
{"OpenWeaponsEndGame","Nuevas armas para empezar a abrir {0} y {1}"},
{"OpenConfigEndGame","Nuevo tipo de flota disponible para jugar: {0}"},
{"FrontShieldActivate","Mega-shield activado"},
{"Crit","Crit {0}!"},
{"WinEnd","Todo bien ahora eres libre y todo va a estar bien. Tal vez..."},
{"LoseEnd","Su flota destruida."},
{"RepairDroneSpell","Lanzamiento de reparación de drones. Cuando la nave llega cerca de drone se inicia la curación de la misma. Sanar {1}% de casco puntos."},
{"Shield Locker","Escudo De Armario"},
{"Auto shield","Auto escudo"},
{"Shield regeneration","Escudo de regeneración"},
{"Repair drone","Reparación de drones"},
{"Rocked catcher","Sacudió catcher"},
{"Deflector","Deflector de"},
{"Side strike","Lado de la huelga"},
{"Engine locker","Motor de armario"},
{"EMI mine","EMI mina"},
{"Power mine","El poder de la mina"},
{"Fire mine","El fuego de la mina"},
{"Front shield","Mega-escudo"},
{"Body armor","Casco de la armadura"},
{"Teleportation","La teletransportación"},
{"Laser power","Potencia del láser"},
{"Rockets power","La energía de los cohetes"},
{"Bomb power","Bomba de alimentación"},
{"EMI power","EMI poder"},
{"Impulse power","Impulso de energía"},
{"Speed","Barco De Velocidad"},
{"Turn Speed","Velocidad De Giro"},
{"Bullet speed","La velocidad de la bala"},
{"Spray fire","Rociador de incendios"},
{"Longer dist","No dist"},
{"Pusher","Empujador"},
{"Burner","Quemador"},
{"Stopper","Tapón"},
{"Locker","Armario"},
{"Critical","Crítica"},
{"AOE","AOE"},
{"Wider","Más amplio"},
{"Close strike","Cerca de la huelga"},
{"Chain strike","Multi destino"},
{"Penetrating shot","Penetrante tiro"},
{"Powerful recoil","Potente retroceso"},
{"Shield stealer","Escudo stealer"},
{"More bullets","Más balas"},
{"Power shot","Power shot"},
{"Fire wave","El fuego de la onda"},
{"Protector","Protector"},
{"Beam upgrade","Haz actualización"},
{"Heavy weapons","Armas pesadas"},
{"Maximum shield","Máximo escudo"},
{"scout","Los Scouts"},
{"repair","Servicios de reparación de"},
{"chargesCount","Los Cargos De Contar"},
{"chargesSpeed","Los Cargos De Velocidad"},
{"engineParameter","Motor"},
{"Preparing","La preparación de"},
{"Return","Volver"},
{"Evade enemy","Evadir enemigo"},
{"RepairAction","Reparación"},
{"Wait","Esperar"},
{"Hiding","Ocultar"},
{"FlangAttack","En El Flanco De Ataque"},
{"MainShipBlinkDesc","Te teletransporta a su nave principal de destino seleccionado"},
{"MainShipBlinkName","Puente"},
{"hookShot","Imán de la huelga"},
{"wantUpgrade","Desea actualizar {0}? Créditos:{1}"},
{"wantUpgradeLong","Desea actualizar {0}? Créditos:{1}. Microchips:{2}"},
{"engineLock","Motor de armario"},
{"lineShot","La línea de tiro"},
{"throwAround","La potencia de la explosión"},
{"vacuum","Vacío"},
{"mineField","Campo De Minas"},
{"distShot","Power shot"},
{"artilleryPeriod","La artillería"},
{"repairDrones","Reparación de drones"},
{"rechargeShield","La recarga de escudo"},
{"roundWave","Ronda de los daños"},
{"machineGun","Ametralladora"},
{"WANT_UPGRADE_WEAPON","¿Quieres actualizar {0}?"},
{"WeaponMaxLevel","Arma tiene de máximo nivel de"},
{"Processing","Procesamiento de..."},
{"Win","Ganar!"},
{"Lose","Perder"},
{"RunAwayComplete","Huir completa"},
{"Type","Tipo de"},
{"Regen","La regeneración"},
{"DamageBody","Los daños del casco"},
{"DamageShield","Escudo de daño"},
{"HealBody","Reparación de casco"},
{"HealShield","La recarga de escudo"},
{"ChargesCount","Los cargos de conteo {0}"},
{"ChargesDelay","Cargos por demora {0}"},
{"Scouted","Explorado"},
{"Gate","Puerta"},
{"Home","Casa"},
{"Complete","Completa {0}"},
{"Target","Destino {0}"},
{"Delay","Retraso"},
{"trick_turn","Vuelta rápida para atacar el enemigo"},
{"trick_twist","La nave se mueve a un lado para evitar el ataque y hacer huelga de flanco"},
{"trick_loop","Bucle para evitar el ataque y confundir al enemigo"},
{"trick_frontStrike","Ram huelga"},
{"trick_name_turn","La deriva"},
{"trick_name_twist","Twist"},
{"trick_name_loop","Bucle"},
{"trick_name_frontStrike","Ram"},
{"healBodySupport","Reparación de drones"},
{"healShieldSupport","La energía drone"},
{"shildDamage","Escudo de armario"},
{"shieldLocker","Bloqueo de escudo del enemigo."},
{"autoShieldRepair","Reparación escudo de abajo."},
{"shieldRegen","Más rápido escudo de la restauración."},
{"autoRepair","Agregar HP cuando la nave tienen poco hp."},
{"antiPhysical","Destruir física de las balas en el radio cercano."},
{"antiEnergy","Destruir la energía balas en radio cercano"},
{"closeStrike","Cuando el enemigo cerca, especial de lanzamiento de bala a golpear."},
{"engineLocker","Destruir motor de enemigo."},
{"systemMines","Poner el sistema de minas, estrellándose enemigos motores"},
{"damageMines","Poner el daño de las minas para golpear a los enemigos"},
{"frontShield","Por un corto periodo, todas las balas no pueden hacer daño."},
{"armor","Disminuir los daños en los buques de casco"},
{"fireMines","Poner el daño de las minas, la bruja puede disparar a los enemigos."},
{"blink","La nave puede teletransportarse a mejores lugares."},
{"laserUpgrade","Aumentar la potencia de todas las armas láser para 1/ 1 por cada nivel."},
{"rocketUpgrade","Aumentar la potencia de todos los lanzacohetes para 1/ 1 por cada nivel."},
{"EMIUpgrade","Aumentar la potencia de todos los EMI armas para 1/ 1 por cada nivel."},
{"impulseUpgrade","Aumentar la potencia de todos impulso armas para 1/ 1 por cada nivel."},
{"bombUpgrade","Aumentar la potencia de todos los de la bomba de armas para 1/ 1 por cada nivel."},
{"WeaponSpeed","Aumentar la velocidad de todas las balas."},
{"questKills","{0} mata"},
{"Fleet","La flota"},
{"RusLang","Ruso"},
{"EngLang","Inglés"},
{"EspLang","Español"},
{"ReloadToLoc","Reiniciar la partida para la actualización de la localización"},
{"SettingsWindow","Ventana De Configuración"},
{"RechargeButton","La Recarga De Escudo.Costo[{0}/{1}]"},
{"BuffButton","Aumento de los parámetros de la nave.[Coste:{0}/{1}]"},
{"PowerWeaponButton","Aumento de la próxima disparar a los daños de la nave.[Coste:{0}/{1}]"},
{"CellScouted","Coordenadas Explorado [{0},{1}]"},
{"PriorityTarget","Objetivo Prioritario"},
{"BaitPriorityTarget","Cebo De Destino"},
{"engineCrash","El motor se estrelló para {0:0} sec"},
{"shieldCrash","Escudo de apagar para {0:0} sec"},
{"fireCrash","El fuego comienza! {0:0} sec"},
{"winAgainst","Gana en contra de {0}"},
{"damageByQuest","Daños por {0}"},
{"killLight","Naves de luz mata"},
{"killMed","Medio de los buques mata"},
{"killHeavy","Pesados barcos mata"},
{"mainShipKills","Mata por el comandante"},
{"upgradeWeapons","Las armas de los niveles de actualizaciones"},
{"sellModuls","Vender módulos"},
{"PriorityTargetDesc","Todos los que tu nave se trate de un ataque barco seleccionado."},
{"BaitPriorityTargetDesc","Todos los barcos enemigos tratarán de atacar barco seleccionado"},
{"SpellModulChargers","Los cargos requieren: {0} con retraso {1} sec."},
{"ArtillerySpell","Se inicia el fuego en la zona seleccionada. Total de balas {0}. El daño de cada bala:{2}/{1}."},
{"EnerguLockSpell","Destruir los motores en todos los barcos enemigos en el radio {1} para {0} sec."},
{"LineSHotSpell","Triple tiro por la dirección seleccionada. El daño Base: {0}/{1}. Y comienza el fuego por {2} sec. Total de daño de fuego:{3}"},
{"MinesSpell","Conjunto {0} minas {1} la sec a la ubicación seleccionada. Cada mina daños {2}/{3}"},
{"ShieldOffSpell","Desactivar los escudos de las naves en la radio para {0} sec. Y los daños y perjuicios de escudo {1}."},
{"TrowAroundSpell","Crear una onda de choque de la bruja de lanzar alrededor de todos los buques en la radio con el poder {0}. Y el escudo de daño {1}."},
{"DescHookShotSpell","Empuje todos los target a su comandante de la nave y el daño de los motores de un {0} sec"},
{"KillUIPilotMini","Mata:{0}"},
{"KillUIPilot","Mata:{0}/{1}"},
{"Remain","Siendo"},
{"EngineDest","Motor destruido"},
{"ShieldDest","Escudo destruido"},
{"FireDest","Fuego a bordo"},
{"DoWantRetire","¿Quieres huir?"},
{"NoSafeGame","No guardar la partida"},
{"MaxLevel","Max"},
{"DamageTimeEffectRepair","Quitar todos los efectos negativos"},
{"AddMicrochips","Agregar los microchips {0}"},
{"Microchips","Microchips"},
{"ArmyAdditionalPower","Cada turno las flotas enemigas serán mejoradas"},
{"WeaponAOE","Afecta para todos los barcos en el radio. {0}. Disminuir el daño por {1}%."},
{"WeaponSector","Aumentar el objetivo del sector de {0}% por nivel"},
{"WeaponPowerShot","Aumentar el tiempo de recarga de {0}%. Aumento de los daños por {1}%."},
{"WeaponPowerShotSupport","Aumentar el tiempo de recarga de {0}%. Aumento de restaurar la energía por {1}%."},
{"WeaponShootPerTime","Agregar 1 bala por sarmiento. Disminución armas de energía por {0}% "},
{"WeaponLessDist","Disminuir objetivo del radio {0}%. Aumento de los daños por {1}%."},
{"WeaponLessDistSupport","Disminuir objetivo del radio {0}%. Aumento de restaurar la energía por {1}%."},
{"WeaponPushSupport","Todos los poderes externos deja de afectar en barco"},
{"ShipTurnSpeed","Aumento de la velocidad de giro de la nave por {0}%"},
{"ShipSpeed","Aumento de la nave de max velocidad por {0}%"},
{"ShieldDouble","Aumento de poder de los escudos por {0}% . Disminución de la nave de los puntos en el cuerpo por {1}%"},
{"ShipDecreaseSpeed","Aumento de armas de energía por {0}%. Disminución de la nave de max velocidad por {1}%"},
{"WeaponIncreaseDamage","Aumento de los daños por {0}% para todos los {1} armas."},
{"WeaponNoBulletDeath","La bala no destruir al alcanzar el objetivo. Aumentar el tiempo de recarga de {0}%."},
{"WeaponShieldPerHitDesc","Disminución armas de energía por {0}%. Restaurar {1} de escudo por golpe."},
{"IgnoreShieldLevel1","Ignorar escudo. Disminuir el daño por {0}%."},
{"Ignore shield","Ignorar escudo."},
{"WeaponSelfDamage","Añadir un {0}/ {0} Daño. Pero los daños propio barco cuando las huelgas en {1}/{1}"},
{"WeaponSelfDamageSupport","Añadir un {0}/ {0} de puntos de restauración. Pero los daños propio barco cuando las huelgas en {1}/{1}"},
{"WeaponPush","Empuje de destino cuando se golpea"},
{"WeaponCrit","Añadir un {0}% de probabilidad de obtener un {1} adicionales avería en el casco."},
{"WeaponCritSupport","С {0}% de probabilidad de reparación {1} casco puntos."},
{"DamageTimeEffect","con un {0}% de probabilidad de {1:0} sec, cuando es golpeado."},
{"DamageTimeEffectEngine","Apague el motor {0}"},
{"DamageTimeEffectShield","Fuera de todos escudo {0}"},
{"DamageTimeEffectFire","Inicio de incendio {0}"},
{"ResistDamages","Refleja todos los efectos negativos"},
{"wantSell","¿Quieres vender elemento de {0}?"},
{"wantBuyItem","¿Quieres comprar elemento de {0}?"},
{"valuable goods","bienes valiosos"},
{"invaluable goods","inestimable bienes"},
{"DamageInfoUI","Daño: {0}/{1}"},
{"KillsInfoUI","Mata: {0}"},
{"ReputationChanges","{2} la reputación de cambio {0} => {1}."},
{"ReputationData","{0} reputación: {1}"},
{"HirePilot","Usted contrató a un nuevo piloto. Tipo:{0} Config:{1}"},
{"Destroyed","Destruido"},
{"Completed","Completado"},
{"StartNewGameFieldSize","El tamaño del Sector"},
{"StartNewGameCoresCount","Teclas de contar"},
{"StartNewGameSectorsCount","Sectores recuento"},
{"All to me","La flota"},
{"Equal","Igual"},
{"All to ship","A los acorazados"},
{"To Map","Mapa"},
{"EngineLockNameA1","Radio"},
{"EngineLockNameB2","Baja el tiempo"},
{"EngineLockDescA1","Aumentar el radio de afecto en {0}"},
{"EngineLockDescB2","Disminución de baterías tiempo de recarga en {0} sec"},
{"ArtilleryNameA1","Las balas"},
{"ArtilleryNameB2","Rápido dispara"},
{"ArtilleryDescA1","Aumentar el recuento de balas en {0}"},
{"ArtilleryDescB2","Disminuir el período comprendido entre balas en {0} sec"},
{"DistShotNameA1","Motor de bloqueo de la"},
{"DistShotNameB2","AOE"},
{"DistShotDescA1","El motor de daños en caso de choque. El motor se detiene para {0} sec"},
{"DistShotDescB2","Área de aumento de daño en {0}"},
{"LineShotNameA1","Penetraiting"},
{"LineShotNameB2","Termit"},
{"LineShotDescA1","No hay bala de la muerte cuando es golpeado"},
{"LineShotDescB2","Aumentar el poder de fuego en {0}"},
{"MachineGunNameA1","Multishot"},
{"MachineGunNameB2","Más balas"},
{"MachineGunDescA1","Dispara a todos los objetivos cercanos. Las balas count: {0} para cada objetivo"},
{"MachineGunDescB2","Más balas en línea. Las balas count: {0}"},
{"MinesSpellNameA1","Fuego"},
{"MinesSpellNameB2","Daños en el motor"},
{"MinesSpellDescA1","Añade daño de fuego para {0} sec"},
{"MinesSpellDescB2","Destruir los motores para {0} sec"},
{"RechargeSheildNameA1","AOE"},
{"RechargeSheildNameB2","Resiste"},
{"RechargeSheildDescA1","Efectos a todos los barcos cercanos a {0} radio"},
{"RechargeSheildDescB2","Agregar para {0} sec resistir a la nave"},
{"RepairDroneNameA1","Escudo"},
{"RepairDroneNameB2","Buff"},
{"RepairDroneDescA1","Reparación de escudo para {0} %"},
{"RepairDroneDescB2","Agregar para {0} beneficio de velocidad de"},
{"ShieldOffNameA1","Batería"},
{"ShieldOffNameB2","Fuego"},
{"ShieldOffDescA1","Disminución del recuento de las baterías"},
{"ShieldOffDescB2","Añade daño de fuego para {0} sec"},
{"TrowAroundNameA1","Motores"},
{"TrowAroundNameB2","Caída de la carga"},
{"TrowAroundDescA1","Destruir los motores cuando es golpeado por {0} sec"},
{"TrowAroundDescB2","Descargar todas las armas de destino"},
{"VacuumNameA1","Radio"},
{"VacuumNameB2","Batería"},
{"VacuumDescA1","Aumentar el radio del efecto de {0}"},
{"VacuumDescB2","Disminución de baterías tiempo de recarga para {0} sec"},
{"HookShotNameA1","Radio"},
{"HookShotNameB2","Batería"},
{"HookShotDescA1","Aumentar el radio del efecto de {0}"},
{"HookShotDescB2","Disminución de baterías tiempo de recarga para {0} sec"},
{"RaidersProCons","Pros: Buena velocidad, cantidad de ranuras para módulos.Contras: Pocos arma ranuras. Ningún escudo de regeneración."},
{"FederationProCons","Pros: Muchas arma ranuras. Escudo de regeneración.Contras: Baja velocidad."},
{"MercenaryProCons","Pros: Equilibrado.Contras: Equilibrado."},
{"OcronsProCons","Pros: Perfecto casco de la salud. Muchas ranuras para módulos.Contras: No hay miedo. Ningún escudo de regeneración."},
{"KriosProCons","Pros: Buen escudo. Perfecto escudo de regeneración.Contras: Bajo el casco de la salud."},
{"WeaponsStart","En el inicio de tus barcos tendrá uno de {0} o {1} complect."},
{"Paramscout","Scout puede proporcionarle información acerca de los enemigos del ejército.Y a veces se puede tratar de robar algo."},
{"Paramrepair","Entre las batallas que se necesita para reparar su flota.Esto va a ayudar a usted."},
{"ParamchargesCount","Aumento de la nave principal de los cargos de cuenta."},
{"ParamchargesSpeed","Aumento de la nave principal de los cargos de la regeneración de la velocidad."},
{"ParamEngine","Motor de actualización. Más velocidad y más rápido de recarga de parpadear."},
{"asteroidsEvent","Asteroide de vórtice"},
{"shieldsOffEvent","EMP de sobretensiones"},
{"ShipsRepaired","Los Buques Reparados"},
{"Raiders","Raiders"},
{"Federation","Federación"},
{"Mercenary","Mercenario"},
{"Ocrons","Ocrons"},
{"Krios","Krios"},
{"Droids","Droides"},
{"Light","La luz"},
{"Medium","Medio"},
{"Heavy","Pesado"},
{"Base","Base"},
{"ESideAttackStraight","Ataque como de costumbre"},
{"ESideAttackFlangs","El ataque de banderas"},
{"ESideAttackBaseDefence","El ataque sólo cerca de comandante de la nave"},
{"BaseDefenceYes","Defender la base"},
{"BaseDefenceNo","No"},
{"EGlobalTacticsFight","Lucha"},
{"EGlobalTacticsGoSafe","Permanecer en el seguro"},
{"ECommanderPriority1Base","Ataque el comandante de la nave"},
{"ECommanderPriority1Fast","Elija para atacar la nave más rápida"},
{"ECommanderPriority1Slow","Elige ataque barco más lento"},
{"ECommanderPriority1MinShield","Elegir a la nave de ataque con un mínimo de escudo"},
{"ECommanderPriority1MinHealth","Elegir a la nave de ataque con un mínimo de casco"},
{"ECommanderPriority1MaxShield","Elegir a la nave de ataque con max shield"},
{"ECommanderPriority1MaxHealth","Elegir a la nave de ataque con max casco"},
{"ECommanderPriority1Any","Cualquier barcos para atacar"},
{"ECommanderPriority1Light","Naves de luz será una prioridad"},
{"ECommanderPriority1Mid","Medio de los buques será una prioridad"},
{"ECommanderPriority1Heavy","Pesados barcos será una prioridad"},
{"QuestReward","Elegir una recompensa"},
{"Reputation","Reputación"},
{"Inventory","Inventario"},
{"ReputationElement","Enemigos:{0}"},
{"Trickturn","Vuelta rápida"},
{"Trickloop","Bucle"},
{"Tricktwist","Twist"},
{"Settings","Configuración"},
{"Private","Privado"},
{"Lieutenant","El teniente"},
{"Achievements","Logros"},
{"Captain","El capitán"},
{"Major","Principales"},
{"OpenNew","Desbloquear"},
{"FinalSector","Galaxy gates"},
{"Attack","Ataque"},
{"AttackHalfLoop","Truco ataque"},
{"Evade","Evadir"},
{"Level","Nivel"},
{"Start game","El comienzo del juego"},
{"Randomize","Randomize"},
{"Resume","Curriculum vitae"},
{"NotEnoughtBattries","Battries no están listos!"},
{"reloadBoost","Truco el tiempo de recarga:{0}"},
{"PointsToOpen","Puntos para desbloquear las opciones de inicio:"},
{"SpellMaxLevel","Nivel máximo alcanzado: {0}"},
{"WantChangeLang","Reiniciar la partida para la actualización de la localización."},
{"NoMouseMove","La cámara no tienen mover con el ratón."},
{"descWinner","Ganar en 1 batalla"},
{"descCaptain","Ganar a las 10 de la batalla"},
{"descMayor","Ganar en 100 batalla"},
{"descTeam five","La contratación de todos facción en un ejército"},
{"descFighter","Destruir el 100 naves enemigas"},
{"descDestroyer","Destruir 1000 naves enemigas"},
{"descAnnihilator","Destruir 10000 naves enemigas"},
{"descMerWin","Ganar como mercenarios"},
{"descFedWin","Ganar como de la federación"},
{"descKriWin","Ganar como krios"},
{"descOcrWin","Ganar como ocrons"},
{"descRdrWin","Ganar como reino"},
{"nameWinner","Ganador"},
{"nameCaptain","El capitán"},
{"nameMayor","El alcalde"},
{"nameTeam five","Equipo de cinco"},
{"nameFighter","Luchador"},
{"nameDestroyer","Destructor"},
{"nameAnnihilator","Annihilator"},
{"nameMerWin","Cabecilla de la banda"},
{"nameFedWin","El canciller"},
{"nameKriWin","Experimentales"},
{"nameOcrWin","Fanático"},
{"nameRdrWin","Rey"},
{"MercGlobal","Mercenario escondite"},
{"NotEnoughtMoney","No es suficiente créditos"},
{"NotEnoughtMoneyLong","No hay suficiente créditos {0}."},
{"NotEnoughtUpgrades","No hay suficiente microchips {0}."},
{"leave","Dejar"},
{"HireMerc","Alquiler de {1} la {0}. Nivel:{2}. Costo:{3} créditos."},
{"Take","Tomar"},
{"BrokenItem","Su elemento roto {0}"},
{"StabilizaInfo","Nivel de estabilidad:{0}"},
{"MainElements","Bloques de energía"},
{"Credits","Créditos"},
{"Health","Salud"},
{"Shield","Escudo"},
{"TurnSpeed","Gire a la"},
{"Unknown","Desconocido"},
{"NewGame","Nuevo Juego"},
{"Continue","Continuar"},
{"Exit","Salida"},
{"ScoutsFind","Scouts de encontrar algo!"},
{"Start point","Punto de inicio"},
{"ReinforcmentsCallNo","Sin refuerzos"},
{"ReinforcmentsCallConfig","Llamar a los refuerzos:{0}"},
{"ReinforcmentsCalled","Los refuerzos no está disponible"},
{"Retreat","Retiro"},
{"Upgrade","Actualización"},
{"Laser","Láser"},
{"Rocket","Cohete"},
{"Impulse","Impulso"},
{"Swarm","Enjambre"},
{"EMI","EMI"},
{"Beam","Haz"},
{"MovingArmy","Las fuerzas especiales de {1}Estado:{2}. Potencia:{3}"},
{"MovingArmyBorn","Las fuerzas especiales de {0} aparecer. Coordenadas:{1}"},
{"AdditionalPower","Enemigos actualizaciones"},
{"AddCredits","Añadir créditos:{0}"},
{"Comparable","Comparable"},
{"Risky","Arriesgado"},
{"Easily","Fácilmente"},
{"confirmDismiss","Usted realmente quiere despedir el barco {0}?"},
{"MovingArmyName","SpecOps {0}"},
{"RelocateTo","Reubicar a:{0}"},
{"Demo","Esta es la versión demo. No estamos dispuestos a ver más. Máximo visitó los sectores de:{0}. El máximo de turnos:{1}"},
{"RecievePoints","Usted obtendrá puntos para desbloquear después de ganar. La cantidad depende de la dificultad. También usted puede conseguir algunos puntos ganando batallas."},
{"AA_FXAA","Anti aliasing"},
{"Sound","Sonido"},
{"Turret","La torreta"},
{"battlefield","Campo de batalla"},
{"Amry","Amry"},
{"Trader","Comerciante"},
{"RepairCompete","Reparación De Competir"},
{"RepairStation","Estación De Reparación"},
{"BrokenNavigation","Roto de navegación"},
{"modifBaseStart","Esta es la modificación de la base. Usted puede tratar de modificate algo."},
{"modifCellName","Modificación de la estación de"},
{"scout_shipType","Ningún barco de la información de tipo"},
{"scout_weapons","No hay información de armas"},
{"scout_level","Ningún nivel info"},
{"scout_moduls","No hay módulos info"},
{"scout_spells","No hay armas de gran info"},
{"targteFar","Destino está demasiado lejos"},
{"Battle reward","La batalla de recompensa:"},
{"Fleet money","La flota de dinero:"},
{"armyCount","El ejército de conteo es de {0}"},
{"armyCountBetween","El ejército de contar entre {0} y {1}"},
{"armyWeaponsContains","Armas de tipos contiene {0}"},
{"armyHaveMotherShip","Han comandante de la nave"},
{"armyJustFleet","Sólo flota"},
{"armyWeaponsCount","Las armas del conde:{0}. Módulos de conteo:{1}"},
{"armyUsingWeapons","El uso de las armas:{0}"},
{"DescVacuumSpell","Crea un vacío sobre el área de destino que succiona a las unidades enemigas. Potencia:{0}. Escudo de daño:{1}"},
{"ChainModulDesc","Disparar a todos los objetivos en un radio de. Disminuir el daño en {0}%"},
{"FireNearModulDesc","Puede disparar a los enemigos cercanos para {0} s cuando disparar."},
{"SprayModulDesc","Disparar con {0} balas en lugar de uno. Aumentar el tiempo de recarga por {1}%."},
{"WeaponSpeedModulDesc","Aumento de la velocidad de la bala por la {0}% por nivel"},
{"DescWeaponDistModul","Aumentar la finalidad de radio por {0}% por nivel"},
{"WeaponEngine","Bloqueo enemigo motor para un período"},
{"MachineGunSpellDesc","Serie de {0} rápida balas. Daño: {1}/{2}"},
{"DistShotSpell","Sola bala. Sólo avería en el casco {0}."},
{"DistShotSpellSpecial","Sola bala. Sólo avería en el casco {0}. Si el objetivo no tiene escudo de destruir motor para {1} sec."},
{"rep_adv_friend","Que son amigos. Tal vez puede ayudar."},
{"rep_adv_neutral","Las flotas se lucha, pero se puede comerciar con ellos."},
{"rep_adv_negative","Usted todavía puede negociar con ellos, pero los precios va a ser malo"},
{"rep_adv_enemy","No hay comercio. Sólo la lucha! La fuerza especial tratará de encontrar y matar a usted."},
{"rep_friend","Amigos"},
{"rep_neutral","Neutral"},
{"rep_negative","Negativo"},
{"rep_enemy","Enemigo"},
{"DemoStart","Esta no es la versión final del juego, algo que se puede cambiar más tarde."},
{"DemoStart2","Usted tendrá sólo 25 vueltas. Y algunos mecánicos serán bloqueados."},
{"dialog_Ok","Ok"},
{"dialog_MovingArmyStart","Usted ha sido ocupado por la fuerza especial. Usted no tiene chanse a ejecutar."},
{"dialog_MovingArmyFight","Lucha"},
{"dialog_MovingArmyWin","Las fuerzas especiales destruido."},
{"dialog_MovingArmyGerReward","Obtener todos los artículos de valor."},
{"dialog_shopEnemy","Ves a la tienda. Nadie quiere comerciar con usted."},
{"dialog_shopTrade","Ves a la tienda. Tal vez usted quiere comprar algo?"},
{"dialog_repairEnemy","Esta es la estación de reparación. No van a ayudar a usted."},
{"dialog_repairStart","Esta es la estación de reparación. Podemos reparar nuestra flota aquí."},
{"dialog_fixCrit","Revisión de todos los daños y perjuicios. Cuesta{0}"},
{"dialog_repairCritFixed","Crítica daños fijos"},
{"dialog_repairAll","Sí repare todos.{0} créditos"},
{"dialog_repairNotEnough","No tengo suficientes créditos"},
{"dialog_asteroid_nothingComplete","No pasa nada. Ha completado con éxito el camino"},
{"dialog_asteroid_nothingCompleteRepair","No pasa nada, pero algunos barcos necesitan ser reparados. Ha completado con éxito el camino"},
{"dialog_asteroid_start","Gran campo de asteroides. Usted necesita llegar de alguna manera a otro lado."},
{"dialog_asteroid_fireAll","El fuego de todas las armas"},
{"dialog_asteroid_slow","Lento ir a través de campo."},
{"dialog_asteroid_brokenShip","Usted ve {0} roto de la nave."},
{"dialog_asteroid_brokenShipRepair","Intente repararlo [Reparación:{0}]."},
{"dialog_asteroid_brokenShipdecompile","Intentar descompilar por el dinero."},
{"dialog_repairResultFull","Esta nave no puede ser totalmente reparado, pero ahora usted puede utilizar algunas partes. {0}"},
{"dialog_repairResultCant","Esta nave no puede ser totalmente reparado, pero que no tienen lugar para los artículos."},
{"dialog_asteroid_weaponsFire","Armas explosivas fácilmente destruir suficiente asteroide. Ahora usted tiene una manera."},
{"dialog_asteroid_weaponsFail","Tus armas son no tiene mucho poder para crear de una manera throug. Y algunos de sus buques de sufrir daños"},
{"dialog_asteroid_haveWay","Finalmente, usted tiene una manera! Pero algunos de sus buques de sufrir daños"},
{"dialog_battlefield_start","Se puede ver que algunas {0} barcos está en contra de uno al otro."},
{"dialog_battlefield_provocate","Ocultar y provocate ellos"},
{"dialog_battlefield_reconcile","Tratar de reconciliar a todos los lados"},
{"dialog_battlefield_thanks","Gracias!"},
{"dialog_battlefield_diplomacyWin","Tus habilidades diplomáticas son perfectos. Que no se pelea, y te enviaremos un regalo para ayudar. Reputación agregar {Biblioteca.REPUTATION_RELEASE_PEACEFULL_ADD}."},
{"dialog_battlefield_run","Run!"},
{"dialog_battlefield_shoot","Disparar cerca!"},
{"dialog_battlefield_diplomacyFail","Tus habilidades diplomáticas es horrible. Pero ahora quieren matar a usted en lugar de uno al otro."},
{"dialog_battlefield_shit","Mierda."},
{"dialog_battlefield_theyAttack","Este no es su día. Ellos atacando!"},
{"dialog_battlefield_ufff","Ufff... Genial."},
{"dialog_battlefield_stopAttack","Que dejan de intentar atacar a nadie y se va corriendo. Tal vez esto no es malo. Al menos a salvar vidas"},
{"dialog_battlefield_youRun","Te marchaste"},
{"dialog_battlefield_artillery","Captura el momento y el fuego de artillería"},
{"dialog_battlefield_wait","Esperar"},
{"dialog_battlefield_theyBattle","Se inicia la batalla."},
{"dialog_battlefield_killEachOther","La batalla termina. Se matan los unos a los otros. Y te encuentras con algunos créditos {0}."},
{"dialog_battlefield_isee","Veo"},
{"dialog_battlefield_battleHaveWinner","La batalla termina. Ganar secundarios de tomar trofeos y desaparece. Usted no puede hacer nada"},
{"dialog_battlefield_good","Bueno"},
{"dialog_battlefield_goodSHot","Buen disparo. Destruir todos ellos. Después de la batalla, usted encontrará algunos elementos"},
{"dialog_battlefield_fight","Lucha"},
{"dialog_battlefield_killYou","Ahora quieren destruir."},
{"dialog_navigation_start","Usted tiene una señal de socorro"},
{"dialog_navigation_closer","Acercarse"},
{"dialog_navigation_trap","Es una trampa!"},
{"dialog_navigation_fight","Lucha"},
{"dialog_navigation_askHelp","Usted ve un {0} barco roto con sistema de navegación. Él pidiendo ayuda"},
{"dialog_navigation_shelter","Enviar scout para librarlo al refugio más cercano. [Scouts: {0}]"},
{"dialog_navigation_repair","Tratar de reparar el sistema de navegación. [Reparación {0}]"},
{"dialog_navigation_gift","Su regalo: {0}"},
{"dialog_navigation_noFree","No espacio libre para el regalo"},
{"dialog_navigation_scouted","{0} células en el mapa mundial explorado."},
{"dialog_navigation_shelterOk","Usted logra encontrar la manera de refugio. {0}."},
{"dialog_navigation_repairOk","Con éxito la reparación de la nave. La reputación de agregar."},
{"dialog_navigation_tryHire","Tratar de coches"},
{"dialog_navigation_takeMoney","Tomar dinero"},
{"dialog_navigation_hired","Buque contratado {0}."},
{"dialog_changeitem_start","Este barco se quiere comerciar con usted. {0}"},
{"dialog_changeitem_tradeData","Quieren cambiar de {0} a {1}"},
{"dialog_changeitem_ok","Ok. Permite cambiar."},
{"dialog_changeitem_no","No, gracias."},
{"dialog_changeitem_nothing","Usted no tiene nada para el comercio"},
{"dialog_armySectorEvent","En el Sector eventos:{0}"},
{"dialog_armyFrendly","Esta flota se ve amigable. {0}"},
{"dialog_armyBuyOut","Trate de comprar. [Coste :{0}]"},
{"dialog_armyStronger","Ves a los enemigos. Se parece más fuerte que usted. Vamos a luchar?  {0}"},
{"dialog_armyShallFight","Ves a los enemigos. Vamos a luchar?  {0}"},
{"dialog_armyNeutral","Esta flota no te ataque primero.  {0}"},
{"dialog_armyAskHelp","Pide ayuda. [Reputación:{0}]"},
{"dialog_armyRun","Runaway"},
{"dialog_armyRunComplete","Huyendo completa."},
{"dialog_armyRunFail","Fallar! Ahora debe luchar."},
{"dialog_armyBuyoutComplete","Compra completa. Usted pierde {0} créditos."},
{"dialog_Attack","Ataque"},
{"dialog_sectorClear","Nadie aquí. tal vez debería volver aquí más tarde"},
{"dialog_coreAttack","Ataque."},
{"dialog_coreTargetProtect","Diana está bajo protección."},
{"dialog_coreBuy","Comprar para {0} créditos."},
{"dialog_coreUseDiplomacy","El uso de la diplomacia."},
{"dialog_coreSendScouts","Enviar exploradores a robar."},
{"dialog_coreFleetHave","Algunos otros de la flota ya tiene su destino.  {0}"},
{"dialog_coreFleetHaveFriend","Amistoso de la flota ya encontrar su destino. Usted puede tratar de utilizar la diplomacia. O simplemente comprar. {0}"},
{"dialog_coreWasPurchase","Elemento fue comprado. {0}/{1}"},
{"dialog_coreElementYour","Elemento es el tuyo. {0}/{1}"},
{"dialog_coreFight","Muy malo. Lucha."},
{"dialog_coreFailSteal","Error. Mientras estaba tratando de robar un objeto, los refuerzos llegaron a ellos, y ahora usted no puede fugarse de la casa."},
{"dialog_corePartYours","Esta parte es tuyo ahora."},
{"dialog_coreDiplomacyFail","No quieren darle esta parte"},
{"dialog_hirePay","Pagar"},
{"dialog_hireAttack","Usted no paga. En lugar de ello, sólo quieren matar a todos ellos."},
{"dialog_hireEnter","Espacio de base dentro de la gran asteroide. Han impresionante de protección. Entrar no es libre. Pagar {0} para entrar"},
{"dialog_hireSomebody","Usted puede tratar de contratar a alguien aquí."},
{"dialog_hireMax","Usted tiene el máximo tamaño de la flota."},
{"dialog_hireComplete","Alquiler completo"},
{"Prisoner","Preso"},
{"dialog_prisonerStart","Penal intentar escapa de la {0} de la policía. Pero su flota no puede atraparlo"},
{"dialog_prisonerBuy","Comprar artículo robado. [Coste:{0}]"},
{"dialog_prisonerCatch","Capturar y devolver a la policía."},
{"dialog_prisonerHire","Alquiler de él"},
{"dialog_prisonerHide","Ocultar de la policía. [Reputación:{0}]"},
{"dialog_prisonerHired","Penal contratado. Reputación eliminado {0}"},
{"dialog_prisonerYourItem","Su elemento: {0}"},
{"dialog_prisonerNoSpace","No espacio libre para el elemento"},
{"dialog_prisonerComplete","Completa. {0}"},
{"dialog_prisonerHideOk","Correctamente ocultar los criminales de la nave. Créditos agregar {0}"},
{"dialog_prisonerFailFight","Fallar! Ahora usted lucha con la policía."},
{"dialog_prisonerCatchOk","Usted logra atraparlo. Reputación añadido"},
{"dialog_prisonerBuyFail","Usted no tiene suficiente dinero. Penal sólo volar"},
{"ScienceLaboratory","El laboratorio de ciencias"},
{"dialog_scLabStart","Usted está cerca de la {0} laboratorio de ciencias. Pero este está bajo asedio."},
{"dialog_scLabAttackNow","Ataque de inmediato"},
{"dialog_scLabContact","Póngase en contacto con el comandante de la flota"},
{"dialog_scLabSedScouts","Enviar exploradores para laboratorio"},
{"dialog_scLabFrighten","Tratar de asustarlos."},
{"dialog_scLabBetterContact","No, mejor me contacto con ellos."},
{"dialog_scLabNotRegular","Esto no es un ejército regular. Podemos tratar de asustar."},
{"dialog_scLabGoStation","Ir a la estación."},
{"dialog_scLabTheyRun","Ellos corriendo!."},
{"dialog_scLabFight","Lucha"},
{"dialog_scLabTotalFail","Fallar! Se acaba de lanzar cohetes al laboratorio y ahora quiere matar."},
{"dialog_scLabGiveCredits","Tal vez si sólo te dan algunos créditos y saldrá [Créditos:{0}]"},
{"dialog_scLabSimpleThiefs","Se ven como simples ladrones."},
{"dialog_scLabTheLeave","Que salir."},
{"dialog_scLabBadJoke","Broma de mal gusto! [No es suficiente créditos]"},
{"dialog_scLabAllKilled","Todos los científicos fueron asesinados."},
{"dialog_scLabImproveMain","Mejorar la nave principal."},
{"dialog_scLabImproveBattle","Mejorar barcos de batalla."},
{"dialog_scLabScientsChoose","Los científicos están vivos. Y que pueden mejorar su ejército"},
{"dialog_scLabShipUpgraded","{0} actualización en el barco {1} Actualizado."},
{"dialog_scLabAllMax","Todas sus naves han de máximo nivel."},
{"dialog_scParamUpgraded","{0} Actualizado"},
{"dialog_scLabNotingUpgrade","Nada para mejorar."},
{"dialog_secretStart","Una gran cantidad de basura espacial y otra cosa inútil aquí. ¿Quieres investigar?"},
{"dialog_secretSendScouts","Enviar scouts"},
{"dialog_secretHideWait","Esconderse y esperar"},
{"dialog_secretSendFake","Enviar falsas de la señal"},
{"dialog_secretAttack","El ataque!"},
{"dialog_secretConnectWith","Conectar con el comandante."},
{"dialog_secretScoutResult","Scouts encontrar una enorme flota, esperando algo. [Scouts:{0}]"},
{"dialog_secretTryPrevent","Trate de evitar el conflicto"},
{"dialog_secretRun","Ejecutar"},
{"dialog_secretSeeHugeArmy","De repente se ve un enorme ejército. Y listo! [Scouts:{0}]"},
{"dialog_secretHaveCredits","Y ahora usted tiene [créditos de{0} y {1}]"},
{"dialog_secretYouRun","Te escapas. {0} [Scouts:{1}]"},
{"dialog_secretFight","Lucha"},
{"dialog_secretRunFail","Huir no! [Scouts:{0}]"},
{"dialog_secretApplyDeal","Aplicar tratar"},
{"dialog_secretLeave","Dejar"},
{"dialog_secretTheyMessage","Se enviará un mensaje con las opciones de comercio."},
{"dialog_secretTheyGoKill","Ahora que la iba a matar. La diplomacia no es su lado bueno."},
{"dialog_secretPartGo","Parte de la flota de ir a la verificación de la señal."},
{"dialog_secretDoProvocation","¿Provocación."},
{"dialog_secretWait","Esperar."},
{"dialog_secretSecondCome","{0}s ejército."},
{"dialog_secretSearchPlace","Búsqueda de lugar."},
{"dialog_secretTheyEnd","Se completa el comercio, y listo para saltar."},
{"dialog_secretTake","Tomar. [Créditos:{0}]"},
{"dialog_secretForgotCredits","Parece que se olvidó de algunos créditos."},
{"dialog_secretTakeAll","Tomar todas y ejecutar."},
{"dialog_secretAppearSecond","Mientras que el comercio, aparece otra flota."},
{"dialog_secretFindGoods","Después de la gran batalla de encontrar algunos de sus productos. [Créditos:{0}]"},
{"dialog_secretProvoceFail","Su provocación fallado. Ahora lucha."},
{"dialog_finalStartReady","Este es su principal objetivo. Usted tiene {0}/{1} partes para abrir puertas. Usted está listo para ir."},
{"dialog_finalStartNotReady","Este es su principal objetivo. Usted tiene {0}/{1} partes para abrir puertas.Ahora usted debe adquirir todos los demás. Solo una manera de hacerlo es enviar a uno de sus barcos para bloquear la energía en las puertas.  Pero usted no tiene suficiente barco  Su muerto."},
{"dialog_finalProcess","Este es su principal objetivo. Usted tiene {0}/{1} partes para abrir puertas. Ahora usted debe adquirir todos los demás. Solo una manera de hacerlo es enviar a uno de sus barcos para bloquear la energía en las puertas. "},
{"dialog_finalStartFight","Pero alguien no quiere dejarte ir y te ataca"},
{"dialog_finalEnd","Ahora el camino está libre y usted puede ir a lo que usted desea."},
{"dialog_afterBattleStart","Después de una batalla de la nave enemiga están vivos."},
{"dialog_afterBattleBuyout","Pide bayout, tal vez de enviar algunos créditos para usted"},
{"dialog_afterBattleTeachPilots","Ciencias de la nave puede enseñar a algunos de sus pilotos"},
{"dialog_afterBattleUpgradeSpell","Ciencias de la nave puede intentar ti actualizar su nave principal"},
{"dialog_afterBattleOpenCells","Desbloquear el sistema de navegación de scouts de todo el sector"},
{"dialog_afterBattleHireAction","Alquiler de ellos"},
{"dialog_afterBattleSearchFor","Búsqueda de dinero o artículos"},
{"dialog_afterBattleKillAction","Matar a ellos y todos los bienes"},
{"dialog_afterBattleRepairAction","Reparación de él y salir de él"},
{"dialog_afterBattleTeachOk","{0} actualizado"},
{"dialog_afterBattleUpgradeSpellOk","Big gun actualizado {0}"},
{"dialog_afterBattleUpgradeSpellFail","Nada de actualizar"},
{"dialog_afterBattleCellOpen","Todos los sectores de la célula explorado"},
{"dialog_afterBattleBuyoutConfirm","Compra confirmar créditos:{0}"},
{"dialog_afterBattleBuyoutFail","Compra fallar"},
{"dialog_afterBattleSearchOk","Créditos agregar: {0}."},
{"dialog_afterBattleSearchFail","Nada."},
{"dialog_afterBattleKillOk","El dinero no huele. {0}"},
{"dialog_afterBattleKillFail","Él corriendo."},
{"dialog_afterBattleHireOk","Usted contrató a un nuevo piloto. Tipo:{0} Config:{1}"},
{"dialog_afterBattleRepairOk","Reparación completa de la reputación agregar"},
{"dialog_afterBattleRepairFail","Reparación de error."},
{"dialog_afterBattleMicrochip","Descompilar de la nave y tratar de encontrar microchip para las actualizaciones"},
{"dialog_afterBattleMircochipOk","Ok"},
{"dialog_afterBattleMircochipFail","Fallar"},
{"dialog_dungeonExitFinalWin","Esta base militar completamente destoyed"},
{"dialog_dungeonExitGo","Coge todos los elementos e ir"},
{"dialog_dungeonExitFinalBattle","Esta es la principal militaly base a este sector"},
{"dialog_dungeogArmyEnterStart","Este es el sector militar. ¿Realmente quieres ir allí?Los refuerzos llegarán de inmediato.Aquí usted puede encontrar algunos elementos especiales."},
{"dialog_dungeogArmyFriendGoIn","Pregúntele a su amigo para ir en."},
{"dialog_Trader","Comerciante"},
{"dialog_tradeStartSell","Él quiere vender {0} por {1} créditos."},
{"dialog_tradeStartBuy","Él quiere comprar su elemento {0} por {1} créditos."},
{"dialog_tradeStartOk","Ok. Permite el comercio."},
{"dialog_tradeStartNo","No, gracias."},
{"dialog_tradeStartWantTrade","Este barco se quiere comerciar con usted. {0}"},
{"dialog_Space garbage","El espacio basura"},
{"dialog_scGarbage","En frente de usted un gran recuento de basura."},
{"dialog_scNoWant","No quiero escarbar en la basura."},
{"dialog_scSearch","Búsqueda en la frontera. [Scouts:{0}]."},
{"dialog_scDive","Buceo profundo. [Scouts:{0}]"},
{"dialog_nothing","Nada"},
{"dialog_scAmbush","Emboscada!"},
{"dialog_scWeapon","Esta es la nueva arma de {0}"},
{"dialog_scScouted","{0} puntos en el mapa mundial explorado."},
{"dialog_scMap","Este es el galaxy mapa! {0}"},
{"dialog_teacherImproved","El Barco {0} Mejorado. Nivel piloto:{1}"},
{"dialog_teacherFail","Error."},
{"dialog_teacherStartPilots","Esta es la ciencia de la nave. Ellos pueden enseñar a algunos de sus pilotos [créditos:{0}]."},
{"dialog_teacherNo","No, gracias."},
{"dialog_Science ship","La ciencia de la nave"},
{"dialog_teacherStartSience","Esta es la ciencia de la nave. Se puede mejorar su flota [créditos:{0}]. ¿Quieres actualizar {1}?"},
{"Anomaly","Anomalía"},
{"dialog_anomalySendScouts","Enviar scouts y tratar de conseguir algo de información."},
{"dialog_anomalyBeliveMysielf","Yo creo en mí mismo. Acercarse a ella."},
{"dialog_anomalyGoAway","No. Vaya."},
{"dialog_anomalyStart","Usted encuentra una extraña anomalía. Parece que va a desaparecer pronto. ¿Quieres investigar?"},
{"dialog_anomalyFreeze","El uso de la congelación de la pistola"},
{"dialog_anomalyExplosive","El uso de explosivos"},
{"dialog_anomalyImpulse","El uso de impulso"},
{"dialog_anomalyFire","El uso de fuego"},
{"dialog_anomalyChange","Algo cambio."},
{"dialog_anomalyRight","Parece que hacer las cosas bien."},
{"dialog_anomalyWrong","Mal."},
{"dialog_anomalyNoInfo","No hay información de los scouts .Elija siguiente movimiento. Intenta permanecer:{0}."},
{"dialog_anomalyInfo","{0}{1}/{2} partes desbloqueado. Elija siguiente movimiento. Intenta permanecer:{3}."},
{"dialog_anomalyDeactivated","Con éxito desactivar anomalía. {0} de sus naves mejorado."},
{"dialog_anomalyNotDay","No es mi día."},
{"dialog_anomalyDestroyed","Anomalía desaparecido."},
{"battleSpells","El comandante de la nave opciones especiales.Cualquier disparo tomar algunas baterías durante un período.Usted debe tomar un momento para usarlos correctamente."},
{"battleStart","La batalla comienza.Todos sus buques elegir destino y ataque por sí mismo."},
{"battleEnemy","Los enemigos de la flota"},
{"battleYour","Su flota. Usted no puede controlar directamente.Sólo elige la táctica."},
{"battleMainShip","Usted puede controlar el comandante de la nave. Utilice el ratón para seleccionar y mover. Y el uso de la habilidad de teletransportarse a otro lugar"},
{"mapInsideInventory","Esta es su flota de página. Aquí puede cambiar el equipo de sus barcos, o hacer algunas mejoras."},
{"mapMain","Este es el mapa global.Usted sólo puede moverse a lugares cercanos. Para mover haga clic en el punto que usted desea ir."},
{"mapInventory","Haga clic aquí para elegir el equipo de su flota."},
{"mapFleetFast","Su flota. Usted no puede controlar directamente.Sólo elige la táctica."},
{"mapUpgrade","Uno de sus barcos puede ser actualizado."},
{"preBattle","La preparación para la batalla.Elegir el equipo adecuado contra el actual rival, basado en la información de los scouts"},
{"shopMain","Esta es la tienda de Aquí usted puede comprar o vender algo. Diferente en diferentes sectores de los costos diferentes de dinero. Tratamos de vender y comprar en derecho sectores"},
{"endBattle","Elija una forma de dividir los créditos de bonificación. Si quieres subir de nivel barcos de batalla elegir a los pilotos.\nSi usted quiere comprar armas o mejorar algo seleccione principal"},
{"TutorCloseForever","No mostrar este tip de nuevo"},
{"Tutorial","Tutorial"},
{"TutorMoveGlobal","Para mover la cámara utilice el ratón o WSAD"},
{"TutorHomeButton","Para encontrar su flota pulse el botón inicio"},
{"TutorDifferentTypesCells","Diferentes tipos de células que contiene diferentes eventos.Usted sólo puede moverse a la más cercana de las células.Elegir destino sabiamente"},
{"TutorDialog","En los cuadros de diálogo se puede elegir diferentes maneras."},
{"TutorMove","Haga clic en el botón derecho del ratón para mover el comandante de la nave.Lo hacen para encontrar una buena posición para disparar."},
{"TutorRecharge","Ayudar a sus naves con la recarga de escudo.Si uno de sus buques están dañados - ayudar a él."},
{"TutorMachineGun","Uso de la máquina de armas para destruir a los enemigos.Si usted tiene buenas posibilidades de que el daño enemigo usarlo."},
{"TutorEngineLock","Utilice el motor de armario para deshabilitar los enemigos.Usarlo para ayudar a los barcos de batalla golpear a los enemigos."},
{"TutorChangeTactics","Cambio de nave de batalla táctica.Si su barco si mejor contra los tipos especiales de enemigo usted puede cambiar la prioridad de los objetivos de la misma."},
{"ConfirmCloseTutor","Usted cierre tutorial.Si quieres repetir, usted lo puede encontrar en el menú."},

    };

}

