using System.Collections.Generic;


public static class RusLocalization
{
    public static Dictionary<string, string> _locals = new Dictionary<string, string>()
    {
//        {"StartInfo", "Вы находитесь на самом краю обитаемого мира в отдалённом секторе.\n" +
//                      "В результате спец операции вам пришлось похитить командный корабль и энергетический \n" +
//                      " элемент на нём. Теперь единственный выход собрать достаточное количество элементов," +
//                      "\n для открытия межпространственых врат, и доставить информацию для командования."},
        { "StartInfo", "Командование просит вас выполнить несколько заданий. Проверьте ваш журнал."},
        {"Yes", "Да"},
        {"No", "Нет"},
        {"Ok", "Ок"},
        {"Blocked","Заблокировано"},
        {"Fraction", "Фракция"},
        {"Crashed", "Уничтожен"},
        {"Size4", "Размер сектора 4"},
        {"Size5", "Размер сектора 5"},
        {"Size6", "Размер сектора 6"},
        {"Power", "Мощность"},
        {"MissionComplete", "Миссия завершена" },
        {"MissonFail", "миссия провалена" },
        {"battleTypeNormal", "Обычный сектор"},
        {"battleTypemilatary", "Военный сектор"},
        {"battleTypelongType", "Вытянутый сектор"},
        {"Galaxy", "Галактика" },
        {"unblockGalaxies", "Новые галактики открыты" },
        {"SandBox", "Песочница"},
        {"Failed", "Провал"},
        {"Play", "Играть"},
        {"New", "Новый"},
        {"Chooseprofile", "Выберите профиль"},
        {"EnterNameEtc", "Введите имя..."},
        {"Exproler", "Исследование"},
        {"CreateProfile", "Создать"},
        {"Size", "Размер" },
        {"Endless", "Иследование"},
        {"NotReady", "Еще не реализованно"},
        {"AreYouSureWAntRemoveProfile", "Вы уверенны что хотите удалить этот профиль навсегда?" },
        {"Count", "Количество"},
        {"Reflected", "Эффект отражен"},
        {"Chance", "Шанс"},
        {"questKidnappingBuyout", "Выкупить"},
        {"ClickToGetInfo", "Кликните для информации"},
        {"questKidnappingStageName", "Наш человек был похищен. Освободите его."},
        {"questKidnappingFinalName", "Похищение"},
        {"questKidnappingScoutsFine", "Разведка успешно освободила цель"},
        {"questKidnappingScoutsFail", "Разведчикам не удалось выполнить задачу"},
        {"questKidnappingScouts", "Использовать разведчику что бы освободить его."},
        {"AttackWithFail", "Атаковать. Шанс успеха {0}"},
        {"questKidnappingArmyKilled", "Флот уничтожен. Освобождаем."},
        {"questKidnappingDialogStart", "Они похители нашего человека. Вам нужно вернуть его. Они требуют деньги {1} или уничтожить флот {0}"},
        {"CriticalDamage", "Критические повреждения. Если повреждений будет больше {0} то корабль будет уничтожен"},
        {"Event", "Событие"},
        {"questKidnappingFinaldialog", "Вы вернули нашего человека! Хорошая работа."},
        {"fedQuest1Name", "Зачистить сектор"},
        {"questFedClearSectorFinal", "Сектор чист! Отличная работа."},
        {"RechargeSheildSpell", "Подзарядка щита на {0}%"},
        {"ArmorField", "Броня: {0}/{1}"},
        {"UnstableCore0", "Some of your ships can get damage cause your core is unstable.\n\n Find repair services to stabilize your core.\n\n If core stability level become less than -10 your fleet will be destroyed."},
        {"MapExit", "Вы действительно хотите выйти в главное меню?\nПрогресс будет сохранен и вы сможете продолжить позже."},
        {"CantByLevel", "Уровень корабля недостаточен что бы использовать это оборудование"},
        {"ReqireLevelFeild", "Требуемый уровень корабля:{0}"},
        {"CanCauseNoLevel", "Оружие невозможно улучшить так как уровень корабля недостаточен.\nУровень корабля:{0}. Целевой уровень:{1}"},
        {"RoundWaveStrike", "Наносит всем корабля вокруг урон: [{2}/{3}].\n[Затраты:{0}/{1}]"},
        {"And", "и"},
        {"SupportModul", "Оружейный модуль"},
        {"ActionModul", "Вспомогательный модуль."},
        {"CataclysmProcess", "{0} ячеек уничтожено"},
        {"RemainCataclysm", "Дней осталось:{0}"},
        {"VeryEasy", "Легчайше"},
        {"Easy", "Легко"},
        {"Normal", "Нормально"},
        {"Hard", "Тяжело"},
        {"Imposilbe", "Невозможно"},
        {"Radius", "Радиус"},
        {"Sector", "Сектор"},
        {"Reload", "Время перезарядки"},
        {"ShootPerTime", "Количество зарядов"},
        {"standartStatQuestComplete", "Базовое задание завершено. Выберите награду"},
        {"questStartDeliverDialog", "Доставьте вещи нашим флотам"},
        {"remainTime", "Осталось времени"},
        {"CamMoveSens", "Чувствительность камеры"},
        {"cantRemoveCauseSlots", "Перемещение заблокировано"},
        {"fireVortexEvent", "Огненные вихри"},
        {"VortexEvent", "Вакуумные области"},
        {"BlackHoleEvent", "Чёрные дыры"},
        {"IceZoneEvent", "Зоны заморозки"},
        {"nextWave", "Следущая волна"},
        {"deliverQuestName", "Доставка"},
        {"Protect", "Защищать"},
        {"Nothing", "Пусто"},
        {"Statistics", "Статистика"},
        {"questProtectNameBig", "Защитник"},
        {"questProtectFinalText", "Защита прошла успешно. Выберите награду"},
        {"Locked", "Недоступно"},
        {"questStartDeliverFindCoordinator", "Найдите координатора что бы узнать что и куда доставить"},
        {"questProtectFortressFind", "Узнайте место которое требует вашей защиты."},
        {"questReadyStartProtect", "Координаты места найдены"},
        {"questprotectFortressDialogStart", "Это место вам следует защищать"},
        {"questNameProtectStage", "Защитите место"},

        {"ParameterTypeScouts1", "Небольшая информация перед битвой"},
        {"ParameterTypeScouts2", "Направления передвижения флотов на глобальной карте"},
        {"ParameterTypeScouts3", "События в секторах"},
        {"ParameterTypeScouts4", "Разведывает ближайшие точки"},

        {"defenceWavesWin", "Вы успешно защитили сектор. И ваши друзья высылают вам кредитов:{0}" },
        {"destroyShipPeriodWin", "Корабль был уничтожен. Микро чипов найдено:{0}" },
        {"defenceOfShipWin", "Вы успешно защитили корабль. Ваш подарок:{0}" },
        {"noFreeSpace", "Нет места для подарка" },
        {"baseDefenceWin", "Успешно. После битвы станция подарила вам микрочиы: {0}" },
        {"defenceWavesFail", "Провал." },
        {"destroyShipPeriodFail", "Корабль сбежал" },
        {"defenceOfShipFail", "Корабль был уничтожен" },
        {"baseDefenceFail", "Провал." },


        {"cantUpgrade", "Невозможно улучшить"},
        {"UpgParams", "Вы действительно хотите улучшить {0}?\n Стоимость {1} кредитов."},
        {"CoreSector", "Целевой сектор"},
        {"NotCoreSector", "Обычный сектор"},
        {"StatisticDifficulty", "Сложность:{0}%."},
        {"StatisticConfig", "Флот:{0}."},
        {"StatisticMapSize", "Размер галактики:{0}."},
        {"StatisticFinalArmyPower", "Сила флота:{0}."},
        {"StatisticRecievedOpendPoints", "Очков заработано:{0}."},
        {"StatisticDate", "{0}"},
        {"Fight", "В бой"},
        {"StatisticNoResult", "Нет результатов"},
        {"StatisticNoLastResult", "Ожидание игры..."},
        {"StatisticLastResult", "Последний результат:"},
        {"Sacrifice", "Пожертвовать кораблем: {0}, {1}, {2}"},

        {"EndGameDays", "Дней:{0}"},
        {"BattleWinsStat", "Побед:{0}"},
        {"OpenWeaponsEndGame","Открыты новые типы вооружения {0} и {1}"},
        {"OpenConfigEndGame", "Новый флот доступен для игры: {0}"},
        {"FrontShieldActivate", "Щит активирован"},
        {"Crit", "Критический урон {0}!"},
        {"WinEnd", "Все хорошо, теперь вы вольны сами выбирать куда хотите направиться... ,а возможно и нет"},
        {"LoseEnd", "Ваш флот уничтожен."},
        {"RepairDroneSpell", "Запускает ремонтный дрон. Когда дрон подлетает к кораблю он начинает восстанавливать корпус. Восстановит {1}% корпуса."},

        {"Shield Locker", "Блокиратор щитов"},
        {"Auto shield", "Авто щит"},
        {"Shield regeneration", "Восстановление щитов"},
        {"Repair drone", "Ремонтный дрон"},
        {"Rocked catcher", "Уничтожитель ракет"},
        {"Deflector", "Отражатель"},
        {"Side strike", "Атака с фланга"},
        {"Engine locker", "Ломатель двигателей"},
        {"EMI mine", "Электромагнитная мина"},
        {"Power mine", "Силовая мина"},
        {"Fire mine", "Огненная мина"},
        {"Front shield", "Мега-щит"},
        {"Body armor", "Броня корпуса"},
        {"Teleportation", "Телепортация"},
        {"Laser power", "Мощность лазеров"},
        {"Rockets power", "Мощность ракет"},
        {"Bomb power", "Мощность роя"},
        {"EMI power", "Мощность ЭМИ"},
        {"Impulse power", "Мощность импульса"},
        {"Speed", "Скорость"},
        {"BaseCenter", "Штаб"},
        {"BaseEnter", "Военная база"},
        {"Turn Speed", "Скорость поворота"},
        {"Bullet speed", "Скорость зарядов"},
        {"Spray fire", "Веерный выстрел"},
        {"Longer dist", "Увлечение дистанции"},
        {"Pusher", "Толкатель"},
        {"Burner", "Поджигатель"},
        {"Stopper", "Останавливатель"},
        {"Locker", "Выключатель"},
        {"Critical", "Критические повреждения"},
        {"AOE", "Урон по области"},
        {"Wider", "Расширитель"},
        {"Close strike", "Урон в упор"},
        {"Chain strike", "Мульти цель"},
        {"Penetrating shot", "Проникающий выстрел"},
        {"Powerful recoil", "Мощная отдача"},
        {"Shield stealer", "Похититель щитов"},
        {"More bullets", "Больше зарядов"},
        {"Power shot", "Мощный выстрел"},
        {"Fire wave", "Волна огня"},
        {"Protector", "Защитник"},
        {"Beam upgrade", "Улучшение луча"},
        {"Heavy weapons", "Тяжелый орудия"},
        {"Maximum shield", "Максимум щитов"},
        {"scout", "Разведчики"},
        {"repair", "Служба ремонта"},
        {"chargesCount", "Количество батарей"},
        {"chargesSpeed", "Скорость зарядки батарей"},
        {"engineParameter", "Перемещатель"},

        {"MainShipBlinkDesc", "Перемещает корабль в указанную точку"},
        {"MainShipBlinkName", "Прыжок"},
        {"hookShot", "Магнитная волна"},

        {"Preparing", "Подготовка"},
        {"Return", "Возвращается"},
        {"Evade enemy", "Уворачивается"},
        {"RepairAction", "Починка"},
        {"Wait", "Ожидание"},
        {"Hiding", "Прячется"},

        {"Battle reward", "Награда за сражение:"},
        {"Fleet money", "Общие средства:"},

        {"armyCount", "Размер флота {0}"},
        {"armyCountBetween", "Размер флота от {0} до {1}"},
        {"armyWeaponsContains","Возможное вооружение {0}"},
        {"armyHaveMotherShip","Есть командный корабль"},
        {"armyJustFleet","Без командного корабля"},
        {"armyWeaponsCount","Количество вооружения:{0}. Количество модулей:{1}"},
        {"armyUsingWeapons","Используемое вооружение:{0}"},

        {"engineLock", "Поломщик"},
        {"lineShot", "Огненный залп"},
        {"throwAround", "Разбрасыватель"},
        {"vacuum", "Вакуум"},
        {"mineField", "Минное поле"},
        {"distShot", "Мощный выстрел"},
        {"artilleryPeriod", "Артиллерия"},
        {"repairDrones", "Ремонтный дрон"},
        {"rechargeShield", "Подзарядка щитов"},
        {"roundWave", "Урон вокруг"},
        {"machineGun", "Пулемёт"},
        {"WeaponShieldPerHit", "Вор"},

        {"WANT_UPGRADE_WEAPON","Вы хотите улучшить ваше орудие {0}?" },
        {"WeaponMaxLevel", "Орудие имеет максимальный уровень"},
        {"Processing", "Обработка..."},
        {"Win", "Победа!"},
        {"Lose", "Поражение"},
        {"RunAwayComplete","Вы успешно сбежали" },
        {"Type", "Тип"},

        {"trick_turn", "Резкий разворот для атаки противника."},
        {"trick_twist", "Быстрое смещение в сторону, что бы избежать атаки и нанести удар с фланга"},
        {"trick_loop", "Петля позволяет избежать атаки и запутать противника"},
        {"trick_frontStrike", "Таранный удар. Резко ускоряется и разбрасывает врагов."},

        {"trick_name_turn", "Поворот"},
        {"trick_name_twist", "Смещение"},
        {"trick_name_loop", "Петля"},
        {"trick_name_frontStrike", "Таран"},

        {"Regen", "Регенерация"},
        {"DamageBody", "Урон по корпусу"},
        {"DamageShield", "Урон по щитам"},
        {"HealBody", "Починка корпуса"},
        {"HealShield", "Зарядка щитов"},
        {"ChargesCount", "Количество зарядов {0}"},
        {"ChargesDelay", "Время перезарядки {0}"},
        {"Scouted", "Разведано"},
        {"Gate", "Врата"},
        {"Home", "Домой"},
        {"Complete", "Завершено {0}"},
        {"CompleteNodata", "Завершено"},
        {"Target", "Цель {0}"},
        {"Delay", "Задержка"},
        {"FlangAttack", "Атака с фланга"},
        {"questSearachFleetMercFinal", "Вы успешно уничтожили цель. Командование благодарит вас. Выберите награду"},

        {"DamageTimeEffectRepair", "Убирает все негативные эффекты"},
        {"shieldLocker",  "Отключает щиты у цели."},
        {"autoShieldRepair", "Восстанавливает щиты если они будут уничтожены."},
        {"shieldRegen", "Усиленное восстановление щитов."},
        {"autoRepair", "Чинит корпус при появлении значительных повреждений."},
        {"antiPhysical", "Уничтожает физические заряды в определенном радиусе."},
        {"antiEnergy","Уничтожает энергетические заряды в определенном радиусе." },
        {"closeStrike","Когда враг близко открывает огонь." },
        {"engineLocker","Выключает двигатель цели." },
        {"systemMines", "Устанавливает системные мины, которые отключают двигатель."},
        {"damageMines","Устанавливает мины которые наносят повреждения." },
        {"frontShield","Отражает все заряды на короткий промежуток времени." },
        {"armor", "Уменьшает повреждения по корпусу"},
        {"fireMines", "Устанавливает мины которые поджигают цели."},
        {"blink", "Перемещает корабль в различных ситуациях."},
        {"laserUpgrade", "Увеличивает урон всех лазеров на +1/+1 за уровень."},
        {"rocketUpgrade","Увеличивает урон всех ракет на +1/+1 за уровень." },
        {"EMIUpgrade", "Увеличивает урон всех эми на +1/+1 за уровень."},
        {"impulseUpgrade","Увеличивает урон всех импульсов на +1/+1 за уровень." },
        {"bombUpgrade","Увеличивает урон всех роев на +1/+1 за уровень." },
        {"WeaponSpeed", "Увеличивает скорость зарядов."},

        {"WeaponAOE", "Воздействует на все корабли в области {0}. Уменьшает урон на {1}%."},
        {"WeaponSector",  "Увеличивает сектор прицеливания на {0}% за уровень"},
        {"WeaponPowerShot", "Увеличивает время перезарядки на {0}%. Увеличивает урон на {1}%."},
        {"WeaponPowerShotSupport", "Увеличивает время перезарядки на {0}%. Увеличивает восстановление на {1}%."},
        {"WeaponShootPerTime", "Добавляет по 1 заряду в очередь. Уменьшает мощность орудий на {0}% "},
        {"WeaponLessDist", "Уменьшает радиус стрельбы на {0}%. Увеличивает урон на {1}%."},
        {"WeaponPushSupport", "Все внешние силы перестают действовать на корабль."},
        {"WeaponLessDistSupport", "Уменьшает радиус стрельбы на {0}%. Увеличивает восстановление на {1}%."},
        {"ShipTurnSpeed", "Увеличивает скорость поворота корабля на {0}%"},
        {"ShipSpeed", "Увеличивает максимальную скорость корабля на {0}%"},
        {"ShieldDouble", "Усиливает щиты на {0}% . Уменьшает прочность корпуса на {1}%"},
        {"ShipDecreaseSpeed", "Увеличивает мощность орудий на {0}%.  Уменьшает скорость корабля на {1}%"},
        {"WeaponIncreaseDamage", "Увеличивает урон на {0}% у всех орудий типа {1}."},
        {"WeaponNoBulletDeath", "Пуля не уничтожается при столкновении с препятствием. Увеличивает время перезарядки на {0}%."},
        {"WeaponShieldPerHitDesc", "Уменьшает мощность орудий на {0}%. Восстанавливает {1} щита за попадание."},
        {"IgnoreShieldLevel1", "Игнорирует щит. Уменьшает урон на  {0}%."},
        {"Ignore shield", "Игнорируется щит."},
        {"WeaponSelfDamage", "Добавляет +{0}/+{0} урона. При каждом выстреле наносит себе урон {1}/{1}"},
        {"WeaponSelfDamageSupport", "Добавляет a +{0}/+{0} к восстановлению. При каждом выстреле наносит себе урон {1}/{1}"},
        {"WeaponPush","Отталкивает цель при попадании"},
        {"WeaponCrit","С {0}% шансом наносит {1} дополнительного урона в корпус."},
        {"WeaponCritSupport","С {0}% шансом восстанавливает {1} единиц корпуса."},
        {"DamageTimeEffect","с шансом {0}% на {1:0} сек, при попадании."},
        {"DamageTimeEffectEngine","Отключает двигатели {0}"},
        {"DamageTimeEffectShield","Отключает щиты {0}"},
        {"DamageTimeEffectFire","Поджигает на {0}"},
        {"shildDamage",  "Глушилка"},
        {"wantUpgrade", "Улучшить {0}? Стоимость {1}"},
        {"wantUpgradeLong", "Улучшить {0}? Стоимость:{1}. Микрочипы:{2}"},
        {"WantChangeLang", "Перезапустите игру что бы обновить локализацию"},

        {"Start game", "Новая игра"},
        {"Randomize", "Случайно"},
        {"Resume", "Продолжить"},

        {"questKills", "{0} Убийств"},
        {"Fleet", "Флот"},
        {"RechargeButton","Подзарядка щитов.\nЗатраты[{0}/{1}]" },
        {"BuffButton", "Увеличивает характеристики корабля.\n[Затраты:{0}/{1}]"},
        {"PowerWeaponButton", "Увеличивает мощность орудий на следующий выстрел.\n[Затраты:{0}/{1}]"},
        {"CellScouted", "Координаты разведаны [{0},{1}]"},
        {"PriorityTarget", "Приоритетная цель"},
        {"BaitPriorityTarget","Приманка"},
        {"engineCrash","Двигатель отключен на {0:0} сек" },
        {"shieldCrash","Щиты отключены на {0:0} сек" },
        {"fireCrash", "Пожар начался! {0:0} сек"},
        {"winAgainst", "Победы против {0}"},
        {"damageByQuest", "Урон от {0}"},
        {"killLight","Уничтожить легкий кораблей" },
        {"killMed","Уничтожить средних кораблей" },
        {"killHeavy", "Уничтожить тяжелых кораблей"},
        {"mainShipKills", "Уничтожить командиром"},
        {"upgradeWeapons", "Улучшить оружия"},
        {"sellModuls", "Продать модулей"},
        {"PriorityTargetDesc", "Все ваши корабли буду стараться атаковать выбранную цель."},
        {"BaitPriorityTargetDesc","Все корабли врага будут атаковать приманку" },
        {"SpellModulChargers", "Требуется батарей: {0} на {1} сек."},
        {"ArtillerySpell","Обстреливает зону. Всего выстрелов {0}. Урон от каждого попадания:{2}/{1}." },
        {"EnerguLockSpell","Отключает двигатели всем кораблям противника в радиусе {1} на {0} сек." },
        {"LineSHotSpell","Выстрел 3 зарядами в заданном направлении. Базовый урон: {0}/{1}. Период горения {2} сек. Общий урон от огня:{3}" },
        {"MinesSpell","Устанавливает {0} мин на {1} сек в выбранную локацию. Урон от каждой мины: {2}/{3}" },
        {"ShieldOffSpell","Выключает щиты у кораблей в радиусе на {0} сек. И наносит {1} урона щитам." },
        {"TrowAroundSpell", "Create a shockwave witch throw around all ships in radius with power {0}. And shield damage {1}."},
        {"DescHookShotSpell", "Притягивает все в области к вашему командному кораблю и отключает двигатели на {0} сек"},
        {"KillUIPilotMini","Убийств: {0}" },
        {"KillUIPilot", "Убийств: {0}/{1}"},
        {"Remain","Осталось" },
        {"EngineDest", "Двигатель поврежден"},
        {"ShieldDest","Щит отключен" },
        {"FireDest", "Пожар на борту"},
        {"Shop", "Магазин"},
        {"SectorDungeon", "Военная база"},
        {"DoWantRetire","Вы хотите сбежать?" },
        {"NoSafeGame","Не сохраненных игр" },
        {"MaxLevel", "Максимальный"},
        {"RusLang", "Русский"},
        {"Loading", "Загрузка"},
        {"EngLang", "Английский"},
        {"EspLang", "Испанский"},
        {"ReloadToLoc", "Перезапустите игру что бы использовать выбранный язык"},
        {"SettingsWindow", "Настройки"},
        {"Microchips", "Микрочипы"},
        {"AddMicrochips", "Получено микрочипов {0}"},
        {"ArmyAdditionalPower", "Каждый ход вражеские флоты будут улучшаться."},
        {"Back", "Назад"},
        {"Battle", "Битва"},

        {"DamageInfoUI", "Урон: {0}/{1}" },
        {"KillsInfoUI", "Убийства: {0}"},
        {"ReputationChanges", "{2} Репутация изменена {0} => {1}."},
        {"ReputationData", "{0} репутация: {1}"},
        {"Credits", "Кредиты"},
        {"BulletSpeed", "Скорость"},
        {"SellItemCost", "Цена продажи"},
        {"ItemCost", "Ценность"},
        {"AutoSpellButton", "Авто Выстрел"},

        {"Turret", "Турель" },
        {"Destroyed", "Уничтожены" },
        {"Completed", "Завершено"},
        {"StartNewGameFieldSize", "Размер сектора"},
        {"StartNewGameCoresCount","Задачи" },
        {"StartNewGameSectorsCount", "Количество секторов"},

        {"EngineLockNameA1", "Радиус"},
        {"New quest", "Новое задание"},
        {"EngineLockNameB2", "Уменьшение времени"},
        {"EngineLockDescA1", "Увеличение радиуса действия на {0}"},
        {"EngineLockDescB2", "Уменьшение время перезарядки батарей на {0} сек"},

        {"ArtilleryNameA1", "Заряды"},
        {"ArtilleryNameB2", "Ускорение"},
        {"ArtilleryDescA1", "Увлечение количества зарядов на {0}"},
        {"ArtilleryDescB2", "Уменьшение периода между выстрелами на {0} сек"},

        {"DistShotNameA1", "Блок двигателя"},
        {"DistShotNameB2", "По площади"},
        {"DistShotDescA1", "Повреждает двигатель при попадании на {0} сек"},
        {"DistShotDescB2", "Наносит повреждения ближайшим противникам в радиусе {0}"},

        {"LineShotNameA1", "Проникающий"},
        {"LineShotNameB2", "Термит"},
        {"LineShotDescA1", "Заряд не умирает при попадании"},
        {"LineShotDescB2", "Увеличивает силу горения на {0}"},

        {"MachineGunNameA1", "Мульти выстрел"},
        {"MachineGunNameB2", "Больше зарядов"},
        {"MachineGunDescA1", "Так же выстреливает по всем ближайшим целям. Количество зарядов {0} по каждой цели"},
        {"MachineGunDescB2", "Больше зарядов в очереди. Количество зарядов {0}"},

        {"MinesSpellNameA1", "Поджог"},
        {"MinesSpellNameB2", "Взрыв"},
        {"MinesSpellDescA1", "Добавляет урон от огня на {0} сек"},
        {"MinesSpellDescB2", "Отключает двигатели на {0} сек"},

        {"RechargeSheildNameA1", "По области"},
        {"RechargeSheildNameB2", "Блокиратор"},
        {"RechargeSheildDescA1", "Так же накладывает эффекты на ближайшие корабли в радиусе {0}"},
        {"RechargeSheildDescB2", "На {0} сек накладывает на цель сопротивление ко всем эффектам"},

        {"RepairDroneNameA1", "Щит"},
        {"RepairDroneNameB2", "Апгрейд"},
        {"RepairDroneDescA1", "Восстанавливает щиты на {0}%"},
        {"RepairDroneDescB2", "На {0} сек увеличивает скорость"},

        {"ShieldOffNameA1", "Батарея"},
        {"ShieldOffNameB2", "Поджог"},
        {"ShieldOffDescA1", "Требует для использования меньше батарей"},
        {"ShieldOffDescB2", "Добавляет урон от огня на {0} сек"},

        {"TrowAroundNameA1", "Разрушитель"},
        {"TrowAroundNameB2", "Разрядка"},
        {"TrowAroundDescA1", "Отключает двигатели для попадании на {0} сек"},
        {"TrowAroundDescB2", "Разряжает всё оружие цели"},

        {"VacuumNameA1", "Радиус"},
        {"VacuumNameB2", "Батареи"},
        {"VacuumDescA1", "Увеличивает радиус поражения на {0}"},
        {"VacuumDescB2", "Уменьшает время перезарядки батарей на {0} сек"},

        {"HookShotNameA1", "Радиус"},
        {"HookShotNameB2", "Батареи"},
        {"HookShotDescA1", "Увеличивает радиус поражения на {0}"},
        {"HookShotDescB2", "Уменьшает время перезарядки батарей на {0} сек"},

        {"RaidersProCons", "Плюсы: Хорошая скорость. Много слотов для модулей. Есть броня.\nМинусы: Мало оружейных слотов."},
        {"FederationProCons", "Плюсы: Много слотов для оружия. Регенерация щитов.\nМинусы: Низкая скорость."},
        {"MercenaryProCons", "Плюсы: Усредненные.\nМинусы: Усредненные."},
        {"OcronsProCons", "Плюсы: Отличные корпуса. Много слотов для модулей.\nМинусы: Нет щитов."},
        {"KriosProCons", "Плюсы: Сильные щиты. Отличная регенерация щитов.\nМинусы: Низкое качество корпуса."},

        {"WeaponsStart","На начало компании ваши корабли будут иметь комплект вооружения: {0} или {1}."},

        {"Paramscout", "Разведка предоставляет информацию о флоте противника.\nИногда позволяет что то своровать."},
        {"Paramrepair", "Между битвами надо ремонтировать флот.\nЭта служба вам поможет."},
        {"ParamchargesCount", "Увеличивает количество батарей главного корабля."},
        {"ParamchargesSpeed","Увеличивает скорость зарядки батарей главного корабля."},
        {"ParamEngine","Улучшает двигатель. Увеличивает скорость и ускоряет перезарядку перемещателя."},

        {"asteroidsEvent", "Астероидный шторм"},
        {"shieldsOffEvent", "ЭМИ излучение"},

        {"Raiders", "Королевство"},
        {"Federation", "Федерация"},
        {"Mercenary", "Наёмники"},
        {"Ocrons", "Окроны"},
        {"Krios", "Криос"},
        {"Droids", "Дройды"},
        {"Light", "Лёгкие"},
        {"Medium", "Средние"},
        {"Heavy", "Тяжелые"},
        {"Base", "База"},
        {"ESideAttackStraight", "Атаковать как обычно"},
        {"ESideAttackFlangs", "Атака с флангов"},
        {"ESideAttackBaseDefence", "Атаковать только рядом с командным центром"},
        {"BaseDefenceYes", "Защита базы"},
        {"BaseDefenceNo", "Нет"},
        {"Upgrade", "Улучшить"},

        {"ECommanderPriority1Base","Атакует базу" },
        {"ECommanderPriority1Fast","Выбирать корабли для атаки с максимальной маневренностью"  },
        {"ECommanderPriority1Slow","Выбирать корабли для атаки с минимальной маневренностью"  },
        {"EGlobalTacticsFight", "Воевать"},
        {"EGlobalTacticsGoSafe", "Быть в укрытии"},

        {"ECommanderPriority1MinShield","Выбирать корабли для атаки с минимальным щитом" },
        {"ECommanderPriority1MinHealth","Выбирать корабли для атаки с минимальным уровнем корпуса"  },
        {"ECommanderPriority1MaxShield","Выбирать корабли для атаки с максимальным щитом"  },
        {"ECommanderPriority1MaxHealth","Выбирать корабли для атаки с максимальным уровнем корпуса"  },
        {"ECommanderPriority1Any", "Атаковать любые корабли"},
        {"ECommanderPriority1Light","Приоритет на лёгкие корабли" },
        {"ECommanderPriority1Mid","Приоритет на средние корабли" },
        {"ECommanderPriority1Heavy", "Приоритет на тяжелые корабли"},
        {"QuestReward", "Выберите одну награду"},
        {"Reputation", "Репутация"},
        {"Inventory", "Инвентарь"},
        {"ReputationElement", "Врагов:{0}"},
        {"Trickturn", "Быстрый поворот"},
        {"Trickloop", "Петля"},
        {"Tricktwist", "Бочка"},
        {"Settings", "Настройки"},
        {"Private", "Рядовой"},
        {"Lieutenant", "Лейтенант"},
        {"Achievements", "Достижения"},
        {"Captain", "Капитан"},
        {"Major", "Майор"},
        {"OpenNew", "Разблокировать"},
        {"FinalSector", "Галактические врата"},
        {"Attack", "Атака"},
        {"AttackHalfLoop", "Спец прием"},
        {"Evade", "Уворот"},
        {"Level", "Уровень"},
        {"NotEnoughtBattries", "Батареи не заряжены!"},
        {"reloadBoost", "Время перезарядки трюков:{0}"},
        {"PointsToOpen", "Очков для открытия стартовых опций:"},
        {"SpellMaxLevel", "Максимальный уровень: {0}"},
        {"NoMouseMove", "Мышь не двигает камеру."},

        {"descWinner", "Выиграйте 1 битву"},
        {"descCaptain", "Выиграйте 10 битв"},
        {"descMayor", "Выиграйте 100 битв"},
        {"descTeam five", "Соберите корабли всех фракций в одну армию"},
        {"descFighter", "Уничтожте 100 вражеских кораблей"},
        {"descDestroyer", "Уничтожте 1000 вражеских кораблей"},
        {"descAnnihilator", "Уничтожте 10000 вражеских кораблей"},
        {"descMerWin", "Выиграйте за немников"},
        {"descFedWin", "Выиграйте за федерацию"},
        {"descKriWin", "Выиграйте за криосов"},
        {"descOcrWin", "Выиграйте за окронов"},
        {"descRdrWin", "Выиграйте за королевство"},

        {"nameWinner", "Победитель"},
        {"nameCaptain", "Капитан"},
        {"nameMayor", "Майор"},
        {"nameTeam five", "Полный сбор"},
        {"nameFighter", "Боец"},
        {"nameDestroyer", "Уничтожитель"},
        {"nameAnnihilator", "Анигилятор"},
        {"nameMerWin", "Главарь"},
        {"nameFedWin", "Канцлер"},
        {"nameKriWin", "Экспериментатор"},
        {"nameOcrWin", "Фанатик"},
        {"nameRdrWin", "Король"},


        {"ShipsRepaired", "Ships Repaired"},
        {"ResistDamages","Отражает все негативные эффекты"},

        {"MercGlobal", "Убежище наемников"},
        {"NotEnoughtMoney", "Недостаточно денег"},
        {"NotEnoughtMoneyLong", "Недостаточно денег {0}."},
        {"NotEnoughtUpgrades", "Недостаточно микрочипов для улучшения {0}."},
        {"leave", "Уйти"},
        {"HireMerc", "Нанять {1} {0}. Уровень:{2}. Стоимость:{3} кредитов."},
        {"Take", "Взять"},
        {"BrokenItem", "Вещь сломана {0}"},
        {"StabilizaInfo", "Уровень стабилизации:{0}"},
        {"MainElements", "Энергетических элементов"},

        {"ReinforcmentsCallNo", "Нет подкреплений"},
        {"ReinforcmentsCallConfig", "Вызвать подкрепление:{0}"},
        {"ReinforcmentsCalled", "Подкрепление недоступно"},
        {"Retreat", "Сбежать"},

        {"MaxArmyCount", "Размер флота:{0}/{1}"},
        {"Health", "Корпус"},
        {"Shield", "Щит"},
        {"TurnSpeed", "Поворот"},
        {"Unknown", "Неизвестно"},
        {"NewGame", "Новая игра"},
        {"Continue", "Продолжить"},
        {"Exit", "Выход"},
        {"ScoutsFind", "Разведчики нашли что то!"},
        {"Start point", "Начало"},

        {"Laser", "Лазер"},
        {"Rocket", "Ракеты"},
        {"Impulse", "Импульс"},
        {"Swarm", "Рой"},
        {"EMI", "ЭМИ"},
        {"Beam", "Луч"},
        {"MovingArmy", "Спец флот {1}\nСтатус:{2}. Мощь:{3}"},
        {"SimpleMovingArmy", "Флот {1}\nСтатус:{2}. Мощь:{3}"},
        {"MovingArmyBorn", "Спец флот {0} появился. Координаты:{1}"},
        {"AdditionalPower", "Улучшения флотов"},

        {"AddCredits", "Добавлено кредитов:{0}"},
        {"Comparable", "Сопоставим"},
        {"Risky", "Рискованно"},
        {"Easily", "Легко"},
        {"confirmDismiss", "Вы действительно хотите удалить корабль {0}?"},
        {"MovingArmyName", "Спец флот {0}"},
        {"RelocateTo", "Переместился в:{0}"},

        {"healBodySupport",  "Рем. дрон"},
        {"healShieldSupport",  "Энерг. дрон"},

        {"wantSell","Вы хотите продать за {0}?"},
        {"wantBuyItem","Вы хотите купить за {0}?"},

        {"valuable goods","Ценные товары"},
        {"invaluable goods","Не ценные товары"},

        {"Demo", "Это демо версия игры. Пока что мы не готовы показать вам больше. Максимальное количество посещенных секторов:{0}. Максимум ходов:{1}"},

        {"RecievePoints", "Вы будите получать очки за победы. Количество зависит от сложности. Также можно получить очки выигрывая битвы."},
        {"AA_FXAA", "Сглаживание"},
        {"Sound", "Звук"},
        {"battlefield", "Поле боя"},
        {"Amry","Армия"},
        {"Trader","Торговец"},
        {"BrokenNavigation", "Заблудившийся"},
        {"modifBaseStart", "Это станция модификаций. Вы можете попытаться модифицировать ваше оборудование."},
        {"modifCellName", "Станция улучшения"},

        {"scout_shipType", "Нет информации о типах кораблей"},
        {"scout_weapons", "Нет информации об оружии"},
        {"scout_level", "Нет информации об уровни кораблей"},
        {"scout_moduls", "Нет информации о модулях"},
        {"scout_spells", "Нет информации о спец оружии"},
        {"targteFar", "Цель слишком далеко"},
        {"CantDropNow", "Вы не можете продавать сейчас."},

        {"DescVacuumSpell", "Создает вакуум в указанной точке и затягивает туда. Сила:{0}. Урон по щитам:{1}"},
        {"ChainModulDesc", "Выстреливает по всем целям поблизости. Уменьшает урон на {0}%"},
        {"FireNearModulDesc", "Поджигает врагов рядом при выстреле на {0} сек."},
        {"SprayModulDesc", "Выстреливает {0} зарядами вместо одного. Увеличивает время перезарядки на {1}%."},
        {"WeaponSpeedModulDesc", "Увеличивает скорость зарядов на {0}% за уровень"},
        {"DescWeaponDistModul", "Увеличивает радиус прицеливания на {0}% за уровень"},
        {"WeaponEngine", "Выключает двигатели противника на некоторое время"},

        {"HirePilot","Пилот нанят. Тип:{0} Конфигурация:{1}"},
        {"All to me", "Флоту"},
        {"Equal", "Поровну"},
        {"All to ship", "Боевым кораблям"},
        {"To Map", "На карту"},

        {"MachineGunSpellDesc", "Серия из {0} быстрых зарядов. Урон: {1}/{2}"},
        {"DistShotSpell", "Один заряд. Урон только по корпусу {0}."},
        {"DistShotSpellSpecial", "Один заряд. Урон только по корпусу {0}. Если у цели нет щитов отключает двигатель на {1} сек."},

        {"rep_adv_friend", "Вы союзники. Возможно вам даже помогут."},
        {"rep_adv_neutral", "Вам придется сражаться с флотами, но можно и торговать."},
        {"rep_adv_negative", "Вы все еще можете торговать но цены вас не порадуют"},
        {"rep_adv_enemy", "Торговать запрещено. только битвы! Спец силы будут преследовать вас."},
        {"rep_friend", "Союзники"},
        {"rep_neutral", "Нейтральное"},
        {"rep_negative", "Негативное"},
        {"rep_enemy", "Враг"},
        {"DemoStart", "Ранний доступ\nЭто не финальная версия игры\nПочта: Kinderril@gmail.com"},
        {"DemoStart2", "You will have only 25 turns. And some mechanics will be blocked."},
        {"RepairCompete","Ремонт выполнен"},
        {"RepairStation","Станция тех. обслуживания."},

        {"dialog_Ok", "Ок"},
        {"dialog_MovingArmyStart", "Вы встретились со спец силами и окружены."},

        {"dialog_MovingArmyFight", "В битву"},
        {"dialog_MovingArmyWin", "Спец силы уничтожены."},
        {"dialog_MovingArmyGerReward", "Покинуть место."},

        {"dialog_shopEnemy", "Перед вами магазин. С вами никто торговать не будет. Вы враг." },
        {"dialog_shopTrade", "Перед вами магазин. Хотите обменяться товарами?" },
        {"dialog_repairEnemy", "Это ремонтная станция. Они не будут помогать вам." },
        {"dialog_nothingToRepair", "Это ремонтная станция. Ваш флот не нуждается в ремонте." },
        {"dialog_repairStart", "Это ремонтная станция. Здесь мы можем отремонтировать свой флот." },
        {"dialog_fixCrit", "Починить все критические повреждения. Стоимость:{0}." },
        {"dialog_repairCritFixed", "Критические повреждения устранены" },
        {"dialog_repairAll", "Починить всё.{0} кредитов" },
        {"dialog_repairNotEnough", "Не хватает кредитов" },

        //DILOGS ASTEROIDS
        {"dialog_asteroid_nothingComplete", "Все отлично. Вы можете продолжать двигаться" },
        {"dialog_asteroid_nothingCompleteRepair","Некоторые корабли повреждены и требуют ремонта. Вы можете продолжать двигаться" },
        {"dialog_asteroid_start", "Большое астероидное поле. Вам нужно неким образом пробраться на другую сторону." },
        {"dialog_asteroid_fireAll","Открыть огонь из всех орудий" },
        {"dialog_asteroid_slow","Медленно продвигаться через поле." },
        {"dialog_asteroid_brokenShip","Вы видите поврежденный корабль {0}." },
        {"dialog_asteroid_brokenShipRepair", "Попытаться отремонтировать его [Ремонтная служба:{0}]."},
        {"dialog_asteroid_brokenShipdecompile","Переработать его на детали для продажи." },
        {"dialog_repairResultFull", "Этот корабль не может быть полностью отремонтирован, но кое какие детали вы можете забрать. {0}"},
        {"dialog_repairResultCant", "Этот корабль не может быть полностью отремонтирован, но у вас нет места для неповрежденных деталей."},
        {"dialog_asteroid_weaponsFire","Выстрелы ракетами легко расчищают вам путь." },
        {"dialog_asteroid_weaponsFail", "Ваши орудия не обладают достаточной мощью что бы открыть путь. Некоторые корабли повреждены"},
        {"dialog_asteroid_haveWay", "Наконец то вы нашли выход! Некоторые корабли повреждены"},
              
        //DILOGS BATTLEFIELD
        {"dialog_battlefield_start","Вы видите 2 флота {0} в боквой готовности друг напротив друга " },
        {"dialog_battlefield_provocate", "Спрятаться и спровоцировать их бой"},
        {"dialog_battlefield_reconcile","Постараться примирить стороны" },
        {"dialog_battlefield_thanks","Спасибо!" },
        {"dialog_battlefield_diplomacyWin", "Ваша дипломатия была превосходна. Они не собираются сражаться и высылают вам подарок. Репутация добавлена {0}."},
        {"dialog_battlefield_run","Бежать!" },
        {"dialog_battlefield_shoot","Выстрелить рядом!" },
        {"dialog_battlefield_diplomacyFail","Ваша дипломатическая попытка провалилась. И теперь они решили убить вас." },
        {"dialog_battlefield_shit", "Неудачно."},
        {"dialog_battlefield_theyAttack","Это явно не ваш день. Приготовиться к обороне!" },
        {"dialog_battlefield_ufff", "Уффф... Великолепно."},
        {"dialog_battlefield_stopAttack","Они не обращая внимания друг на друга убегают. Возможно это не так уж и плохо, по крайней мере сегодня вы спасли немного жизней." },
        {"dialog_battlefield_youRun", "Вы сбежали"},
        {"dialog_battlefield_artillery","Подловить момент и открыть артилерийский огонь" },
        {"dialog_battlefield_wait","Ждать" },
        {"dialog_battlefield_theyBattle","Они начали сражение." },
        {"dialog_battlefield_killEachOther", "Сражение окончилось. Они успешно перебили друг друга. Но зато вы смогли найти немного кредитов на поле боя {0}."},
        {"dialog_battlefield_isee", "Да"},
        {"dialog_battlefield_battleHaveWinner", "Битва закончилась.Победившая сторона забрала трофеи и улетела."},
        {"dialog_battlefield_good","Хорошо" },
        {"dialog_battlefield_goodSHot", "Отличный выстрел. Вы всех уничтожили. После битвы вам удалось найти немного вещей."},
        {"dialog_battlefield_fight","Сражаться" },
        {"dialog_battlefield_killYou","Теперь они хотят уничтожить вас." },

        //DIALOG_BROKEN_NAVIGATION
        {"dialog_navigation_start","Вы поймали сигнал о помощи" },
        {"dialog_navigation_closer","Приблизиться" },
        {"dialog_navigation_trap", "Ловушка!"},
        {"dialog_navigation_fight", "В битву"},
        {"dialog_navigation_askHelp","Вы видите корабль {0} с поломанной навигационной системой. О просит вас о помощи" },
        {"dialog_navigation_shelter","Послать вашего разведчика что бы он помог ему добраться до убежища. [Разведка: {0}]" },
        {"dialog_navigation_repair","Попытаться починить его навигационную систему. [Ремонт: {0}]" },
        {"dialog_navigation_gift", "Ваша награда: {0}"},
        {"dialog_navigation_noFree", "Нет места для награды"},
        {"dialog_navigation_scouted", "{0} мест открыто на карте."},
        {"dialog_navigation_shelterOk","Вы успешно проводили его в укрытие. {0}." },
        {"dialog_navigation_repairOk","Вы успешно починили корабль. Репутация добавлена." },
        {"dialog_navigation_tryHire", "Предложить присоедениться"},
        {"dialog_navigation_takeMoney","Взять деньги" },
        {"dialog_navigation_hired","Корабль нанят {0}." },
                            
        //DIALOG_CHANGE_ITEM
        {"dialog_changeitem_start","Этот корабль желает торговать с вами. {0}" },
        {"dialog_changeitem_tradeData","\nОни предлагают поменять {0} на {1}" },
        {"dialog_changeitem_ok","Хорошо. Меняемся." },
        {"dialog_changeitem_no","Нет, спасибо." },
        {"dialog_changeitem_nothing","У вас нет ничего, что было бы им интересно" },
        {"dialog_sectorClear","Здесь пусто. Возможно вам стоит вернуться позже." },

        {"dialog_armySectorEvent","Событие:{0}\n" },
        {"dialog_armyFrendly", "Этот флот выглядит дружелюбно.\n {0}"},
        {"dialog_armyBuyOut","Попытаться откупиться. [Стоимость :{0}]" },
        {"dialog_armyStronger", "Вы видите враждебно настроенный флот. Они явно сильнее чем вы. Будем драться?"},
        {"dialog_armyShallFight","Вы видите враждебно настроенный флот. Будем драться?" },
        {"dialog_armyNeutral", "Этот явно флот не собирается вас атаковать первыми." },
        {"dialog_armyAskHelp",  "Попросить о помощи. [Репутация:{0}]"},
        {"dialog_armyRun","Убежать" },
        {"dialog_armyRunComplete","Вы сбежали." },
        {"dialog_armyRunFail", "Неудачно! Теперь придется драться."},
        {"dialog_armyBuyoutComplete","Вы откупились. Потеряно {0} кредитов." },
        {"dialog_Attack","Атаковать" },
        {"TeachPilot", "Обучить: {0} {1}"},
        {"mercQuest1Name", "Найти и уничтожить"},
        {"Quests", "Задания"},

        {"defenceWavesStart", "Несколько небольших флотилий собираються в этой секторе" },
        {"destroyShipPeriodStart", "Похоже что у этого корабля найдется что то полезное для нас. Уничтожьте его до того как он сбежит" },
        {"defenceOfShipStart", "Несколько кораблей преследуют корабль без вооружения" },
        {"baseDefenceStart", "Эта станция скоро будет атакована. Мы можем постараться защитить её." },

        {"dialog_coreAttack","Атаковать." },
        {"dialog_coreTargetProtect","Цель находится под защитой." },
        {"dialog_coreBuy","Выкупить за {0} кредитов." },
        {"dialog_coreUseDiplomacy","Попытаться договориться." },
        {"dialog_coreSendScouts","Выслать разведку, что бы они выкрали цель." },
        {"dialog_coreFleetHave","Этот флот нашел первыми вашу цель. \n {0}" },
        {"dialog_coreFleetHaveFriend","Дружественный флот уже нашел ваше цель. Можете попытаться договориться. Или выкупить.\n {0}" },
        {"dialog_coreWasPurchase","Вы приобрели это. {0}/{1}" },
        {"dialog_coreElementYour","Элемент у вас. {0}/{1}" },
        {"dialog_coreFight","Плохо. пора драться." },
        {"dialog_coreFailSteal","Неудачно. Пока вы ждали ваших разведчиков к ним подошло подкрепление и теперь вы не можете сбежать." },
        {"dialog_corePartYours", "Цель теперь у вас."},
        {"dialog_coreDiplomacyFail", "Они не хотят отдавать вам элемент"},

        {"dialog_Trader","Торговец"},
        {"dialog_tradeStartSell","Они хотят вам продать {0} за {1} кредитов."},
        {"dialog_tradeStartBuy","У вас хотят выкупить {0} за {1} кредитов."},
        {"dialog_tradeStartOk","Ок."},
        {"dialog_tradeStartNo","Нет."},
        {"dialog_tradeStartWantTrade","Этот корабль хочет поторговать с вами {0}."},

        {"dialog_Space garbage", "Свалка мусора"},
        {"dialog_scGarbage", "Прямо перед вами огромное облако мусора."},
        {"dialog_scNoWant", "Я не хочу копаться в мусоре."},
        {"dialog_scSearch", "Обыскать границы. [Разведка:{0}]."},
        {"dialog_scDive", "Искать в глубине. [Разведка:{0}]"},
        {"dialog_nothing", "Пусто"},
        {"dialog_scAmbush", "Засада!"},
        {"dialog_scWeapon", "Новое оружие {0}"},
        {"dialog_scScouted", "{0} ячеек открыто."},
        {"dialog_scMap", "Это карта области! {0}"},

        {"dialog_hirePay", "Заплатить"},
        {"dialog_hireAttack", "Не платить. Атаковать в лоб."},
        {"dialog_hireEnter","Огромная база построенная на астероиде. Обладает впечатляющей обороной. \nВход платный. Заплатить {0} за вход" },
        {"dialog_hireSomebody","Вы можете попытаться нанять здесь корабли." },
        {"dialog_hireMax","Ваш флот максимального размера." },
        {"dialog_hireComplete","Нанят." },

        {"Prisoner","Сбежавший"},
        {"dialog_prisonerStart","Кто то пытается спастись от полиции {0}. Вы можете поймать его"},
        {"dialog_prisonerBuy","Купить украденную вещь. [Стоимость:{0}]"},
        {"dialog_prisonerCatch","Поймать его и отдать полиции."},
        {"dialog_prisonerHire","Нанять его"},
        {"dialog_prisonerHide","Спрятать его от полиции. [Репутация:{0}]"},
        {"dialog_prisonerHired","Преступник нанят. Репутация уменьшена {0}"},
        {"dialog_prisonerYourItem","{0}"},
        {"dialog_prisonerNoSpace","Нет места для покупки"},
        {"dialog_prisonerComplete","Завершено. {0}"},
        {"dialog_prisonerHideOk","Вы удачно спрятали преступника. Кредитов поручено {0}"},
        {"dialog_prisonerFailFight","Неудачно! теперь придётся сражаться с преследователями."},
        {"dialog_prisonerCatchOk","Вы успешно поймали его. Репутация добавлена"},
        {"dialog_prisonerBuyFail","У вас нет достаточно денег."},

        {"ScienceLaboratory","Научная лаборатория"},
        {"dialog_scLabStart","Вы приближаетесь к научной лаборатории {0}. К сожалению она в осаде."},
        {"dialog_scLabAttackNow","Атаковать немедленно"},
        {"dialog_scLabContact","Связаться с командиром осаждающих"},
        {"dialog_scLabSedScouts","Выслать разведчиком что бы подробнее узнать о ситуации"},
        {"dialog_scLabFrighten","Попытаться запугать их."},
        {"dialog_scLabBetterContact","Нет, лучше выйти на связь."},
        {"dialog_scLabNotRegular","Не не регулярные войска. Мы можем попробовать запугать их."},
        {"dialog_scLabGoStation","Направиться к станции."},
        {"dialog_scLabTheyRun","Они бегут!"},
        {"dialog_scLabFight","В битву"},
        {"dialog_scLabTotalFail","Неудачно! Они запустили ракеты в лабораторию и теперь собираться приняться за вас."},
        {"dialog_scLabGiveCredits","Скорее всего они просто хотят денег. Возможно, если им заплатить они уйдут [Кредиты:{0}]"},
        {"dialog_scLabSimpleThiefs","Они выглядят как обычное отребье."},
        {"dialog_scLabTheLeave","Они уходят."},
        {"dialog_scLabBadJoke","Неудачная шутка! [Недостаточно кредитов]"},
        {"dialog_scLabAllKilled","Все ученые были убиты."},
        {"dialog_scLabImproveMain","Улучшить главный корабль."},
        {"dialog_scLabImproveBattle","Улучшить боевые корабли."},
        {"dialog_scLabScientsChoose","Ученые выжили. И они могут помочь вам в модернизации вашего флота"},
        {"dialog_scLabShipUpgraded","У корабля {1} улучшено: {0}."},
        {"dialog_scLabAllMax","У всех ваших кораблей максимальный уровень."},
        {"dialog_scParamUpgraded","{0} Улучшено"},
        {"dialog_scLabNotingUpgrade","Нечего улучшать."},

        {"dialog_secretStart","Куча бесполезного мусора и прочего хлама находится тут, возможно стоит исследовать местность."},
        {"dialog_secretSendScouts","Выслать разведку"},
        {"dialog_secretHideWait","Спрятаться и ждать"},
        {"dialog_secretSendFake","Послать ложный сигнал"},
        {"dialog_secretAttack","Атаковать!"},
        {"dialog_secretConnectWith","Связаться с командиром."},
        {"dialog_secretScoutResult","Разведка нашла огромный флот чего то ожидающий. [Разведка:{0}]"},
        {"dialog_secretTryPrevent","Постараться предотвратить конфликт"},
        {"dialog_secretRun","Бежать"},
        {"dialog_secretSeeHugeArmy","Внезапно вы встречаете огромную армию. Во всеоружии! [Разведка:{0}]"},
        {"dialog_secretHaveCredits","Теперь у вас есть [кредитов:{0} и {1}]"},
        {"dialog_secretYouRun","Вы сбежали. {0} [Разведка:{1}]"},
        {"dialog_secretFight","Сражаться"},
        {"dialog_secretRunFail","Побег не удался! [Разведка:{0}]"},
        {"dialog_secretApplyDeal","Принять сделку"},
        {"dialog_secretLeave","Покинуть"},
        {"dialog_secretTheyMessage","Вам пришло предложение о сделке."},
        {"dialog_secretTheyGoKill","Теперь они собираются прибить вас. Дипломатия не самая сильная ваша сторона."},
        {"dialog_secretPartGo","Часть флота отделилась и отправилась проверить сигнал."},
        {"dialog_secretDoProvocation","Спровоцировать."},
        {"dialog_secretWait","Ждать."},
        {"dialog_secretSecondCome","{0} приближается."},
        {"dialog_secretSearchPlace","Обыскать местность."},
        {"dialog_secretTheyEnd","Сделка завершена и они готовятся к прыжку."},
        {"dialog_secretTake","Взять. [Кредиты:{0}]"},
        {"dialog_secretForgotCredits","Выглядит как будто они забыли что то."},
        {"dialog_secretTakeAll","Взять все и сваливать."},
        {"dialog_secretAppearSecond","Пока вы совершали сделку появился другой флот."},
        {"dialog_secretFindGoods","После масштабной битвы вы можете собрать трофеи. [Кредиты:{0}]"},
        {"dialog_secretProvoceFail","Провокация провалилась. Придется сражаться честно."},
        {"dialog_ArmyReputation","Репутация {0}"},

        {"dialog_finalStartReady","Вы добрались до вашей главной цели. Все готово для продолжения ."},
        {"dialog_finalStartNotReady","Сейчас здесь ничего нет."},
        {"dialog_finalProcess","Вы добрались до вашей главной цели. У вас есть {0}/{1} частей для запуска врат..\n Вам нужны все части..\n Единственный путь сделать это - использовать энергетические ячейки ваших кораблей."},
        {"dialog_finalStartFight","Но кое кто не хочет вас отпускать и вам придется пробиваться с боем"},
        {"dialog_finalEnd","Путь свободен и вы вольны лететь куда вам заблагорассудится."},
        {"questFinalStageName","Уничтожьте большой вражеский флот"},

        {"dialog_afterBattleStart","После битвы вы обнаруживаете выжившего."},
        {"dialog_afterBattleBuyout","Запросить выкуп."},
        {"dialog_afterBattleTeachPilots","Ученые могут обучить ваших пилотов"},
        {"dialog_afterBattleUpgradeSpell","Ученые могут улучшить элементы командного корабля"},
        {"dialog_afterBattleOpenCells","Взломать навигационную систему и получить информацию о секторе"},
        {"dialog_afterBattleHireAction","Нанять его"},
        {"dialog_afterBattleSearchFor","Обыскать на предмет наличия устройств"},
        {"dialog_afterBattleKillAction","Убить и забрать всё"},
        {"dialog_afterBattleRepairAction","Починить его корабль и отпустить"},
        {"dialog_afterBattleTeachOk","{0} улучшено"},
        {"dialog_afterBattleUpgradeSpellOk","Спец возможности улучшены {0}"},
        {"dialog_afterBattleUpgradeSpellFail","Нечего улучшать"},
        {"dialog_afterBattleCellOpen","Разведка завершена"},
        {"dialog_afterBattleBuyoutConfirm","Выкуп совершен:{0} кредитов"},
        {"dialog_afterBattleBuyoutFail","Выкуп не получился"},
        {"dialog_afterBattleSearchOk","Кредитов добавлено: {0}."},
        {"dialog_afterBattleSearchFail","Ничего."},
        {"dialog_afterBattleKillOk","Деньги не пахнут. {0} кредитов"},
        {"dialog_afterBattleKillFail","Он сбежал."},
        {"dialog_afterBattleHireOk","Найм совершен. Тип:{0}  Фракция:{1}"},
        {"dialog_afterBattleRepairOk","Ремонт завершен. Репутация увеличена."},
        {"dialog_afterBattleRepairFail","Ремонт неудачен."},
        {"dialog_afterBattleMicrochip","Разобрать корабль и попробовать достать микро чип для улучшений."},
        {"dialog_afterBattleMircochipOk","Чип получен"},
        {"dialog_afterBattleMircochipFail","Ничего не найдено"} ,
        {"dialog_CantAttack", "Вы не можете атаковать сейчас. Следуйте в магазин и купите оружием."},

        {"Anomaly", "Аномалия"},
        {"dialog_anomalySendScouts", "Отправить разведчиков"},
        {"dialog_anomalyBeliveMysielf", "Мне кажется я сумею сделать все сам"},
        {"dialog_anomalyGoAway","Уйти." },
        {"dialog_anomalyStart","Вы встретили странную аномалию. Кажется что она скоро пропадет. Желаете исследовать?"},
        {"dialog_anomalyFreeze","Заморозить"},
        {"dialog_anomalyExplosive","Взорвать"},
        {"dialog_anomalyImpulse","Подействовать импульсом"},
        {"dialog_anomalyFire","Поджечь"},
        {"dialog_anomalyChange","Что то изменилось."},
        {"dialog_anomalyRight","Похоже вы действуете верно."},
        {"dialog_anomalyWrong","Неверно."},
        {"dialog_anomalyNoInfo","Не информации от разведки. Что делать далее? Попыток осталось:{0}."},
        {"dialog_anomalyInfo","{0}{1}/{2} вскрыто. Что делать далее? Попыток осталось:{3}."},
        {"dialog_anomalyDeactivated","Аномалия успешно деактивирована. {0} кораблей улучшено."},
        {"dialog_anomalyNotDay","Не мой день."},
        {"dialog_anomalyDestroyed","Аномалия исчезла."},

        {"dialog_dungeonExitFinalWin","Военная база полностью разрушена"},
        {"dialog_dungeonExitGo","Забрать все и улететь"},
        {"dialog_dungeonExitFinalBattle","Это военная база."},
        {"dialog_dungeogArmyEnterStart","Это военный сектор с сильными формированиями. Вы действительно хотите отправится туда?\nПодкрепления к противнику прибудут незамедлительно.\nВы можете найти здесь некоторые уникальные предметы."},
        {"dialog_dungeogArmyFriendGoIn","Попросить ваших друзей впустить вас."},

        {"dialog_teacherImproved","Корабль {0} улучшен. Уровень:{1}"},
        {"dialog_teacherFail","Неудача."},
        {"dialog_teacherStartPilots","Это научный корабль. Они могут обучить ваших пилотов [кредитов:{0}]."},
        {"dialog_teacherNo","Нет."},
        {"dialog_Science ship","Научный корабль"},
        {"dialog_teacherStartSience", "Это научный корабль. Они могут улучшить ваш флот [кредитов:{0}]. Делаем {1}?"},


        {"battleSpells", "Особые возможности главного корабля.\nЛюбое использование требует определенное количество батарей и блокирует их на некоторый период.\nПродумывайте каждое действие заранее."},
        {"battleStart", "Битва началась.\nВсе ваши боевые корабли будут выбирать цели самостоятельно." },
        {"battleEnemy", "Вражеский флот" },
        {"TutorCloseForever", "Больше не показывать"},
        {"battleYour", "Ваш флот. Вы не можете управлять им напрямую.\nТолько изменять тактику." },
        {"battleMainShip", "Ваш командный центр. Используйте мышку для передвижения" },
        {"mapInsideInventory", "Это ваш флот.Здесь вы можете менять снаряжение вашего флота и производить улучшения."},
        {"mapMain","Глобальная карта.\nПеремещаться можно только к ближайшим отметкам." },
        {"mapInventory", "Нажмите здесь что бы снаряжать ваш флот." },
        {"mapFleetFast", "Ваш флот. Вы не можете управлять им напрямую.\nТолько изменять тактику."},
        {"mapUpgrade", "Вы можете улучшить один из ваших кораблей." },
        {"preBattle", "Приготовления к битве.\nВыбирайте подходящее снаряжение, основываясь на разведданных"},
        {"shopMain", "Магазин \nЗдесь можно покупать и продавать снаряжение. В зависимости от сектора разные вещи могут стоить разных денег."},
        {"endBattle", "Выбирайте способ что бы поделить награду.\n Если вы хотите улучшить уровень кораблей выбирайте:\"Пилотам\".\nЕсли вы хотите сами распорядится деньгами то выбирайте:\"В казну\" "},

        {"Tutorial", "Обучение"},
        {"TutorMoveGlobal", "Что бы двигать камеру используйте мышь или WSAD"},
        {"TutorHomeButton", "Что бы найти ваш флот нажмите \"Домой\""},
        {"TutorDifferentTypesCells", "В различных местах вас ждут различные события.\nПеремещаться можно только между доступными клетками.\nВыбирайте опираясь на ваше текущее состояние."},
        {"TutorDialog", "В диалогах выбирайте подходящий вариант событий."},
        {"TutorMove", "Вы можете управлять ТОЛЬКО главным кораблём.\nКликнет правой кнопкой что бы направить корабль."},
        {"TutorRecharge", "Помогайте вашим кораблям перезаряжая щит.\nЕсли один из ваших кораблей поврежден -  помогите ему"},
        {"TutorMachineGun", "Стреляйте по противникам из доступных орудий.\nЕсли у вас есть возможность нанести урон - воспользуйтесь ею"},
        {"TutorEngineLock", "Выключайте двигатели\nОтключайте противникам двигатели что бы помочь вашим кораблям попасть по ним."},
        {"TutorChangeTactics", "Изменение тактики боевого корабля.\nЕсли ваш корабль хорош только против определенных типов целей, вы можете поменять его приоритеты."},
        {"ConfirmCloseTutor", "Вы закрываете обучение.\nЕсли вы хотите повторить, вы сможете найти это в меню игры."},
        {"TutorShootMainShip", "Используйте пулемет что бы уничтожить турель."},
        {"dialog_tutorEnds", "Обучение закончено"},
        {"ChanceAfterBattle", "[Успех {0}%]"},

        {"StartTutorMoveGlobal", "Что бы двигать камеру используйте мышь или WSAD. Кликните левой кнопкой мыши туда куда вы хотите переместить корабль"},
        {"startGameNoTutor", "Советуем пройти обучение."},
        {"toGame", "Играть"},
        {"toTutor", "Вернуться"},
        {"Cancel", "Отмена"},
        {"Galaxy gate", "Врата галактики"},
        {"wantStartTutor", "Это короткое обучение. Для понимания основ игры."},
        {"TutorPreBattle", "Оснастите ваш флот"},
        {"TutorStartShop", "Купить оружие для боевого корабля."},
        {"resolutionTooLow", "Малое разрешение экрана . Возможно у вас будут проблемы. Минимум: 1280 и 720"},
        {"Move camera", "Двигать камеру"},
        {"Commander Guns", "Главные орудия"},
        {"Simple","Основной"},
        {"Advanced","Продвинутый"},

        {"ParameterTypeScouts", "Количество информации получаемое до битвы"},
        {"ParameterTypeRepair", "Каждый ход боевые корабли ремонтируются на {0} процентов."},
        {"ParameterTypeChanrgeCount", "Количество батарей в битве {0}"},
        {"ParameterTypeChanrgeSpeed", "Уменьшение времени перезарядки батарей {0}%"},
        {"ParameterTypeEngine", "Радиус телепортации {0}. Перезарядка телепортации {1}"},


        {"RaidersProConsCalc", "Бонус к скорости {0}%. Бонус к скорости поворота {1}%"},
        {"MercenaryProConsCalc", "Бонус к скорости {0}%. Бонус к скорости поворота {1}%"},
        {"FederationProConsCalc", "Ничего"},
        {"OcronsProConsCalc", "Бонусы к корпусу {0}%. Щитов нет"},
        {"KriosProConsCalc", "Бонус к щиту {0}%. Коэффициент корпуса {1}%"},
        {"loaderror", "Ошибка загрузки. Перезапустите приложение."},
        {"questNameSearchFleetMerc", "Найдите 2 части координат вражеского флота"},
        {"questSearachFleetMerc", "Одна из частей кординат найдена"},
        {"questNameKillMerc", "Уничтожьте флот"},
        {"ReadyToComplete", "Кликните для завершения"},
        {"doDestroyShip", "Уничтожите отмеченный корабль \"T\""},
        {"defendMarkedShip", "Защищайте отмеченный корабль \"T\""},
        {"defendBaseWithTurrets", "Защищайте базу с помощью турелей"},

        { "dialog_TutorialUpgradeMainShip", "Улучшить командный корабль"},
        {"dialog_WearDetailsTutor", "Оборудовать боевой корабль"},
        { "MainShipUpgradeTutor", "Обновление"},
        { "WearDetailsTutor", "Оборудование"},
        {"questNameSectorClearFedMerc", "Уничтожьте все формирования в указанном секторе"},


        {"cocpit", "Кабина"},
        {"engine", "Двигатель"},
        {"wings", "Крылья"},
        {"EParameterItemRaritynormal", "Обычный"},
        {"EParameterItemRarityimproved", "Улучшенный"},
        {"EParameterItemRarityperfect", "Особый"},

        {"EParameterShipspeed", "Скорость"},
        {"EParameterShipturn", "Поворот"},
        {"EParameterShipbodyPoints", "Корпус"},
        {"EParameterShipshieldPoints", "Щит"},
        {"EParameterShiparmor", "Броня"},
        {"EParameterShipbodyArmor", "Броня корпуса"},
        {"EParameterShipmodulsSlots", "Слоты модулей"},
        {"EParameterShipweaponSlots", "Оружейные слоты"},
        {"Goal", "Цель"},

        {"Energy storage", "Хранилище энергии"},
        {"Steal", "Украсть"},
        {"destrySeveralEnemies","Вам удалось уничтожить пару кораблей врага до начала битвы.Теперь придеться сражаться с остальными."},
        {"scoutsFailed", "Разведка не удалась. Все защитники теперь будут атаковать вас."},
        {"StoragePower", "Сила защищающего флота {0}"},
        {"creditYours", "Вы нашли {0} кредитов"},
        {"Excavations", "Раскопки"},
        {"ExcavationStart", "Перед вами раскопки. Небольшой флот прибыл до вас.\nНо тут все заминированно. Вам следует быть осторожным."},
        {"Try attack.", "Попытаться атаковать."},
        {"Come closer.","Приблизиться." },
        {"Start search at other side","Начать поиски на другой стороне" },
        {"BlowUpAlmost","Им удалось почти все взорвать. Но пара модулей смогли уцелеть:{0}" },
        {"They blow up","Они все взорвали и убежали." },
        {"TheySearching","Они что то ищут" },
        {"Threaten", "Запугать"},
        {"Offer assistance", "Предложить помочь"},
        {"TheyHaveNothing","У них ничего нет. И они все взорвали. Часть ваших кораблей повреждена." },
        {"nobodyFind", "Никто ничего не смог найти"},
        {"foundLotCreditsThey", "Они нашли кредиты первыми {0}"},
        {"NotYourDayNothung","Пусто. Не ваш день" },
        {"foundLotCredits","Вы нашли кучу кредитов {0}" },
        {"YourRartMoney", "Вам удалось что то найти. Ваша часть:{0}."},
        {"OKgo5050", "Ок, давай 50 на 50"},
        {"BonusParamField", "Бонус {0}%"},
        {"StartTutorTargetGlobal", "Что бы переместить камеру к вашему флоту нажмите 'Домой'. Для поиска цели нажмите 'Цель'."},
        {"CollectAll", "Соберите нужное количество энергетических элементов\nКнопка 'Цель' поможет найти их\nЗатем выдвигайтесь к вратам галактики что бы активировать их"},

        {"questReadyToDeliver", "Готовы к отгрузке?"},
        {"deliverItems", "Доставить предметы"},
        {"haveNotEnought", "Недостаточно предметов"},
        {"questDeliverReadyToDeliver", "Доставка"},
        {"questDeliverFinal", "предметы доставлены. Теперь наш флот готов. Выберите награду"},


        { "AdvTutorialOpenInv", "Чтобы открыть инвентарь, нажмите эту кнопку"},
        {"AdvTutorialUpgradeParameters", "Улучшите некоторые основные параметры корабля, чтобы быть более полезным в бою или после него"},
        {"AdvTutorEqupBattleShip", "Оснастить боевой корабль основными деталями \n Детали могут быть разного качества"},
        {"AdvTutorEquipShip", "Оборудуйте корабль"},
        {"AdvTutorAutoUse", "Чтобы автоматически использовать главные судовые орудия, нажмите кнопку @Авто, затем выберите орудие и цель"},
        {"AdvTutorUnsetAutoUse", "Чтобы остановить автоматическое использование орудия, нажмите правую кнопку мыши на значке орудия"},
        {"AdvTutorEquipShipWeaponsAndModules", "Следующее сражение будет достаточно трудным\nЭтот модуль добавляет ко всему оружию корабля эффект 'игнорирования щитов'"},
        {"AdvTutorUpgradeLevel", "Для некоторых модулей требуется уровень корабля\nУвеличьте уровень боевого корабля"},
        {"dialog_armyTutorIgnoreShield", "Перед битвой вы нашли оружие и модули. Экипируйте их до битвы"},
        {"wantStartAdvTutor", "Вторая часть обучения. 5 этапов."},
    };

}

