using System.Collections.Generic;


public static class RusLocalization
{
    public static Dictionary<string, string> _locals = new Dictionary<string, string>()
    {
        {"StartInfo", "Вы находитесь на самом краю обитаемого мира в отдаленом секторе.\n" +
                  "В результате спецоперации вам пришлось похитеть командный корабль и энергетический\n" +
                  " элемент на нём. Теперь единсченный выход собрать достаточное количество элементов," +
                  "\n для открытия межпространственых врат, и достаить информацию для командования."},
        {"Yes", "Да"},
        {"No", "Нет"},
        {"Ok", "Ок"},
        {"Reflected", "Эффект отражен"},
        {"CriticalDamage", "Критические повреждения. Если повреждений будет больше {0} то корабль будет уничтожен"},
        {"Event", "Событие"},
        {"RechargeSheildSpell", "Подзарядка щита на {0}%"},
        {"ArmorField", "Броня:{0}/{1}"},
        {"UnstableCore0", "Some of your ships can get damage cause your core is unstable.\n\n Find repair services to stabilize your core.\n\n If core stability level become less than -10 your fleet will be destroyed."},
        {"MapExit", "Вы действительно хотите выйти в главное меню?\nПрогресс будет сохранен и вы сможете продолжить позже."},
        {"CantByLevel", "Уровень корабля недостаточен что бы использовать это оборудование"},
        {"ReqireLevelFeild", "Требуемый уровень корабля:{0}"},
        {"CanCauseNoLevel", "Оружие невозмжно улучшить так как уровень корабля недостоточен.\nУровень корабля:{0}. Целевой уровень:{1}"},
        {"RoundWaveStrike", "Наночит всем корабля вокруг урон: [{2}/{3}].\n[Затраты:{0}/{1}]"},
        {"And", "и"},
        {"SupportModul", "Оружейный модуль. влияет на свойства оружия."},
        {"ActionModul", "Вспомотаьельный модуль."},
        {"CataclysmProcess", "{0} ячеек уничтоженно"},
        {"RemainCataclysm", "Дней осталось:{0}"},
        {"VeryEasy", "Легчайше"},
        {"Easy", "Легко"},
        {"Normal", "Нормально"},
        {"Hard", "Тяжело"},
        {"Imposilbe", "Невозможно"},
        {"Radius", "Радиус"},
        {"Sector", "Сектор"},
        {"Reload", "Перезарядка"},
        {"ShootPerTime", "Количество зарядов"},

        {"cantUpgrade", "Невозможно улучшить"},
        {"UpgParams", "Вы действительно хотите улучшить {0}?\n Стоимость {1} кредитов."},
        {"CoreSector", "Целевой сектор"},
        {"NotCoreSector", "Обычный сектор"},
        {"StatisticDifficulty", "Сложность:{0}%."},
        {"StatisticConfig", "Флот:{0}."},
        {"StatisticMapSize", "Размер галактики:{0}."},
        {"StatisticFinalArmyPower", "Сила флота:{0}."},
        {"StatisticDate", "{0}"},
        {"Fight", "В бой"},
        {"StatisticNoResult", "Нет результатов"},
        {"StatisticNoLastResult", "Ожидание игры..."},
        {"StatisticLastResult", "Последний результат:"},
        {"Sacrifice", "Пожертвовать кораблем: {0}, {1}, {2}"},

        {"EndGameDays", "Дней:{0}"},
        {"BattleWinsStat", "Побед:{0}"},
        {"OpenWeaponsEndGame","Открыты новые типы вооружения {0} и {1}"},
        {"OpenConfigEndGame", "Новый флот доступен для игры: {0}"},
        {"FrontShieldActivate", "Фронтальный щит активирован"},
        {"Crit", "Критический урон {0}!"},
        {"WinEnd", "Все хорошо, теперь вы вольны сами выбирать куда хотите направиться... ,а возможно и нет"},
        {"LoseEnd", "Ваш флот уничтожен."},
        {"RepairDroneSpell", "Запускает ремонтный дрон. Когда дрон подлетает к кораблю он начинает восстанавливать корпус. Восстановит {1}% корпуса."},

        {"Shield Locker", "Блокиратор щитов"},
        {"Auto shield", "Авто щит"},
        {"Shield regeneration", "Восстановление щитов"},
        {"Repair drone", "Ремонтный дрон"},
        {"Rocked catcher", "Уничтожитель ракет"},
        {"Deflector", "Отражатель"},
        {"Side strike", "Атака с фланга"},
        {"Engine locker", "Ломатель двигателей"},
        {"EMI mine", "Электромагнитная мина"},
        {"Power mine", "Силовая мина"},
        {"Fire mine", "Огненная мина"},
        {"Front shield", "Фронтальный щит"},
        {"Body armor", "Броня копуса"},
        {"Teleportation", "Телепортация"},
        {"Laser power", "Мощность лазеров"},
        {"Rockets power", "Мощность ракет"},
        {"Bomb power", "Мощность роя"},
        {"EMI power", "Мощность ЭМИ"},
        {"Impulse power", "Мощность импульса"},
        {"Speed", "Скорость"},
        {"BaseCenter", "Штаб"},
        {"BaseEnter", "Военная база"},
        {"Turn Speed", "Скорость поворота"},
        {"Bullet speed", "Скорость зарядов"},
        {"Spray fire", "Веерный выстрел"},
        {"Longer dist", "Увелечение дистанции"},
        {"Pusher", "Толкатель"},
        {"Burner", "Поджигатель"},
        {"Stopper", "Останавливатель"},
        {"Locker", "Выключатель"},
        {"Critical", "Критические повреждения"},
        {"AOE", "Урон по области"},
        {"Wider", "Расширитель"},
        {"Close strike", "Урон в упор"},
        {"Chain strike", "Мульти цель"},
        {"Penetrating shot", "Проникающий выстрел"},
        {"Powerful recoil", "Мощная отдача"},
        {"Shield stealer", "Похититель щитов"},
        {"More bullets", "Больше зарядов"},
        {"Power shot", "Мощный выстрел"},
        {"Fire wave", "Волная огня"},
        {"Protector", "Защитник"},
        {"Beam upgrade", "Улучшение луча"},
        {"Heavy weapons", "Тяжелый орудия"},
        {"Maximum shield", "Максимум щитов"},
        {"scout", "Разведчики"},
        {"repair", "Служба ремонта"},
        {"chargesCount", "Количество батарей"},
        {"chargesSpeed", "Скорость зарядки батарей"},
        {"engineParameter", "Перемещатель"},

        {"MainShipBlinkDesc", "Перемещает корабль в указанную точку"},
        {"MainShipBlinkName", "Прыжок"},
        {"hookShot", "Магнитная волна"},

        {"Preparing", "Подготовка"},
        {"Return", "Возвращается"},
        {"Evade enemy", "Уворачивается"},
        {"RepairAction", "Починка"},
        {"Wait", "Ожидание"},
        {"Hiding", "Прячется"},

        {"shildDamage", "Вырубатель щитов"},
        {"engineLock", "Поломщик"},
        {"lineShot", "Огненный залп"},
        {"throwAround", "Разбрасыватель"},
        {"vacuum", "Вакуум"},
        {"mineField", "Минное поле"},
        {"distShot", "Мощный выстрел"},
        {"artilleryPeriod", "Артилерия"},
        {"repairDrones", "Ремонтный дрон"},
        {"rechargeShield", "Подзарядка щитов"},
        {"roundWave", "Урон вокруг"},
        {"machineGun", "Пулемёт"},

        {"WANT_UPGRADE_WEAPON","Вы хотите улучшить ваше орудие {0}?" },
        {"WeaponMaxLevel", "Орудие имеет максимальный уровень"},
        {"Processing", "Обработка..."},
        {"Win", "Победа!"},
        {"Lose", "Поражение"},
        {"RunAwayComplete","Вы успешно сбежали" },
        {"Type", "Тип"},

        {"Regen", "Регенерация"},
        {"DamageBody", "Урон по корпусу"},
        {"DamageShield", "Урон по щитам"},
        {"ChargesCount", "Количество зарядов {0}"},
        {"ChargesDelay", "Время перезарядки {0}"},
        {"Scouted", "Разведано"},
        {"Gate", "Врата"},
        {"Home", "Домой"},
        {"Complete", "Завершено {0}"},
        {"Target", "Цель {0}"},
        {"Delay", "Задержка"},

        {"shieldLocker",  "Отключае щиты у цели."},
        {"autoShieldRepair", "Восстанавливает щиты если они будут уничтожены."},
        {"shieldRegen", "Усиленное восстановление щитов."},
        {"autoRepair", "Чинит корпус при появлении значительных повреждений."},
        {"antiPhysical", "Уничтожает физические заряды в определенном радиусе."},
        {"antiEnergy","Уничтожает энергетические заряды в определенном радиусе." },
        {"closeStrike","Когда враг близко открывает огонь." },
        {"engineLocker","Выключает двигатель цели." },
        {"systemMines", "Устанавливает системные мины,, который отключают двигатель."},
        {"damageMines","Устанавливает мины которые наносят повреждения." },
        {"frontShield","Отражает все заряды с фронтальной части." },
        {"armor", "Уменьшает повреждения по корпусу"},
        {"fireMines", "Устанавливает мины которые поджигают цели."},
        {"blink", "Перемещает корабль в различных ситуациях."},
        {"laserUpgrade", "Увеличивает урон всех лазеров на +1/+1 за уровень."},
        {"rocketUpgrade","Увеличивает урон всех ракет на +1/+1 за уровень." },
        {"EMIUpgrade", "Увеличивает урон всех эми на +1/+1 за уровень."},
        {"impulseUpgrade","Увеличивает урон всех имульсов на +1/+1 за уровень." },
        {"bombUpgrade","Увеличивает урон всех роев на +1/+1 за уровень." },
        {"WeaponSpeed", "Увеличивает скорость зарядов."},

        {"WeaponAOE", "Наносит урон всем кораблям в области {0}. Уменьшает урон на {1}%."},
        {"WeaponSector",  "Увеличивает сектор прицеливания на {0}% за уровень"},
        {"WeaponPowerShot", "Увеличивает время перезарядки на {0}%. Увеличивает урон на {1}%."},
        {"WeaponShootPerTime", "Добавляет по 1 заряду в очередь. Уменьшает урон на {0}% "},
        {"WeaponLessDist", "Уменьшает радиус стрельбы на {0}%. Увеличивает урон на {1}%."},
        {"ShipTurnSpeed", "Увеличивает скорость поворота корабля на {0}%"},
        {"ShipSpeed", "Увеличивает максимальную скорость корабля на {0}%"},
        {"ShieldDouble", "Усиливает щиты на {0}% . Уменьшает прочность корпуса на {1}%"},
        {"ShipDecreaseSpeed", "Увеличивает урон на {0}%.  Уменьшает скорость корабля на {1}%"},
        {"WeaponIncreaseDamage", "Увеличивает урон на {0}% у всех орудий типа {1}."},
        {"WeaponNoBulletDeath", "Пуля не уничтожается при столкновении с препятствием. Увеличивает время перезарядки на {0}%."},
        {"WeaponShieldPerHitDesc", "Уменьшает урон на  {0}%. Восстанавливает {1} щита за попадание."},
        {"IgnoreShieldLevel1", "Игнорирует щит. Уменьшает урон на  {0}%."},
        {"Ignore shield", "Игнорируст щит."},
        {"WeaponSelfDamage", "Добавляет +{0}/+{0} урона. При каждом выстреле наносит себе урон {1}/{1}"},
        {"WeaponPush","Отталкивает цель при попадании"},
        {"WeaponCrit","С {0}% шансом наносит {1} дополнительного урона в тело."},
        {"DamageTimeEffect","с шансом {0}% на {1:0} сек, при попадании."},
        {"DamageTimeEffectEngine","Отключает двигатели {0}"},
        {"DamageTimeEffectShield","Отключает щиты {0}"},
        {"DamageTimeEffectFire","Поджигает на {0}"},


        {"questKills", "{0} Убийств"},
        {"Fleet", "Флот"},
        {"RechargeButton","Подзарядка щитов.\nЗатраты[{0}/{1}]" },
        {"BuffButton", "Увеличивает характеристики корабля.\n[Затраты:{0}/{1}]"},
        {"PowerWeaponButton", "Увеличивает мощность орудий на следущий выстрел.\n[Затраты:{0}/{1}]"},
        {"CellScouted", "Координаты разведаны [{0},{1}]"},
        {"PriorityTarget", "Приоритетная цель"},
        {"BaitPriorityTarget","Приманка"},
        {"engineCrash","Двигатель отключен на {0:0} сек" },
        {"shieldCrash","Щиты отключены на {0:0} сек" },
        {"fireCrash", "Пожар началлся! {0:0} сек"},
        {"winAgainst", "Победы против {0}"},
        {"damageByQuest", "Урон от {0}"},
        {"killLight","Уничтожить легкий кораблей" },
        {"killMed","Уничтожить средних кораблей" },
        {"killHeavy", "Уничтожить тяжелых кораблей"},
        {"mainShipKills", "Уничтожить командиром"},
        {"upgradeWeapons", "Улучшить оружия"},
        {"sellModuls", "Продать модулей"},
        {"PriorityTargetDesc", "Все ваши корабли буду стараться атаковать выбранную цель."},
        {"BaitPriorityTargetDesc","Все корабли врага будут атаковать приманку" },
        {"SpellModulChargers", "Требуеться батарей: {0} на {1} сек."},
        {"ArtillerySpell","Обстреливает зону. Всего выстрелов {0}. Урон от каждого попадания:{2}/{1}." },
        {"EnerguLockSpell","Отключает двигатели всем кораблям противника в радиусе {1} на {0} сек." },
        {"LineSHotSpell","Выстрел 3 зарядами в заданном направлении. Базовый урон: {0}/{1}. Период горения {2} сек. Общий урон от огня:{3}" },
        {"MinesSpell","Устанавливает {0} мин на {1} сек в выбранную локацию. Урон от каждой мины: {2}/{3}" },
        {"ShieldOffSpell","Выключает щиты у кораблей в радиусе на {0} сек. И наносит {1} урона щитам." },
        {"TrowAroundSpell", "Create a shockwave witch throw around all ships in radius with power {0}. And shield damage {1}."},
        {"DescHookShotSpell", "Притягивает все в области к вашему командному кораблю и отключает двигатели на {0} сек"},
        {"KillUIPilotMini","Убийств:{0}" },
        {"KillUIPilot", "Убийств:{0}/{1}"},
        {"Remain","Осталось" },
        {"EngineDest", "Двигатель поврежден"},
        {"ShieldDest","Щит отключен" },
        {"FireDest", "Пожар на борту"},
        {"Retreat", "Сбежать"},
        {"Shop", "Магазин"},
        {"SectorDungeon", "Военная база"},
        {"DoWantRetire","Вы хотите сбежать?" },
        {"NoSafeGame","Не сохраненных игр" },
        {"MaxLevel", "Максимальный"},
        {"RusLang", "Русский"},
        {"EngLang", "Англисский"},
        {"ReloadToLoc", "Перезапустите игру что бы использовать выбранный язык"},
        {"SettingsWindow", "Настройки"},

        {"DamageInfoUI", "Урон: {0}/{1}" },
        {"KillsInfoUI", "Убийства: {0}"},
        {"ReputationChanges", "{2} Репутация изменена {0} => {1}."},
        {"ReputationData", "{0} репутация: {1}"},

        {"Turret", "Турель" },
        {"Destroyed", "Уничтожены" },
        {"Completed", "Завершено"},
        {"StartNewGameFieldSize", "Размер сектора"},
        {"StartNewGameCoresCount","Ключевые элементы" },
        {"StartNewGameSectorsCount", "Количество секторов"},

        {"EngineLockNameA1", "Радиус"},
        {"EngineLockNameB2", "Уменьшение времени"},
        {"EngineLockDescA1", "Увеличесние радиуса действия на {0}"},
        {"EngineLockDescB2", "Уменьшение время перезарядки батарей на {0} сек"},

        {"ArtilleryNameA1", "Заряды"},
        {"ArtilleryNameB2", "Ускорение"},
        {"ArtilleryDescA1", "Увелечение количества зарядов на {0}"},
        {"ArtilleryDescB2", "Уменьшение периода между выстрелами на {0} сек"},

        {"DistShotNameA1", "Блок двигателя"},
        {"DistShotNameB2", "По площади"},
        {"DistShotDescA1", "Повреждает двигатель при попадании на {0} сек"},
        {"DistShotDescB2", "Наносит повреждения ближайшим противникам в радиусе {0}"},

        {"LineShotNameA1", "Проникающий"},
        {"LineShotNameB2", "Термит"},
        {"LineShotDescA1", "Заряд не умирает при попадании"},
        {"LineShotDescB2", "Увеличивает силу горения на {0}"},

        {"MachineGunNameA1", "Мульти выстрел"},
        {"MachineGunNameB2", "Больше зарядов"},
        {"MachineGunDescA1", "Так же выстреливает по всем ближайшим целям. Количество зарядов {0} по каждой цели"},
        {"MachineGunDescB2", "Больше зарядов в очереди. Количество зарядов {0}"},

        {"MinesSpellNameA1", "Поджог"},
        {"MinesSpellNameB2", "Взрыв"},
        {"MinesSpellDescA1", "Добавляет урон от огня на {0} сек"},
        {"MinesSpellDescB2", "Отключает двигатели на {0} сек"},

        {"RechargeSheildNameA1", "По области"},
        {"RechargeSheildNameB2", "Блокиратор"},
        {"RechargeSheildDescA1", "Так же накладывает эффекты на ближайшие корабли в радиусе {0}"},
        {"RechargeSheildDescB2", "На {0} сек накладывает на цель сопротивление ко всем эффектам"},

        {"RepairDroneNameA1", "Щит"},
        {"RepairDroneNameB2", "Апгрейд"},
        {"RepairDroneDescA1", "Восстанавливает щиты на {0}%"},
        {"RepairDroneDescB2", "На {0} сек увеличивает скорость"},

        {"ShieldOffNameA1", "Батарея"},
        {"ShieldOffNameB2", "Поджог"},
        {"ShieldOffDescA1", "Требует для использования меньше батарей"},
        {"ShieldOffDescB2", "Добавляет урон от огня на {0} сек"},

        {"TrowAroundNameA1", "Разрушитель"},
        {"TrowAroundNameB2", "Разрядка"},
        {"TrowAroundDescA1", "Отключает двигатели для попадании на {0} сек"},
        {"TrowAroundDescB2", "Разряжает всё оружие цели"},

        {"VacuumNameA1", "Радиус"},
        {"VacuumNameB2", "Батареи"},
        {"VacuumDescA1", "Увеличивает радиус поражения на {0}"},
        {"VacuumDescB2", "Уменьшает время перезарядки батарей на {0} сек"},

        {"HookShotNameA1", "Радиус"},
        {"HookShotNameB2", "Батареи"},
        {"HookShotDescA1", "Увеличивает радиус поражения на {0}"},
        {"HookShotDescB2", "Уменьшает время перезарядки батарей на {0} сек"},

        {"RaidersProCons", "Плюсы: Хорошая скорость. Много слотов для модулей. Есть броня.\nМинусы: Мало оружейных слотов."},
        {"FederationProCons", "Плюсы: Много слотов для оружия. Регенерация щитов.\nМинусы: Низкая скорость."},
        {"MercenaryProCons", "Плюсы: Усредненные.\nМинусы: Усредненные."},
        {"OcronsProCons", "Плюсы: Отличные корпуса. Много слотов для модулей.\nМинусы: Нет щитов."},
        {"KriosProCons", "Плюсы: Сильные щиты. Отличная регенерация щитов.\nМинусы: Низкое качество корпуса."},

        {"WeaponsStart","На начало компании ваши корабли будут иметь комплект вооружения: {0} или {1}."},

        {"Paramscout", "Разведка предоставляет информацию о флоте противника.\nИногда позволяет что то своровать."},
        {"Paramrepair", "Между битвами надо ремонтировать флот.\nЭта служба вам поможет."},
        {"ParamchargesCount", "Увеличивает количество батарей главного корабля."},
        {"ParamchargesSpeed","Увеличивает скорость зарядки батарей главного корабля."},
        {"ParamEngine","Улучшает двигатель. Увеличивает скорость и ускоряет перезарядку перемещателя."},

        {"asteroidsEvent", "Астеройдный шторм"},
        {"shieldsOffEvent", "ЭМИ излучение"},

        {"Raiders", "Королевство"},
        {"Federation", "Федерация"},
        {"Mercenary", "Наёмники"},
        {"Ocrons", "Окроны"},
        {"Krios", "Криос"},
        {"Droids", "Дройды"},
        {"Light", "Лёгкие"},
        {"Medium", "Средние"},
        {"Heavy", "Тяжелые"},
        {"Base", "База"},
        {"ESideAttackStraight", "Атаковать как обычно"},
        {"ESideAttackFlangs", "Атака с флангов"},
        {"BaseDefenceYes", "Защита базы"},
        {"BaseDefenceNo", "Нет"},

        {"ECommanderPriority1Base","Атакует базу" },
        {"ECommanderPriority1Fast","Выбирать корабли для атаки с максимальной маневренностью"  },
        {"ECommanderPriority1Slow","Выбирать корабли для атаки с минимальной маневренностью"  },
        {"EGlobalTacticsFight", "Воевать"},
        {"EGlobalTacticsGoSafe", "Быть в укрытии"},

        {"ECommanderPriority1MinShield","Выбирать корабли для атаки с минимальным щитом" },
        {"ECommanderPriority1MinHealth","Выбирать корабли для атаки с минимальным уровнем корпуса"  },
        {"ECommanderPriority1MaxShield","Выбирать корабли для атаки с максимальным щитом"  },
        {"ECommanderPriority1MaxHealth","Выбирать корабли для атаки с максимальным уровнем корпуса"  },
        {"ECommanderPriority1Any", "Атаковать любые корабли"},
        {"ECommanderPriority1Light","Приоритет на лёгкие корабли" },
        {"ECommanderPriority1Mid","Приоритет на средние корабли" },
        {"ECommanderPriority1Heavy", "Приоритет на тяжелые корабли"},
        {"QuestReward", "Выберите одну награду"},
        {"Reputation", "Репутация"},
        {"Inventory", "Инвентарь"},
        {"ReputationElement", "Врагов:{0}"},
        {"Trickturn", "Быстрый поворот"},
        {"Trickloop", "Петля"},
        {"Tricktwist", "Бочка"},
        {"Settings", "Настройки"},
        {"Private", "Рядовой"},
        {"Lieutenant", "Лейтенант"},
        {"Achievements", "Достижения"},
        {"Captain", "Капитан"},
        {"Major", "Майор"},
        {"OpenNew", "Разблокировать"},
        {"FinalSector", "Галактические врата"},
        {"Attack", "Атака"},
        {"AttackHalfLoop", "Спец прием"},
        {"Evade", "Уворот"},
        {"Level", "Уровень"},
        {"NotEnoughtBattries", "Батареи не заряжены!"},
        {"reloadBoost", "Время перезарядки трюков:{0}"},
        {"PointsToOpen", "Очков для открытия стартовых опций:"},
        {"SpellMaxLevel", "Максимальный уровень: {0}"},



        {"descWinner", "Win at 1 battle"},
        {"descCaptain", "Win at 10 battle"},
        {"descMayor", "Win at 100 battle"},
        {"descTeam five", "Hire all faction at one army"},
        {"descFighter", "Destroy 100 enemy ships"},
        {"descDestroyer", "Destroy 1000 enemy ships"},
        {"descAnnihilator", "Destroy 10000 enemy ships"},
        {"descMerWin", "Win as mercenaries"},
        {"descFedWin", "Win as federation"},
        {"descKriWin", "Win as krios"},
        {"descOcrWin", "Win as ocrons"},
        {"descRdrWin", "Win as kingdom"},

        {"nameWinner", "Winner"},
        {"nameCaptain", "Captain"},
        {"nameMayor", "Mayor"},
        {"nameTeam five", "Team five"},
        {"nameFighter", "Fighter"},
        {"nameDestroyer", "Destroyer"},
        {"nameAnnihilator", "Annihilator"},
        {"nameMerWin", "Ringleader"},
        {"nameFedWin", "Chancellor"},
        {"nameKriWin", "Experimentalist"},
        {"nameOcrWin", "Fanatic"},
        {"nameRdrWin", "King"},


        {"ShipsRepaired", "Ships Repaired"},

        {"MercGlobal", "Убежище наемников"},
        {"NotEnoughtMoney", "Недостаточно денег"},
        {"leave", "Уйти"},
        {"HireMerc", "Нанять {1} {0}. Уровень:{2}. Стоимость:{3} кредитов."},
        {"Take", "Взять"},
        {"BrokenItem", "Вещь сломана {0}"},
        {"StabilizaInfo", "Уровень стабилизации:{0}"},
        {"MainElements", "Энергетических элементов"},

        {"Health", "Корпус"},
        {"Shield", "Щит"},
        {"TurnSpeed", "Поворот"},
        {"Unknown", "Неизвестно"},

        {"Laser", "Лазер"},
        {"Rocket", "Ракеты"},
        {"Impulse", "Импульс"},
        {"Swarm", "Рой"},
        {"EMI", "ЭМИ"},
        {"Beam", "Луч"},
        {"MovingArmy", "Спец флот {1}\nСтатус:{2}. Мощь:{3}"},
        {"MovingArmyBorn", "Спец флот {0} появился. Координаты:{1}"},
        {"AdditionalPower", "Улучшения флотов"},

        {"AddCredits", "Добавленно кредитов:{0}"},
        {"Comparable", "Сопоставим"},
        {"Risky", "Рисковано"},
        {"Easily", "Легко"},
        {"confirmDismiss", "Вы действительно хотите удалить корабль {0}?"},
        {"MovingArmyName", "Спец флот {0}"},
        {"RelocateTo", "Переместился в:{0}"},

        {"Demo", "Это демо версия игры. Пока что мы не готовы показать вам больше. Максимальное количество посещенных секторов:{0}. Максимум ходов:{1}"},

        {"RecievePoints", "Вы будите получать очки за победы. Количество зависит от сложности. Также можно получить очки выигрывая битвы."},
        {"AA_FXAA", "Сглаживание"},
        {"Sound", "Звук"},
        {"battlefield", "Поле боя"},
        {"Amry","Армия"},
        {"Trader","Торговец"},
        {"BrokenNavigation", "Заблудившийся"},
        {"modifBaseStart", "Это станция модификаций. Вы можете попытаться модифицировать ваше оборудование."},
        {"modifCellName", "Станция улучшения"},

        {"scout_shipType", "Нет информации о типах кораблей"},
        {"scout_weapons", "Нет информации об оружии"},
        {"scout_level", "Нет информации об уровни кораблей"},
        {"scout_moduls", "Нет информации о модулях"},
        {"scout_spells", "Нет информации о спец оружии"},
        {"targteFar", "Цель слишком далеко"},

        {"DescVacuumSpell", "Создает вакуум в указанной точке и затягивает туда. Сила:{0}. Урон по щитам:{1}"},
        {"ChainModulDesc", "Shoot to all targets in radius. Decrease damage on {0}%"},
        {"FireNearModulDesc", "Поджигает врагов рядом при выстреле на {0} сек."},
        {"SprayModulDesc", "Shoot with {0} bullets instead on one. Increase reload time by {1}%."},
        {"WeaponSpeedModulDesc", "Increase bullet speed by {0}% per level"},
        {"DescWeaponDistModul", "Increase aim radius by {0}% per level"},

        {"MachineGunSpellDesc", "Series  of {0} fast bullets. Damage: {1}/{2}"},
        {"DistShotSpell", "Single bullet. Only hull damage {0}. Additional damage dependence on distance."},
        {"DistShotSpellSpecial", "Single bullet.  Only hull damage {0}. Additional damage dependence on distance. If target have no shield destroy engine for {1} sec."},

        {"rep_adv_friend", "Вы союзники. Возможно вам даже помогут."},
        {"rep_adv_neutral", "Вам придется сражаться с флотами, но можно и торговать."},
        {"rep_adv_negative", "Вы все еще можете торговать но цены вас не порадуют"},
        {"rep_adv_enemy", "Торговать запрещено. только битвы! Спец силы будут преследовать вас."},
        {"rep_friend", "Союзники"},
        {"rep_neutral", "Нейтральное"},
        {"rep_negative", "Негативное"},
        {"rep_enemy", "Враг"},
        {"DemoStart", "Это демо версия игры. Пока что мы не готовы показать вам больше."},
        {"DemoStart2", "You will have only 25 turns. And some mechanics will be blocked."},
        {"RepairCompete","Repair Compete"},
        {"RepairStation","Repair Station"},

        {"dialog_ok", "Ок"},
        {"dialog_MovingArmyStart", "Вы встретились со спец силами и окружены."},

        {"dialog_MovingArmyFight", "В битву"},
        {"dialog_MovingArmyWin", "Спец силы уничтожены."},
        {"dialog_MovingArmyGerReward", "Покинуть место."},

        {"dialog_shopEnemy", "Перед вами магазин. С вами никто торговать не будет. Вы враг." },
        {"dialog_shopTrade", "Перед вами магазин. Желате обменяться товарами?" },
        {"dialog_repairEnemy", "Это ремонтная станция. Они не будут помогать вам." },
        {"dialog_repairStart", "Это ремонтная станция. Здесь мы можем оремонтировать свой флот." },
        {"dialog_fixCrit", "Починить все критичесие повреждения. Стоимость:{0}." },
        {"dialog_repairCritFixed", "Критические повреждения устранены" },
        {"dialog_repairAll", "Починить всё.{0} кредитов" },
        {"dialog_repairNotEnough", "Нехватает кредитов" },


        //DILOGS ASTEROIDS
        {"dialog_asteroid_nothingComplete", "Все отлично. Вы можете продолжать двигаться" },
        {"dialog_asteroid_nothingCompleteRepair","Некоторые корабли повреждены и требуют ремонта. Вы можете продолжать двигаться" },
        {"dialog_asteroid_start", "Большое астеройдное поле. Вам нужно какито образом пробраться на другую сторону." },
        {"dialog_asteroid_fireAll","Открыть огонь из всех орудий" },
        {"dialog_asteroid_slow","Медленно продвигаться через поле." },
        {"dialog_asteroid_brokenShip","Вы видите поврежденный корабль {0}." },
        {"dialog_asteroid_brokenShipRepair", "Попытаться отремонтировать его [Ремонтная служба:{0}]."},
        {"dialog_asteroid_brokenShipdecompile","Переработать его на детали для продажи." },
        {"dialog_repairResultFull", "Этот корабль не может быть полностью оремонтирован, но кое какие детали вы можете забрать. {0}"},
        {"dialog_repairResultCant", "Этот корабль не может быть полностью оремонтирован, но у вас нет места для неповрежденных деталей."},
        {"dialog_asteroid_weaponsFire","Выстрелы акетами легко расчищают вам путь." },
        {"dialog_asteroid_weaponsFail", "Ваши орудия не обладают достаточной мощью что бы открыть путь. Некоторые корабли повреждены"},
        {"dialog_asteroid_haveWay", "Наконецто вы нашли выход! Некоторые корабли повреждены"},
              
        //DILOGS BATTLEFIELD
        {"dialog_battlefield_start","Вы видите 2 флота {0} в боквой готовности друг напротив друга " },
        {"dialog_battlefield_provocate", "Спрятаться и спровоцировать их бой"},
        {"dialog_battlefield_reconcile","Постараться примирить стороны" },
        {"dialog_battlefield_thanks","Спасибо!" },
        {"dialog_battlefield_diplomacyWin", "Ваша дипломатия была превосходна. Они не собираются сражаться и высылают вам подарок. Репутация добавлена {0}."},
        {"dialog_battlefield_run","Бежать!" },
        {"dialog_battlefield_shoot","Выстрелить рядом!" },
        {"dialog_battlefield_diplomacyFail","Ваша дипломатическая попытка провалилась. И теперь они решили убить вас." },
        {"dialog_battlefield_shit", "Неудано."},
        {"dialog_battlefield_theyAttack","Это явно не ваш день. Приготовиться к обороне!" },
        {"dialog_battlefield_ufff", "Уффф... Великопелно."},
        {"dialog_battlefield_stopAttack","Они не обращая внимания друг на друга убегают. Возможно это не так уж и плохо, по крайней мере сегодня вы спасли немного жизней." },
        {"dialog_battlefield_youRun", "Вы сбежали"},
        {"dialog_battlefield_artillery","Подловить момент и открыть артилерийский огонь" },
        {"dialog_battlefield_wait","Ждать" },
        {"dialog_battlefield_theyBattle","Они начали сражение." },
        {"dialog_battlefield_killEachOther", "Сражение окончилось. Они успешно перебили друг друга. Но зато вы смогли найти немного кредитов на поле боя {0}."},
        {"dialog_battlefield_isee", "Да"},
        {"dialog_battlefield_battleHaveWinner", "Битва закончилась.Победившая сторона забрала трофеи и улетела."},
        {"dialog_battlefield_good","Хорошо" },
        {"dialog_battlefield_goodSHot", "Отличный выстрел. Вы всех уничтожили. После битвы вам удалось найти немного вещей."},
        {"dialog_battlefield_fight","Сражаться" },
        {"dialog_battlefield_killYou","Теперь они хотят уничтожить вас." },

        //DIALOG_BROKEN_NAVIGATION
        {"dialog_navigation_start","Вы поймали сигнал о помощи" },
        {"dialog_navigation_closer","Приблизиться" },
        {"dialog_navigation_trap", "Ловушка!"},
        {"dialog_navigation_fight", "В битву"},
        {"dialog_navigation_askHelp","Вы видите корабль {0} с поломанной навигационной системой. О просит вас о помощи" },
        {"dialog_navigation_shelter","Выстать вашего разведчика что бы он помог ему добраться до убежища. [Разведка: {0}]" },
        {"dialog_navigation_repair","Попытаться починить его навигационную систему. [Ремонт: {0}]" },
        {"dialog_navigation_gift", "Ваша награда: {0}"},
        {"dialog_navigation_noFree", "Нет места для награды"},
        {"dialog_navigation_scouted", "{0} мест открыто на карте."},
        {"dialog_navigation_shelterOk","Вы успешно проводили его в укрытие. {0}." },
        {"dialog_navigation_repairOk","Вы успешно починили корабль. Репутация добавлена." },
        {"dialog_navigation_tryHire", "Предложить присоедениться"},
        {"dialog_navigation_takeMoney","Взять деньги" },
        {"dialog_navigation_hired","Корабль нанят {0}." },
                            
        //DIALOG_CHANGE_ITEM
        {"dialog_changeitem_start","Этот корабль желает торговать с вами. {0}" },
        {"dialog_changeitem_tradeData","\nОни предлагают поменять {0} на {1}" },
        {"dialog_changeitem_ok","Хорошо. Меняемся." },
        {"dialog_changeitem_no","Нет, спасибо." },
        {"dialog_changeitem_nothing","У вас нет ничего, что было бы им интересно" },

        {"dialog_armySectorEvent","Событие:{0}\n" },
        {"dialog_armyFrendly", "Этот флот выглядит дружелюбно.\n {0}"},
        {"dialog_armyBuyOut","Попытаться откупиться. [Стоимость :{0}]" },
        {"dialog_armyStronger", "Вы видите враждебно настроенный флот. Они явно сильнее чем вы. Будем драться? \n {0}"},
        {"dialog_armyShallFight","Вы видите враждебно настроенный флот. Будем драться? \n {0}" },
        {"dialog_armyNeutral", "Этот явно флот не собирается вас атаковать первыми. \n {0}" },
        {"dialog_armyAskHelp",  "Попросить о помощи. [Репутация:{0}]"},
        {"dialog_armyRun","Убежать" },
        {"dialog_armyRunComplete","Вы сбежали." },
        {"dialog_armyRunFail", "Неудано! Теперь придеться драться."},
        {"dialog_armyBuyoutComplete","Вы откупились. Потеряно {0} кредитов." },
        {"dialog_Attack","Атаковать" },

        {"dialog_coreAttack","Атаковать." },
        {"dialog_coreTargetProtect","Цель находится под защитой." },
        {"dialog_coreBuy","Выкупить за {0} кредтов." },
        {"dialog_coreUseDiplomacy","Попытаться договориться." },
        {"dialog_coreSendScouts","Выслать разведку, что бы они выкрали цель." },
        {"dialog_coreFleetHave","Этот флот нашел первыми вашу цель. \n {0}" },
        {"dialog_coreFleetHaveFriend","Дружественный флот уже нашел ваше цель. Можете попытаться договориться. Или выкупить.\n {0}" },
        {"dialog_coreWasPurchase","Вы приобрили это. {0}/{1}" },
        {"dialog_coreElementYour","Элемент у вас. {0}/{1}" },
        {"dialog_coreFight","Плохо. пора драться." },
        {"dialog_coreFailSteal","Неудачно. Пока вы ждали ваших разведчиков к ним подошло подкрепление и теперь вы не можете сбежать." },
        {"dialog_corePartYours", "Цель теперь у вас."},
        {"dialog_coreDiplomacyFail", "Они не хотят отдавать вам элемент"},

        {"dialog_hirePay", "Pay"},
        {"dialog_hireAttack", "You won't pay. Instead of it, you will just want to kill them all."},
        {"dialog_hireEnter","Space base inside big asteroid. Have impressive protection. \nEnter not free. Pay {0} to enter" },
        {"dialog_hireSomebody","You can try to hire somebody here." },
        {"dialog_hireMax","You have maximum size of fleet." },
        {"dialog_hireComplete","Hire complete" },

        {"Prisoner","Prisoner"},
        {"dialog_prisonerStart","Criminal try to escapes from the {0} police. But your fleet can catch him"},
        {"dialog_prisonerBuy","Buy stolen item. [Cost:{0}]"},
        {"dialog_prisonerCatch","Catch and return to police."},
        {"dialog_prisonerHire","Hire him"},
        {"dialog_prisonerHide","Hide him from police. [Reputation:{0}]"},
        {"dialog_prisonerHired","Criminal hired. Reputation removed {0}"},
        {"dialog_prisonerYourItem","Your item: {0}"},
        {"dialog_prisonerNoSpace","Not free space for item"},
        {"dialog_prisonerComplete","Complete. {0}"},
        {"dialog_prisonerHideOk","You successfully hide criminals ship. Credits add {0}"},
        {"dialog_prisonerFailFight","Fail! Now you will fight with police."},
        {"dialog_prisonerCatchOk","You successfully catch him. Reputation added"},
        {"dialog_prisonerBuyFail","You don't have enough money. Criminal just fly away"},

        {"ScienceLaboratory","Science laboratory"},
        {"dialog_scLabStart","You are close to {0} science laboratory. But this one is under siege."},
        {"dialog_scLabAttackNow","Attack immediately"},
        {"dialog_scLabContact","Contact with fleet commander"},
        {"dialog_scLabSedScouts","Send scouts to laboratory"},
        {"dialog_scLabFrighten","Try to frighten them."},
        {"dialog_scLabBetterContact","No, better I contact with them."},
        {"dialog_scLabNotRegular","This isn't regular army. We can try to frighten them."},
        {"dialog_scLabGoStation","Go to station."},
        {"dialog_scLabTheyRun","They running away!."},
        {"dialog_scLabFight","Fight"},
        {"dialog_scLabTotalFail","Fail! They just launch rockets to laboratory and now wants to kill you."},
        {"dialog_scLabGiveCredits","Maybe if just give you some credits and you will leave [Credits:{0}]"},
        {"dialog_scLabSimpleThiefs","They look like simple thiefs."},
        {"dialog_scLabTheLeave","They leaving."},
        {"dialog_scLabBadJoke","Bad joke! [Not enough credits]"},
        {"dialog_scLabAllKilled","All scientists were killed."},
        {"dialog_scLabImproveMain","Improve main ship."},
        {"dialog_scLabImproveBattle","Improve battle ships."},
        {"dialog_scLabScientsChoose","Scientists are alive. And they can improve your army"},
        {"dialog_scLabShipUpgraded","{0} upgrade at ship {1} Upgraded."},
        {"dialog_scLabAllMax","All your ships have max level."},
        {"dialog_scParamUpgraded","{0} Upgraded"},
        {"dialog_scLabNotingUpgrade","Nothing to improve."},

        {"dialog_secretStart","A lot of space garbage and other useless thing here. Do you want to investigate?"},
        {"dialog_secretSendScouts","Send scouts"},
        {"dialog_secretHideWait","Hide and wait"},
        {"dialog_secretSendFake","Send fake signal"},
        {"dialog_secretAttack","Attack!"},
        {"dialog_secretConnectWith","Connect with commander."},
        {"dialog_secretScoutResult","Scouts find a huge fleet, waiting for something. [Scouts:{0}]"},
        {"dialog_secretTryPrevent","Try to prevent conflict"},
        {"dialog_secretRun","Run"},
        {"dialog_secretSeeHugeArmy","Suddenly you see a huge army. And they are ready! [Scouts:{0}]"},
        {"dialog_secretHaveCredits","And now you have [credits{0} and {1}]"},
        {"dialog_secretYouRun","You run away. {0} [Scouts:{1}]"},
        {"dialog_secretFight","Fight"},
        {"dialog_secretRunFail","Running away failed! [Scouts:{0}]"},
        {"dialog_secretApplyDeal","Apply deal"},
        {"dialog_secretLeave","Leave"},
        {"dialog_secretTheyMessage","They send you a message with trade options."},
        {"dialog_secretTheyGoKill","Now they going to kill. Diplomacy is not your good side."},
        {"dialog_secretPartGo","Part of fleet going to check signal."},
        {"dialog_secretDoProvocation","Do provocation."},
        {"dialog_secretWait","Wait."},
        {"dialog_secretSecondCome","{0}s army coming."},
        {"dialog_secretSearchPlace","Search place."},
        {"dialog_secretTheyEnd","They complete trade, and ready to jump."},
        {"dialog_secretTake","Take. [Credits:{0}]"},
        {"dialog_secretForgotCredits","Looks like they forgot some credits."},
        {"dialog_secretTakeAll","Take all and run."},
        {"dialog_secretAppearSecond","While trading, appears another fleet."},
        {"dialog_secretFindGoods","After massive battle you find some goods. [Credits:{0}]"},
        {"dialog_secretProvoceFail","Your provocation failed. Now fight."},

        {"dialog_finalStartReady","This is your main goal. You have {0}/{1} parts to open gates.\n You are ready to go in."},
        {"dialog_finalStartNotReady","This is your main goal. You have {0}/{1} parts to open gates.\nNow you should acquire all others.\n Only one way to do it send one of your ships to block energy on gates. \n But you don't have enought ship \n Your are dead."},
        {"dialog_finalProcess","This is your main goal. You have {0}/{1} parts to open gates.\n Now you should acquire all others.\n Only one way to do it send one of your ships to block energy on gates. "},
        {"dialog_finalStartFight","But somebody don't want let you go and attacks you"},
        {"dialog_finalEnd","Now way is free and you can go whatever you want."},

        {"dialog_afterBattleStart","After battle one of enemy ship are alive."},
        {"dialog_afterBattleBuyout","Ask for bayout, maybe they send some credits to you"},
        {"dialog_afterBattleTeachPilots","Sciences from ship can teach some of your pilots"},
        {"dialog_afterBattleUpgradeSpell","Sciences from ship can try ti upgrade your main ship"},
        {"dialog_afterBattleOpenCells","Unlock navigation system to scout all sector"},
        {"dialog_afterBattleHireAction","Hire them"},
        {"dialog_afterBattleSearchFor","Search for money or items"},
        {"dialog_afterBattleKillAction","Kill them and take all goods"},
        {"dialog_afterBattleRepairAction","Repair him and leave him"},
        {"dialog_afterBattleTeachOk","{0} upgraded"},
        {"dialog_afterBattleUpgradeSpellOk","Big gun upgraded {0}"},
        {"dialog_afterBattleUpgradeSpellFail","Nothing to upgrade"},
        {"dialog_afterBattleCellOpen","All sectors cell scouted"},
        {"dialog_afterBattleBuyoutConfirm","Buyout confirm credits:{0}"},
        {"dialog_afterBattleBuyoutFail","Buyout fail"},
        {"dialog_afterBattleSearchOk","Credits add: {0}."},
        {"dialog_afterBattleSearchFail","Nothing."},
        {"dialog_afterBattleKillOk","Money doesn't smell. {0}"},
        {"dialog_afterBattleKillFail","He running away."},
        {"dialog_afterBattleHireOk","You hired a new pilot. Type:{0}  Config:{1}"},
        {"dialog_afterBattleRepairOk","Repair complete reputation add"},
        {"dialog_afterBattleRepairFail","Repair fail."},

        {"dialog_dungeonExitFinalWin","This military base completly destoyed"},
        {"dialog_dungeonExitGo","Grab all items and go"},
        {"dialog_dungeonExitFinalBattle","This is main militaly base at this sector"},
        {"dialog_dungeogArmyEnterStart","This is military sector. Do you really want to go there? This sector have only one exit on the other side."},
        {"dialog_dungeogArmyFriendGoIn","Ask your friend to go in."},

        {"dialog_teacherImproved","Ship {0} Improved. Pilot level:{1}"},
        {"dialog_teacherFail","Fail."},
        {"dialog_teacherStartPilots","This is science ship. They can teach some of your pilots [credits:{0}]."},
        {"dialog_teacherNo","No, thanks."},
        {"dialog_Science ship","Science ship"},
        {"dialog_teacherStartSience", "This is science ship. They can improve your fleet [credits:{0}]. Do you want to upgrade {1}?"},


        {"battleSpells", "Commander ship special options.\nAny shot will take some batteries for a period.\nYou must catch the moment to use them successfully."},
        {"battleStart", "Battle starts.\nAll your ships will choose target and attack by self." },
        {"battleEnemy", "Enemies fleet" },
        // {"TutorMyMainShip", "Your main ship. To move it just click right mouse button on map."},    
        {"TutorCloseForever", "Больше не показывать"},
        {"battleYour", "Your fleet. You can't control it directly.\nOnly choose tactics." },
        {"battleMainShip", "You can control commander ship. Use mouse to select and move it" },
        {"mapInsideInventory", "This is your fleet page. Here you can change equipment of your ships, or do some upgrades."},
        {"mapMain","This is global map.\nYou can move only to near places. To move click to point you want to go." },
        {"mapInventory", "Click here to choose equipment of your fleet." },
        {"mapFleetFast", "Your fleet. You can't control it directly.\nOnly choose tactics."},
        {"mapUpgrade", "One of your ships can be upgraded." },
        {"preBattle", "Preparation for the battle.\nChoose equipment suitable against the current opponent, based on information from scouts"},
        {"shopMain", "This is shop \nHere you can buy or sell something. Different good at different sectors can costs different money. Try to sell and buy at right sectors"},
        {"endBattle", "Choose a way to split bonus credits.\n If you want to level up battle ships choose \"to pilots\".\nIf you want to buy weapons or upgrade something choose \"to main\" "},

    };

}

